//! Generates and drift-gates `sdks/srp-test-vectors.json`.
//!
//! Eleven SDKs implement SRP-6a independently. This file is the executable
//! definition they are all checked against — and, just as importantly, the gate
//! that stops the server's implementation from moving without the vectors (and
//! therefore every SDK's conformance test) moving with it.
//!
//! To regenerate after an intentional protocol change:
//!
//! ```bash
//! UPDATE_SRP_VECTORS=1 cargo test -p axiam-auth --test srp_vectors_test
//! ```
//!
//! Then re-sync the file into all eleven SDK repositories, exactly as
//! `CONTRACT.md` and `openapi.json` are re-synced. A change here without that
//! fan-out is a silent cross-language break.

use std::path::PathBuf;

use axiam_auth::srp::{ExchangeVector, deterministic_exchange};
use axiam_core::models::srp::SrpGroup;

/// Where the vectors live, relative to this crate.
fn vectors_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("sdks")
        .join("srp-test-vectors.json")
}

/// Fixed inputs, chosen rather than random.
///
/// Two properties are deliberate. The salt and `x` include a **leading zero
/// byte**, because that is exactly the case an implementation that forgets
/// `PAD()` gets wrong — and it gets it wrong only about one time in 256, which
/// in production reads as a flaky network rather than as a bug. And the
/// identity contains a non-ASCII character, so an SDK that hashes a
/// platform-default encoding instead of UTF-8 fails here rather than for one
/// unlucky user.
fn fixtures() -> Vec<ExchangeVector> {
    let salt = {
        let mut s = [0u8; 32];
        s[1..].copy_from_slice(&[0xA3u8; 31]);
        s // s[0] == 0x00
    };
    let x = {
        let mut x = [0u8; 32];
        x[1..].copy_from_slice(&[0x5Eu8; 31]);
        x // x[0] == 0x00
    };
    let a_priv = [0x11u8; 32];
    let b_priv = [0x22u8; 32];

    let mut out = Vec::new();
    for group in [
        SrpGroup::Rfc5054_2048,
        SrpGroup::Rfc5054_3072,
        SrpGroup::Rfc5054_4096,
    ] {
        out.push(deterministic_exchange(
            group, "alice", &salt, &x, &a_priv, &b_priv,
        ));
        // Non-ASCII identity, same group, to pin UTF-8 encoding of `I`.
        out.push(deterministic_exchange(
            group, "renée", &salt, &x, &a_priv, &b_priv,
        ));
    }
    out
}

fn render(vectors: &[ExchangeVector]) -> String {
    let doc = serde_json::json!({
        "$comment": "Generated by crates/axiam-auth/tests/srp_vectors_test.rs. \
                     Do not hand-edit. Regenerate with UPDATE_SRP_VECTORS=1 and \
                     re-sync into every SDK repository.",
        "protocol": "SRP-6a",
        "hash": "SHA-256",
        "note": "`x` is an input, not a derivation: it is the KDF output, and the \
                 KDF (argon2id or pbkdf2_sha256) is specified in CONTRACT.md §23. \
                 These vectors pin the group arithmetic and the proof \
                 construction, which are identical in every SDK.",
        "vectors": vectors,
    });
    let mut text = serde_json::to_string_pretty(&doc).expect("vectors serialize");
    text.push('\n');
    text
}

#[test]
fn srp_vectors_match_the_committed_file() {
    let generated = render(&fixtures());
    let path = vectors_path();

    if std::env::var("UPDATE_SRP_VECTORS").is_ok() {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).expect("create sdks/");
        }
        std::fs::write(&path, &generated).expect("write vectors");
        return;
    }

    let committed = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "{} is missing ({e}). Generate it with \
             `UPDATE_SRP_VECTORS=1 cargo test -p axiam-auth --test srp_vectors_test`.",
            path.display()
        )
    });

    assert_eq!(
        committed.trim_end(),
        generated.trim_end(),
        "sdks/srp-test-vectors.json is stale.\n\n\
         The server's SRP implementation has changed in a way that alters the \
         wire values every SDK is tested against. Regenerate with \
         `UPDATE_SRP_VECTORS=1 cargo test -p axiam-auth --test srp_vectors_test` \
         AND re-sync the file into all eleven SDK repositories — a change here \
         without that fan-out breaks every SDK silently."
    );
}

/// The two halves of the protocol must agree, independently of the vectors.
///
/// `deterministic_exchange` asserts this internally; this test states it as a
/// property so that a future refactor which removes that assertion still fails
/// here rather than silently publishing an inconsistent vector.
#[test]
fn every_vector_is_internally_consistent() {
    for v in fixtures() {
        assert_eq!(v.client_proof.len(), 64, "M1 must be a SHA-256 digest");
        assert_eq!(v.server_proof.len(), 64, "M2 must be a SHA-256 digest");
        assert_eq!(v.session_key.len(), 64, "K must be a SHA-256 digest");
        assert_ne!(v.client_proof, v.server_proof, "M1 and M2 must differ");

        // Everything the protocol PADs must be exactly the group width — the
        // property an implementation that skips PAD() violates.
        let group: SrpGroup = v.group.parse().unwrap();
        let width = group.byte_len() * 2;
        for (label, value) in [
            ("verifier", &v.verifier),
            ("A", &v.a_pub),
            ("B", &v.b_pub),
            ("S", &v.session_secret),
        ] {
            assert_eq!(
                value.len(),
                width,
                "{label} is not padded to the {} group width",
                v.group
            );
        }
    }
}

/// The fixtures must actually exercise the leading-zero case they exist for.
#[test]
fn the_fixtures_cover_the_leading_zero_padding_case() {
    let vectors = fixtures();
    assert!(
        vectors.iter().any(|v| v.salt.starts_with("00")),
        "no fixture has a leading-zero salt, so nothing here would catch a \
         missing PAD()"
    );
    assert!(
        vectors.iter().any(|v| v.identity == "renée"),
        "no fixture has a non-ASCII identity, so nothing here would catch an \
         SDK hashing a platform-default encoding instead of UTF-8"
    );
}
