# AXIAM development commands

# Start development dependencies (SurrealDB, RabbitMQ)
#
# A6: AMQP is TLS-only, so the dev broker needs a certificate before it can
# serve anyone. gen-broker-tls.sh is idempotent — it leaves existing material
# alone — so running it on every `dev-up` costs a second on the first run and
# nothing afterwards, and it will never rotate a cert out from under a broker
# that is already up.
dev-up: dev-broker-certs
    docker compose -f docker/docker-compose.dev.yml up -d
    @echo "SurrealDB: http://localhost:8000"
    @echo "RabbitMQ:  amqps://localhost:5671 (axiam/axiam, TLS 1.3)"
    @echo "RabbitMQ Management: http://localhost:15672 (axiam/axiam)"

# A6: (re)generate the private CA + broker certificate the dev AMQPS listener
# needs. `dev-up` calls this automatically; run it directly to rotate (delete
# docker/.secrets/broker-tls first).
#
# The same directory backs `prod-up`, and the generated SAN covers `rabbitmq`,
# `localhost` and `127.0.0.1` — so one set of material serves the compose
# network and any `cargo test -- --ignored` running on the host.
dev-broker-certs:
    bash scripts/gen-broker-tls.sh

# Start a development-mode Vault and seed AXIAM's secrets into it.
#
# OPTIONAL locally: `just dev-up` does not start Vault, and the default secret
# provider is `env`, so a developer who never runs this sees no change. Run it
# to exercise the path production uses.
#
# Dev-mode Vault is in-memory, unsealed, plain HTTP and has a fixed root token.
# All four are wrong for production and right for a laptop — see
# docs/deployment/vault.md for what a real deployment does instead.
vault-up:
    #!/usr/bin/env bash
    set -euo pipefail
    docker compose -f docker/docker-compose.dev.yml --profile vault up -d vault
    echo "→ Waiting for Vault to become ready"
    for _ in $(seq 1 30); do
        if curl -fsS http://127.0.0.1:8200/v1/sys/health >/dev/null 2>&1; then break; fi
        sleep 1
    done
    VAULT_ADDR=http://127.0.0.1:8200 \
    VAULT_TOKEN="${VAULT_DEV_ROOT_TOKEN_ID:-axiam-dev-root}" \
        bash scripts/vault-seed.sh
    echo ""
    echo "Vault UI/API: http://localhost:8200 (token: ${VAULT_DEV_ROOT_TOKEN_ID:-axiam-dev-root})"
    echo ""
    echo "To make the server use it, export before \`just run\`:"
    echo "  export AXIAM__AUTH__SECRET_PROVIDER=vault"
    echo "  export AXIAM__AUTH__VAULT_ADDR=http://127.0.0.1:8200"
    echo "  export AXIAM__AUTH__VAULT_TOKEN=${VAULT_DEV_ROOT_TOKEN_ID:-axiam-dev-root}"

# Seed a Vault — any Vault — with every secret AXIAM needs, minting what is
# missing and leaving what is present alone.
#
# THIS IS THE PRODUCTION RECIPE. `vault-up` and `prod-up` both call the same
# seeder underneath; this is the one to run against a Vault you already have,
# which is what a real deployment looks like. It reads its target from the
# environment and never assumes a dev-mode server:
#
#   VAULT_ADDR    required, e.g. https://vault.internal:8200
#   VAULT_TOKEN   required, a token with create/update on the KV path
#   VAULT_MOUNT   KV v2 mount point            (default: secret)
#   VAULT_PATH    path within the mount        (default: axiam)
#   VAULT_CACERT  CA bundle for the listener   (recommended over VAULT_SKIP_VERIFY)
#
# What it mints, all from a CSPRNG and only when absent:
#   - eight 256-bit keys (OPAQUE session + setup, MFA, federation, email,
#     GDPR pepper, PKI, AMQP signing), hex-encoded
#   - the auth pepper
#   - an Ed25519 JWT signing keypair, generated by openssl and never written
#     to disk
#
# IDEMPOTENT, and that is load-bearing rather than a nicety: regenerating
# `opaque_setup_key` would need a password reset for every user in every
# tenant, and regenerating the JWT key invalidates every token in flight. An
# existing value is always preserved.
#
# X.509 material is deliberately NOT in here. The broker's AMQPS certificate
# and Vault's own listener certificate are consumed as FILE PATHS by containers
# that cannot read Vault (`AXIAM__AMQP__TLS__CA_CERT_PATH`, and Vault cannot
# hold the certificate that fronts itself). `just tls-certs` generates those.
# Tenant CA certificates are a runtime concern owned by axiam-pki and issued
# through the API — putting them here would be inventing a second source of
# truth for something the database already owns.
vault-seed:
    #!/usr/bin/env bash
    set -euo pipefail
    : "${VAULT_ADDR:?VAULT_ADDR is required, e.g. https://vault.internal:8200}"
    : "${VAULT_TOKEN:?VAULT_TOKEN is required (needs create/update on the KV path)}"
    echo "→ Seeding ${VAULT_MOUNT:-secret}/${VAULT_PATH:-axiam} at ${VAULT_ADDR}"
    bash scripts/vault-seed.sh
    echo ""
    echo "Point the server at it:"
    echo "  export AXIAM__AUTH__SECRET_PROVIDER=vault"
    echo "  export AXIAM__AUTH__VAULT_ADDR=${VAULT_ADDR}"
    echo "  export AXIAM__AUTH__VAULT_TOKEN=<a read-only token, not the seeding one>"

# Generate the X.509 material the containers mount, for every stack.
#
# Separate from `vault-seed` because these are files rather than Vault entries,
# and for a reason that is not arbitrary: the broker and the Vault listener are
# the two things that need certificates *before* anything can read Vault. Both
# scripts are idempotent and leave bring-your-own material alone.
tls-certs:
    bash scripts/gen-broker-tls.sh
    bash scripts/gen-vault-tls.sh

# Stop the development Vault (its data is in-memory and goes with it).
vault-down:
    docker compose -f docker/docker-compose.dev.yml --profile vault down vault

# Print which secrets the dev Vault holds, without printing their values,
# and what the token presenting them is allowed to do (H-4 / T-180).
#
# The dev Vault runs on a fixed ROOT token on purpose, so the scope block below
# will always report OVER-SCOPED here. That is the point: the same recipe, run
# against a real Vault with the read-only policy from docs/deployment/vault.md
# §5.4, prints `ok` — so the line is a check rather than decoration. Nothing is
# `--strict` here; a production check that should FAIL on an over-scoped token
# adds it (see §5.4).
vault-status:
    #!/usr/bin/env bash
    set -euo pipefail
    VAULT_ADDR_LOCAL="${VAULT_ADDR:-http://127.0.0.1:8200}"
    TOKEN="${VAULT_TOKEN:-${VAULT_DEV_ROOT_TOKEN_ID:-axiam-dev-root}}"
    CAPS="$(mktemp)"
    trap 'rm -f "$CAPS"' EXIT
    # Capabilities are not secrets, so this response is safe to keep on disk
    # for the length of one command. A Vault that will not answer it (an older
    # version, a policy without `sys/capabilities-self`) leaves the file empty
    # and the reporter says "not checked" rather than failing.
    curl -fsS --header "X-Vault-Token: ${TOKEN}" \
        --request POST \
        --data '{"paths":["secret/data/axiam","secret/metadata/axiam"]}' \
        "${VAULT_ADDR_LOCAL}/v1/sys/capabilities-self" > "$CAPS" || true
    curl -fsS --header "X-Vault-Token: ${TOKEN}" \
        "${VAULT_ADDR_LOCAL}/v1/secret/data/axiam" \
        | python3 scripts/vault-status.py --capabilities "$CAPS"

# Stop development dependencies
dev-down:
    docker compose -f docker/docker-compose.dev.yml down

# Stop and remove all data volumes
dev-clean:
    docker compose -f docker/docker-compose.dev.yml down -v

# Build all crates
build:
    cargo build --workspace

# Run all tests
test:
    cargo test --workspace

# Run a specific test
test-one NAME:
    cargo test --workspace {{NAME}}

# Run clippy linter
lint:
    cargo clippy --workspace --all-targets -- -D warnings

# Check formatting
fmt-check:
    cargo fmt --all -- --check

# Apply formatting
fmt:
    cargo fmt --all

# Run all checks (fmt + clippy + test)
check: fmt-check lint test

# Measure line coverage for the server workspace (mirrors coverage.yml).
# Requires: `cargo install cargo-llvm-cov` + `rustup component add llvm-tools-preview`.
# Integration tests that need a live SurrealDB/RabbitMQ expect `just dev-up`.
# Writes an HTML report under target/llvm-cov/html and prints a summary.
coverage:
    cargo llvm-cov --workspace --no-report --no-fail-fast
    cargo llvm-cov --no-report -p axiam-api-grpc --features client --test grpc_authz_test
    cargo llvm-cov report --html
    cargo llvm-cov report --summary-only

# Same as `coverage` but fails if total line coverage drops below THRESHOLD.
# Used to guard against regressions locally before pushing.
coverage-gate THRESHOLD="80":
    cargo llvm-cov --workspace --no-report --no-fail-fast
    cargo llvm-cov --no-report -p axiam-api-grpc --features client --test grpc_authz_test
    cargo llvm-cov report --fail-under-lines {{THRESHOLD}}

# Run the AXIAM server (saml-on; needs a compatible system libxml2 — CI/Docker)
run:
    RUST_LOG=axiam=debug cargo run --bin axiam-server

# Run axiam-server without saml (local dev on Arch/incompatible libxml2; OIDC still works).
# Self-contained: generates a local-only Ed25519 JWT keypair on first run (shared
# with prod-up, gitignored under docker/.secrets/), points AMQP at the dev-up
# RabbitMQ creds, and disables Secure cookies so auth works over http://localhost.
# Requires `just dev-up` (SurrealDB + RabbitMQ) running first.
run-local:
    #!/usr/bin/env bash
    set -euo pipefail
    SECRETS_DIR="docker/.secrets"
    PRIV="$SECRETS_DIR/jwt_ed25519.pem"
    PUB="$SECRETS_DIR/jwt_ed25519.pub.pem"
    if [[ ! -f "$PRIV" || ! -f "$PUB" ]]; then
        echo "→ Generating Ed25519 JWT keypair in $SECRETS_DIR/ (first-run only)"
        mkdir -p "$SECRETS_DIR"
        openssl genpkey -algorithm ed25519 -out "$PRIV"
        openssl pkey -in "$PRIV" -pubout -out "$PUB"
        chmod 600 "$PRIV"
    fi
    export AXIAM__AUTH__JWT_PRIVATE_KEY_PEM="$(cat "$PRIV")"
    export AXIAM__AUTH__JWT_PUBLIC_KEY_PEM="$(cat "$PUB")"
    # 32-byte (64-hex-char) AES-256-GCM keys for at-rest secret encryption.
    # Generated once and persisted (gitignored) so secrets survive restarts.
    # Without the MFA key, POST /api/v1/auth/mfa/enroll 500s ("MFA encryption
    # key not configured"); without the federation key, OIDC client secrets
    # cannot be decrypted at use.
    gen_hex_key() {
        local f="$SECRETS_DIR/$1"
        if [[ ! -f "$f" ]]; then
            openssl rand -hex 32 > "$f"
            chmod 600 "$f"
        fi
        cat "$f"
    }
    export AXIAM__AUTH__MFA_ENCRYPTION_KEY="$(gen_hex_key mfa_enc.hex)"
    export AXIAM__AUTH__FEDERATION_ENCRYPTION_KEY="$(gen_hex_key federation_enc.hex)"
    export AXIAM__PKI__ENCRYPTION_KEY="$(gen_hex_key pki_enc.hex)"
    # Enables the mail consumer + GDPR Art.15 export sweep (both skipped without it).
    export AXIAM__EMAIL_ENCRYPTION_KEY="$(gen_hex_key email_enc.hex)"
    # D-18: cookies must work over plain http://localhost in local dev. NEVER false in prod.
    export AXIAM__AUTH__COOKIE_SECURE="false"
    # dev-up RabbitMQ runs as axiam/axiam with the default guest user disabled,
    # and listens on 5671 (AMQPS) only — A6: AMQP is TLS-only in every build
    # profile, so there is no plaintext listener for this to fall back to. The
    # CA is the one `just dev-broker-certs` minted, and its SAN covers
    # `localhost`, which is what makes this work from the host.
    export AXIAM__AMQP__URL="${AXIAM__AMQP__URL:-amqps://axiam:axiam@localhost:5671}"
    export AXIAM__AMQP__TLS__CA_CERT_PATH="${AXIAM__AMQP__TLS__CA_CERT_PATH:-$SECRETS_DIR/broker-tls/ca.pem}"
    RUST_LOG="${RUST_LOG:-axiam=debug}" cargo run --bin axiam-server --no-default-features

# Build the OPAQUE WebAssembly client the admin UI signs in with.
#
# Optional for everything except OPAQUE: without it `frontend/vite.config.ts`
# falls back to a stub, the UI builds and tests normally, and
# `opaqueAvailable()` reports false — so password login still works and a
# checkout with no Rust toolchain is not blocked. Run it when you need to
# exercise an OPAQUE sign-in locally, or after changing crates/axiam-opaque.
#
# Released images never rely on this recipe: docker/Dockerfile.frontend builds
# the same artifact from the same source in its own stage.
build-opaque-wasm:
    #!/usr/bin/env bash
    set -euo pipefail
    command -v wasm-pack >/dev/null 2>&1 || {
      echo "wasm-pack not found — install it with:" >&2
      echo "  cargo install wasm-pack --version 0.13.1" >&2
      exit 1
    }
    # `--out-name axiam_opaque` matches what release-opaque.yml publishes to
    # npm, so the entry filename vite.config.ts probes for is the same whether
    # the package came from here or from the registry.
    wasm-pack build crates/axiam-opaque-wasm \
      --target web --release \
      --out-dir "$PWD/frontend/vendor/opaque-wasm" \
      --out-name axiam_opaque
    echo "built -> frontend/vendor/opaque-wasm (gitignored)"

# Start frontend dev server
frontend-dev:
    cd frontend && npm run dev

# Build frontend for production
frontend-build:
    cd frontend && npm run build

# Run frontend E2E tests
frontend-test:
    cd frontend && npx playwright test

# Start full production-like stack (pull official images + run all services).
#
# axiam-server and axiam-frontend are pulled from the project's public GitHub
# registry (ghcr.io/ilpanich/axiam/*) instead of being built locally. Override
# the release with AXIAM_IMAGE_TAG, e.g. `AXIAM_IMAGE_TAG=1.0.0-alpha32 just prod-up`.
# Generates a local-only Ed25519 JWT signing keypair on first run under
# docker/.secrets/ (gitignored) and exports it into the shell so the compose
# file can forward it to axiam-server. Host port 80 is left free so a local
# HTTPS reverse proxy (e.g. Caddy) can sit in front of the frontend on :8081.
prod-up:
    #!/usr/bin/env bash
    set -euo pipefail
    SECRETS_DIR="docker/.secrets"
    mkdir -p "$SECRETS_DIR"
    PRIV="$SECRETS_DIR/jwt_ed25519.pem"
    PUB="$SECRETS_DIR/jwt_ed25519.pub.pem"

    # SEC-023: the compose file carries no literal credentials, so the stack's
    # SurrealDB and RabbitMQ passwords are minted here on first run and kept in
    # a gitignored file. PERSISTED rather than regenerated per run because both
    # services only honour these on the first boot of an empty data volume —
    # a fresh password on run two locks the server out of its own datastore.
    CREDS="$SECRETS_DIR/stack-credentials.env"
    if [[ ! -f "$CREDS" ]]; then
        # ...which means minting is only ever correct against EMPTY volumes. A
        # surrealkv datastore stores its root user as a `DEFINE USER` record on
        # first boot and ignores `--user/--pass` on every start after that, so
        # minting a fresh password on top of a surviving volume hands
        # axiam-server a credential its own database is guaranteed to reject —
        # an `InvalidAuth` panic loop that reads like a client bug and is not
        # one. Refuse instead. (RabbitMQ was observed to re-apply a changed
        # RABBITMQ_DEFAULT_PASS to an existing volume, so it may well survive
        # a re-mint; it is checked anyway, because a lost credentials file is
        # reason enough to stop and let a human decide.)
        PROJECT="${COMPOSE_PROJECT_NAME:-docker}"
        STALE=""
        for v in "${PROJECT}_surrealdb-data" "${PROJECT}_rabbitmq-data"; do
            if docker volume inspect "$v" >/dev/null 2>&1; then STALE="$STALE $v"; fi
        done
        if [[ -n "$STALE" ]]; then
            echo "✗ $CREDS is missing, but these data volumes already exist:" >&2
            for v in $STALE; do echo "      $v" >&2; done
            echo "" >&2
            echo "  Their credentials were fixed when the volumes were first created and" >&2
            echo "  cannot be changed by minting new ones — the server would be locked out" >&2
            echo "  of its own datastore. Restore the credentials file from backup, or" >&2
            echo "  discard the data and start clean:" >&2
            echo "" >&2
            echo "      just prod-clean && just prod-up" >&2
            exit 1
        fi
        echo "→ Minting SurrealDB + RabbitMQ credentials in $CREDS (first-run only)"
        ( umask 077 && cat > "$CREDS" <<EOF
    # Generated by \`just prod-up\` — gitignored, do not commit.
    # Delete this file AND the surrealdb-data / rabbitmq-data volumes to rotate
    # (\`just prod-clean\`); deleting it alone strands the running volumes.
    export AXIAM__DB__USERNAME="axiam"
    export AXIAM__DB__PASSWORD="$(openssl rand -hex 24)"
    export RABBITMQ_DEFAULT_USER="axiam"
    export RABBITMQ_DEFAULT_PASS="$(openssl rand -hex 24)"
    EOF
        )
    fi
    # shellcheck source=/dev/null
    source "$CREDS"

    # No moving `latest` tag exists in the registry (release.yml applies it to
    # stable releases only, and every AXIAM release so far is a pre-release), so
    # the tag is pinned to the workspace version — one source of truth, bumped
    # by the release-prep commit like everything else.
    export AXIAM_IMAGE_TAG="${AXIAM_IMAGE_TAG:-$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml | head -1)}"

    # Chicken-and-egg: compose interpolates the WHOLE file even for `up -d vault`,
    # so the server's `${AXIAM__AUTH__VAULT_TOKEN:?...}` must resolve before Vault
    # exists to issue one. A placeholder gets the bring-up past interpolation; the
    # real root token replaces it below, before axiam-server is ever started.
    export AXIAM__AUTH__VAULT_TOKEN="${AXIAM__AUTH__VAULT_TOKEN:-pending-vault-init}"
    # A6: the prod stack speaks amqps:// to the broker, so it needs a broker
    # certificate. Idempotent — existing material is left alone, and bring-your-
    # own certs dropped into docker/.secrets/broker-tls/ are picked up unchanged.
    bash scripts/gen-broker-tls.sh
    if [[ ! -f "$PRIV" || ! -f "$PUB" ]]; then
        echo "→ Generating Ed25519 JWT keypair in $SECRETS_DIR/ (first-run only)"
        mkdir -p "$SECRETS_DIR"
        openssl genpkey -algorithm ed25519 -out "$PRIV"
        openssl pkey -in "$PRIV" -pubout -out "$PUB"
        chmod 600 "$PRIV"
    fi
    export AXIAM__AUTH__JWT_PRIVATE_KEY_PEM="$(cat "$PRIV")"
    export AXIAM__AUTH__JWT_PUBLIC_KEY_PEM="$(cat "$PUB")"

    # Vault is mandatory in this stack, so it comes up first and gets
    # initialised, unsealed and seeded before the server is allowed to start.
    bash scripts/gen-vault-tls.sh
    docker compose -f docker/docker-compose.prod.yml up -d vault
    VAULT_STATE="$SECRETS_DIR/vault-init.json"
    export VAULT_ADDR="https://127.0.0.1:8200"
    export VAULT_CACERT="$PWD/$SECRETS_DIR/vault-tls/ca.pem"

    echo "→ Waiting for Vault to respond"
    VAULT_UP=0
    for _ in $(seq 1 60); do
        # 501 (uninitialised) and 503 (sealed) both mean "listening", which is
        # what we are waiting for here.
        if curl -sS --cacert "$VAULT_CACERT" -o /dev/null "$VAULT_ADDR/v1/sys/health" 2>/dev/null; then
            VAULT_UP=1
            break
        fi
        sleep 1
    done
    if [[ "$VAULT_UP" -ne 1 ]]; then
        echo "✗ Vault never came up on $VAULT_ADDR. Check: docker logs axiam-vault" >&2
        exit 1
    fi

    # Ask Vault whether it is initialised rather than inferring it from the
    # presence of $VAULT_STATE: a run that died between the redirect and a
    # successful response leaves a zero-byte file behind, and `[[ -f ]]` then
    # skips initialisation forever on a Vault that was never initialised.
    if ! curl -sS --cacert "$VAULT_CACERT" "$VAULT_ADDR/v1/sys/init" | grep -q '"initialized":true'; then
        echo "→ Initialising Vault (first run)"
        # One unseal key for a local stack. A real deployment uses Shamir with
        # a threshold across several holders, or auto-unseal — see
        # docs/deployment/vault.md.
        #
        # Written to a temp file and validated BEFORE it replaces $VAULT_STATE:
        # this response is the only copy of the unseal key that will ever exist,
        # so a truncated write is unrecoverable.
        VAULT_STATE_TMP="$(mktemp)"
        curl -sS --cacert "$VAULT_CACERT" --request POST \
            --data '{"secret_shares":1,"secret_threshold":1}' \
            "$VAULT_ADDR/v1/sys/init" > "$VAULT_STATE_TMP"
        if ! python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); assert d["keys"][0] and d["root_token"]' "$VAULT_STATE_TMP" 2>/dev/null; then
            echo "✗ Vault init returned no usable keys:" >&2
            head -c 500 "$VAULT_STATE_TMP" >&2; echo >&2
            rm -f "$VAULT_STATE_TMP"
            exit 1
        fi
        mv "$VAULT_STATE_TMP" "$VAULT_STATE"
        chmod 600 "$VAULT_STATE"
        echo "  ⚠ Unseal key and root token written to $VAULT_STATE."
        echo "    That file is the whole of your Vault. Back it up, and do NOT"
        echo "    do this in production — see docs/deployment/vault.md."
    elif [[ ! -s "$VAULT_STATE" ]]; then
        echo "✗ Vault reports it is initialised but $VAULT_STATE is missing or empty." >&2
        echo "  The unseal key and root token existed nowhere else. Restore that file" >&2
        echo "  from backup, or discard the Vault entirely with 'just prod-clean'." >&2
        exit 1
    fi

    UNSEAL_KEY="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["keys"][0])' "$VAULT_STATE")"
    export VAULT_TOKEN="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["root_token"])' "$VAULT_STATE")"

    if curl -sS --cacert "$VAULT_CACERT" "$VAULT_ADDR/v1/sys/seal-status" \
        | grep -q '"sealed":true'; then
        echo "→ Unsealing Vault"
        curl -sS --cacert "$VAULT_CACERT" --request POST \
            --data "{\"key\":\"$UNSEAL_KEY\"}" \
            "$VAULT_ADDR/v1/sys/unseal" > /dev/null
    fi

    JWT_PRIVATE_KEY_PEM="$AXIAM__AUTH__JWT_PRIVATE_KEY_PEM" \
    JWT_PUBLIC_KEY_PEM="$AXIAM__AUTH__JWT_PUBLIC_KEY_PEM" \
        bash scripts/vault-seed.sh

    export AXIAM__AUTH__VAULT_TOKEN="$VAULT_TOKEN"
    # axiam-server and axiam-frontend come from the official images published
    # to ghcr.io/ilpanich/axiam/* by the release workflow, so there is no local
    # build here. `--pull always` is deliberately absent: the tag is a pinned,
    # immutable release, so re-pulling it every run buys nothing.
    #
    # To build from the working tree instead, uncomment the `build:` blocks in
    # docker/docker-compose.prod.yml and swap the two lines below.
    # docker compose -f docker/docker-compose.prod.yml up --build -d
    docker compose -f docker/docker-compose.prod.yml up -d
    echo "AXIAM Frontend: http://localhost:8081 (front it with Caddy for HTTPS)"
    echo "AXIAM REST API: http://localhost:8090"
    echo "AXIAM gRPC:     localhost:50051"
    echo ""
    echo "For HTTPS cookie tests, in another terminal run:"
    echo "  sudo caddy reverse-proxy --from https://localhost --to :8081"

# A6: (re)generate the private CA + broker certificate for the AMQPS listener.
# `prod-up` calls this automatically; run it directly to rotate (delete
# docker/.secrets/broker-tls first) or to inspect what would be generated.
prod-broker-certs:
    bash scripts/gen-broker-tls.sh

# Run `docker compose` against the prod file with an environment it can
# interpolate. Compose expands EVERY `${VAR:?...}` guard in the file whatever
# the subcommand is — so `down`, which starts nothing and reads none of these
# values, still fails on all eight of them unless they resolve. Real
# credentials are sourced when the file is there (so the environment matches
# what `prod-up` built); anything still unset falls back to a placeholder,
# which keeps teardown working from a clean shell without minting, reading or
# regenerating key material.
_prod-compose *ARGS:
    #!/usr/bin/env bash
    set -euo pipefail
    CREDS="docker/.secrets/stack-credentials.env"
    if [[ -f "$CREDS" ]]; then
        # shellcheck source=/dev/null
        source "$CREDS"
    fi
    export AXIAM__DB__USERNAME="${AXIAM__DB__USERNAME:-unused-for-this-subcommand}"
    export AXIAM__DB__PASSWORD="${AXIAM__DB__PASSWORD:-unused-for-this-subcommand}"
    export RABBITMQ_DEFAULT_USER="${RABBITMQ_DEFAULT_USER:-unused-for-this-subcommand}"
    export RABBITMQ_DEFAULT_PASS="${RABBITMQ_DEFAULT_PASS:-unused-for-this-subcommand}"
    export AXIAM__AUTH__VAULT_TOKEN="${AXIAM__AUTH__VAULT_TOKEN:-unused-for-this-subcommand}"
    export AXIAM__AUTH__JWT_PRIVATE_KEY_PEM="${AXIAM__AUTH__JWT_PRIVATE_KEY_PEM:-unused-for-this-subcommand}"
    export AXIAM__AUTH__JWT_PUBLIC_KEY_PEM="${AXIAM__AUTH__JWT_PUBLIC_KEY_PEM:-unused-for-this-subcommand}"
    # Same derivation as `prod-up`, so teardown targets the tag that was brought up.
    export AXIAM_IMAGE_TAG="${AXIAM_IMAGE_TAG:-$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml | head -1)}"
    docker compose -f docker/docker-compose.prod.yml {{ARGS}}

# Stop production-like stack
prod-down: (_prod-compose "down")

# Stop production-like stack and remove volumes.
#
# The state files under docker/.secrets/ go with them. Each one describes a
# volume that no longer exists — the datastore credentials minted for
# surrealdb-data, and the unseal key + root token for vault-data — so keeping
# them past the volume they belong to is exactly what strands the next
# `prod-up` (see the guard there). `prod-up`'s "discard the Vault entirely
# with 'just prod-clean'" is only true because of the second `rm` here.
#
# Deliberately kept: the JWT keypair, broker TLS and Vault TLS material, which
# are inputs to the stack rather than state produced by it, and are regenerated
# only when absent.
prod-clean: (_prod-compose "down" "-v")
    rm -f docker/.secrets/stack-credentials.env docker/.secrets/vault-init.json

# Requires: `just dev-up` (SurrealDB on :8000) + `just run-local` (AXIAM on :8090).
# Defaults: E2E_ORG_SLUG=test-org, E2E_TENANT_SLUG=default, E2E_ADMIN_EMAIL=admin@axiam.dev
# Override E2E_*, AXIAM_URL, SURREAL_URL, AXIAM__DB__DATABASE env vars as needed.
# Seed org+tenant+admin against the run-local server; unblocks 12-HUMAN-UAT smoke.
bootstrap-local:
    #!/usr/bin/env bash
    set -euo pipefail
    export AXIAM_URL="${AXIAM_URL:-http://localhost:8090}"
    export SURREAL_URL="${SURREAL_URL:-http://localhost:8000}"
    # Must match the database run-local targets (DbConfig default: main).
    export AXIAM__DB__DATABASE="${AXIAM__DB__DATABASE:-main}"
    bash scripts/e2e-bootstrap.sh

# ---------------------------------------------------------------------------
# FAPI 2.0 conformance (X5.2) — see claude_dev/fapi-conformance-runbook.md
# ---------------------------------------------------------------------------
#
# The OpenID Foundation conformance suite, pinned, driven against a running
# AXIAM. The suite is NOT a unit test: it needs a real deployment with an mTLS
# listener, two registered FAPI clients, and — for several modules — a human
# with a browser. Read the runbook before the first run; it is short and it
# will save an evening.
#
#   just conformance-certs      # throwaway client certs for both auth variants
#   just conformance-up         # start the pinned suite (~60s to ready)
#   just conformance-register   # create the two fapi2 clients, fill suite.env
#   just conformance-run        # drive both test plans, collect results
#   just conformance-report     # render docs/conformance/*.md — failures first
#   just conformance-down

# Throwaway client certificates for the two client-auth variants.
conformance-certs:
    bash conformance/scripts/gen-certs.sh

# Start the pinned OIDF conformance suite.
conformance-up:
    #!/usr/bin/env bash
    set -euo pipefail
    set -a; . conformance/suite.env; set +a
    docker compose -f conformance/docker-compose.yml up -d
    echo "[conformance] waiting for the suite to become ready (up to 3 min)…"
    for _ in $(seq 1 90); do
      if curl -sSk --max-time 5 "${SUITE_BASE_URL}/api/runner/available" >/dev/null 2>&1; then
        echo "[conformance] ready at ${SUITE_BASE_URL}"
        exit 0
      fi
      sleep 2
    done
    echo "[conformance] the suite did not become ready; check 'docker compose -f conformance/docker-compose.yml logs'" >&2
    exit 1

# Register the fapi2 clients against a running AXIAM and update suite.env.
conformance-register:
    bash conformance/scripts/register-clients.sh

# Drive all three FAPI 2.0 plans and collect their results.
#
# Exits non-zero if any plan has a module that did not pass — deliberately,
# so this can be wired into a manually-triggered CI workflow without silently
# going green on a red run. Every plan always runs: stopping at the first red
# one would hide the later variants' failures behind the first's.
#
# The third variant (private_key_jwt + DPoP) is what makes this cover both of
# FAPI's client-authentication FAMILIES rather than both of RFC 8705's mTLS
# methods. It needs no mTLS listener, which also makes it a diagnostic: if the
# first two fail at client authentication and the third passes, the problem is
# the listener's client-CA bundle rather than AXIAM.
conformance-run:
    #!/usr/bin/env bash
    set -uo pipefail
    PLAN_NAME="${CONFORMANCE_PLAN_NAME:-fapi2-security-profile-final-test-plan}"
    rc=0
    for variant in mtls self-signed private-key-jwt; do
      cfg="conformance/plans/fapi2-security-profile-final-${variant}.json"
      echo
      echo "=== ${variant} client authentication ==="
      bash conformance/scripts/render-plan.sh "$cfg" || { rc=1; continue; }
      bash conformance/scripts/run-plan.sh \
        "conformance/.run/$(basename "$cfg")" "$PLAN_NAME" || rc=1
    done
    exit $rc

# Render the collected results into docs/conformance/, failures first.
conformance-report:
    python3 conformance/scripts/report.py --results conformance/.run/results \
      --out docs/conformance --date "${CONFORMANCE_DATE:-}"

conformance-down:
    #!/usr/bin/env bash
    set -euo pipefail
    set -a; . conformance/suite.env; set +a
    docker compose -f conformance/docker-compose.yml down -v
