//! Integration tests for CA certificate management endpoints.

use actix_web::{App, test, web};
use axiam_api_rest::RateLimitConfig;
use axiam_api_rest::authz::{AllowAllAuthzChecker, AuthzChecker};
use axiam_api_rest::register_api_v1_routes;
use axiam_api_rest::state::AppState;
use axiam_auth::config::AuthConfig;
use axiam_auth::token::issue_access_token;
use axiam_core::models::organization::CreateOrganization;
use axiam_core::models::tenant::{CreateTenant, TenantKind};
use axiam_core::models::user::CreateUser;
use axiam_core::repository::{OrganizationRepository, TenantRepository, UserRepository};
use axiam_db::{
    SurrealCaCertificateRepository, SurrealOrganizationRepository, SurrealTenantRepository,
    SurrealUserRepository,
};
use axiam_pki::{CaService, PkiConfig};
use std::sync::Arc;
use surrealdb::Surreal;
use surrealdb::engine::local::Mem;
use uuid::Uuid;

/// The CA key custodians these tests run against.
///
/// The same all-zero key `test_pki_config` uses, so a CA generated by one
/// service and signed with by another opens. Built through
/// `custodians_from_env` rather than by hand: it is the function the
/// composition root calls, and a test that assembled custody differently would
/// agree with itself and not with production.
#[allow(dead_code)]
fn test_ca_custodians() -> std::sync::Arc<axiam_pki::CaKeyCustodians> {
    std::sync::Arc::new(
        axiam_pki::custodians_from_env(Some([0u8; 32])) // gitleaks:allow
            .expect("test CA key custodians"),
    )
}

type TestDb = surrealdb::engine::local::Db;

/// Test-only placeholder password — not a real credential.
const TEST_PASSWORD: &str = "test-only-placeholder-not-a-real-password"; // gitleaks:allow

/// Arbitrary CSRF token for the double-submit check (SEC-046). These
/// Bearer-token tests have no login/`axiam_csrf` cookie, so we send a matching
/// `axiam_csrf` cookie + `X-CSRF-Token` header; the middleware only checks they
/// are equal (no session lookup). Safe (GET) requests ignore it.
const CSRF_TOKEN: &str = "test-csrf-token";

fn test_keypair() -> (String, String) {
    // Test-only non-secret Ed25519 key pair used solely for JWT signing in unit tests.
    let private_key = [
        "-----BEGIN PRIVATE KEY-----\n", // nosemgrep: generic.secrets.security.detected-private-key
        "MC4CAQAwBQYDK2VwBCIEINvQFIZqeI5OX7TDEFKcYhLxO5R75FOv/nC4+o+HHPfM\n",
        "-----END PRIVATE KEY-----",
    ]
    .concat();
    let public_key = [
        "-----BEGIN PUBLIC KEY-----\n",
        "MCowBQYDK2VwAyEAcweT2rPwpUxadO56wIhW1XBoMF63aWOE2UMAVsRudhs=\n",
        "-----END PUBLIC KEY-----",
    ]
    .concat();
    (private_key, public_key)
}

fn test_auth_config() -> AuthConfig {
    let (priv_pem, pub_pem) = test_keypair();
    AuthConfig {
        jwt_private_key_pem: priv_pem,
        jwt_public_key_pem: pub_pem,
        access_token_lifetime_secs: 900,
        jwt_issuer: "axiam-test".into(),
        ..AuthConfig::default()
    }
}

/// Test-only PKI encryption key (32 zero bytes) — not a real key.
fn test_pki_config() -> PkiConfig {
    PkiConfig {
        encryption_key: Some([0u8; 32]), // gitleaks:allow
        ..Default::default()
    }
}

async fn setup_db() -> (Surreal<TestDb>, Uuid, Uuid) {
    let db = Surreal::new::<Mem>(()).await.unwrap();
    db.use_ns("test").use_db("test").await.unwrap();
    axiam_db::run_migrations(&db).await.unwrap();

    let org_repo = SurrealOrganizationRepository::new(db.clone());
    let org = org_repo
        .create(CreateOrganization {
            name: "Test Org".into(),
            slug: "test-org".into(),
            metadata: None,
        })
        .await
        .unwrap();

    let tenant_repo = SurrealTenantRepository::new(db.clone());
    let tenant = tenant_repo
        .create(CreateTenant {
            organization_id: org.id,
            kind: TenantKind::Standard,
            name: "Test Tenant".into(),
            slug: "test-tenant".into(),
            metadata: None,
        })
        .await
        .unwrap();

    (db, org.id, tenant.id)
}

async fn create_admin_user(db: &Surreal<TestDb>, tenant_id: Uuid) -> Uuid {
    let user_repo = SurrealUserRepository::new(db.clone());
    let user = user_repo
        .create(CreateUser {
            tenant_id,
            username: "admin".into(),
            email: "admin@example.com".into(),
            password: TEST_PASSWORD.into(),
            metadata: None,
        })
        .await
        .unwrap();
    user.id
}

fn mint_token(auth: &AuthConfig, user_id: Uuid, tenant_id: Uuid, org_id: Uuid) -> String {
    issue_access_token(
        user_id,
        tenant_id,
        org_id,
        &[],
        auth,
        uuid::Uuid::new_v4().to_string(),
        axiam_auth::token::AUD_USER,
    )
    .unwrap()
}

macro_rules! test_app {
    ($db:expr, $auth:expr) => {
        test::init_service(
            App::new()
                .app_data(web::Data::new($auth.clone()))
                .app_data(web::Data::new({
                    let mut state = AppState::for_test($db.clone(), $auth.clone());
                    state.pki.ca_service = CaService::new(
                        SurrealCaCertificateRepository::new($db.clone()),
                        test_pki_config(),
                        std::sync::Arc::new(tokio::sync::Semaphore::new(4)),
                        test_ca_custodians(),
                    );
                    state
                }))
                .app_data(web::Data::new(
                    Arc::new(AllowAllAuthzChecker) as Arc<dyn AuthzChecker>
                ))
                .configure(|cfg| {
                    register_api_v1_routes::<TestDb>(cfg, &RateLimitConfig::default())
                }),
        )
        .await
    };
}

#[actix_rt::test]
async fn generate_ca_certificate_returns_201_with_private_key() {
    let (db, org_id, tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let user_id = create_admin_user(&db, tenant_id).await;
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let app = test_app!(db, auth);

    let req = test::TestRequest::post()
        .uri(&format!("/api/v1/organizations/{org_id}/ca-certificates"))
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .insert_header(("Content-Type", "application/json"))
        .set_json(serde_json::json!({
            "subject": "Test CA",
            "key_algorithm": "Ed25519",
            "validity_days": 365
        }))
        .to_request();

    let resp = test::call_service(&app, req).await;
    let status = resp.status().as_u16();
    let body: serde_json::Value = test::read_body_json(resp).await;
    assert_eq!(status, 201, "body: {body}");
    // GeneratedCaCertificate uses #[serde(flatten)] — all fields are at the top level.
    assert!(
        body["private_key_pem"]
            .as_str()
            .unwrap()
            .contains("PRIVATE KEY")
    );
    assert!(
        body["public_cert_pem"]
            .as_str()
            .unwrap()
            .contains("CERTIFICATE")
    );
    assert!(!body["fingerprint"].as_str().unwrap().is_empty());
    assert_eq!(body["status"], "Active");
    assert_eq!(body["key_algorithm"], "Ed25519");
}

#[actix_rt::test]
async fn list_ca_certificates_returns_paginated_results() {
    let (db, org_id, tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let user_id = create_admin_user(&db, tenant_id).await;
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let app = test_app!(db, auth);

    // Generate two CA certificates.
    for subject in ["CA One", "CA Two"] {
        let req = test::TestRequest::post()
            .uri(&format!("/api/v1/organizations/{org_id}/ca-certificates"))
            .insert_header(("Authorization", format!("Bearer {token}")))
            .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
            .insert_header(("X-CSRF-Token", CSRF_TOKEN))
            .insert_header(("Content-Type", "application/json"))
            .set_json(serde_json::json!({
                "subject": subject,
                "key_algorithm": "Ed25519",
                "validity_days": 365
            }))
            .to_request();
        let resp = test::call_service(&app, req).await;
        assert_eq!(resp.status().as_u16(), 201);
    }

    let req = test::TestRequest::get()
        .uri(&format!("/api/v1/organizations/{org_id}/ca-certificates"))
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .to_request();

    let resp = test::call_service(&app, req).await;
    assert_eq!(resp.status().as_u16(), 200);

    let body: serde_json::Value = test::read_body_json(resp).await;
    assert_eq!(body["total"], 2);
    assert_eq!(body["items"].as_array().unwrap().len(), 2);
}

#[actix_rt::test]
async fn get_ca_certificate_by_id() {
    let (db, org_id, tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let user_id = create_admin_user(&db, tenant_id).await;
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let app = test_app!(db, auth);

    // Generate a cert.
    let req = test::TestRequest::post()
        .uri(&format!("/api/v1/organizations/{org_id}/ca-certificates"))
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .insert_header(("Content-Type", "application/json"))
        .set_json(serde_json::json!({
            "subject": "My CA",
            "key_algorithm": "Ed25519",
            "validity_days": 365
        }))
        .to_request();
    let resp = test::call_service(&app, req).await;
    let created: serde_json::Value = test::read_body_json(resp).await;
    let cert_id = created["id"].as_str().unwrap();

    // Get by ID.
    let req = test::TestRequest::get()
        .uri(&format!(
            "/api/v1/organizations/{org_id}/ca-certificates/{cert_id}"
        ))
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(resp.status().as_u16(), 200);

    let body: serde_json::Value = test::read_body_json(resp).await;
    assert_eq!(body["subject"], "My CA");
    assert_eq!(body["id"], cert_id);
    // encrypted_private_key should not be in JSON (serde skip_serializing).
    assert!(body.get("encrypted_private_key").is_none());
}

#[actix_rt::test]
async fn revoke_ca_certificate() {
    let (db, org_id, tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let user_id = create_admin_user(&db, tenant_id).await;
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let app = test_app!(db, auth);

    // Generate a cert.
    let req = test::TestRequest::post()
        .uri(&format!("/api/v1/organizations/{org_id}/ca-certificates"))
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .insert_header(("Content-Type", "application/json"))
        .set_json(serde_json::json!({
            "subject": "Revocable CA",
            "key_algorithm": "Ed25519",
            "validity_days": 365
        }))
        .to_request();
    let resp = test::call_service(&app, req).await;
    let created: serde_json::Value = test::read_body_json(resp).await;
    let cert_id = created["id"].as_str().unwrap();

    // Revoke.
    let req = test::TestRequest::post()
        .uri(&format!(
            "/api/v1/organizations/{org_id}/ca-certificates/{cert_id}/revoke"
        ))
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(resp.status().as_u16(), 200);

    let body: serde_json::Value = test::read_body_json(resp).await;
    assert_eq!(body["status"], "revoked");

    // Verify it's revoked by fetching it.
    let req = test::TestRequest::get()
        .uri(&format!(
            "/api/v1/organizations/{org_id}/ca-certificates/{cert_id}"
        ))
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(resp.status().as_u16(), 200);

    let body: serde_json::Value = test::read_body_json(resp).await;
    assert_eq!(body["status"], "Revoked");
}

#[actix_rt::test]
async fn ca_certificate_endpoints_require_auth() {
    let (db, org_id, _tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let app = test_app!(db, auth);

    let endpoints = vec![
        (
            "POST",
            format!("/api/v1/organizations/{org_id}/ca-certificates"),
        ),
        (
            "GET",
            format!("/api/v1/organizations/{org_id}/ca-certificates"),
        ),
        (
            "GET",
            format!(
                "/api/v1/organizations/{org_id}/ca-certificates/{}",
                Uuid::new_v4()
            ),
        ),
        (
            "POST",
            format!(
                "/api/v1/organizations/{org_id}/ca-certificates/{}/revoke",
                Uuid::new_v4()
            ),
        ),
    ];

    for (method, uri) in endpoints {
        let req = match method {
            "POST" => test::TestRequest::post()
                .uri(&uri)
                .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
                .insert_header(("X-CSRF-Token", CSRF_TOKEN))
                .to_request(),
            _ => test::TestRequest::get().uri(&uri).to_request(),
        };
        let resp = test::call_service(&app, req).await;
        assert_eq!(
            resp.status().as_u16(),
            401,
            "{method} {uri} should require auth"
        );
    }
}

// ---------------------------------------------------------------------------
// SEC-002: Cross-org 403 negative tests
// ---------------------------------------------------------------------------

/// A caller authenticated for org A gets 403 on GET /organizations/{org_B_id}/ca-certificates.
/// Regression guard: same-org caller gets 200.
#[actix_rt::test]
async fn cross_org_list_ca_certificates_returns_403() {
    let (db, org_a_id, tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let user_id = create_admin_user(&db, tenant_id).await;

    // Create org B with a distinct id.
    let org_repo = SurrealOrganizationRepository::new(db.clone());
    let org_b = org_repo
        .create(CreateOrganization {
            name: "Org B".into(),
            slug: "org-b-ca".into(),
            metadata: None,
        })
        .await
        .unwrap();
    let org_b_id = org_b.id;

    // Token claims org A.
    let token = mint_token(&auth, user_id, tenant_id, org_a_id);
    let app = test_app!(db, auth);

    // Cross-org list -> 403.
    let req = test::TestRequest::get()
        .uri(&format!("/api/v1/organizations/{org_b_id}/ca-certificates"))
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(
        resp.status().as_u16(),
        403,
        "cross-org CA list must return 403"
    );

    // Same-org regression guard -> 200.
    let req = test::TestRequest::get()
        .uri(&format!("/api/v1/organizations/{org_a_id}/ca-certificates"))
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(
        resp.status().as_u16(),
        200,
        "same-org CA list must return 200"
    );
}

/// A caller authenticated for org A gets 403 on POST /organizations/{org_B_id}/ca-certificates.
#[actix_rt::test]
async fn cross_org_generate_ca_certificate_returns_403() {
    let (db, org_a_id, tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let user_id = create_admin_user(&db, tenant_id).await;

    let org_repo = SurrealOrganizationRepository::new(db.clone());
    let org_b = org_repo
        .create(CreateOrganization {
            name: "Org B".into(),
            slug: "org-b-ca-gen".into(),
            metadata: None,
        })
        .await
        .unwrap();

    let token = mint_token(&auth, user_id, tenant_id, org_a_id);
    let app = test_app!(db, auth);

    let req = test::TestRequest::post()
        .uri(&format!(
            "/api/v1/organizations/{}/ca-certificates",
            org_b.id
        ))
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .insert_header(("Content-Type", "application/json"))
        .set_json(serde_json::json!({
            "subject": "Sneaky CA",
            "key_algorithm": "Ed25519",
            "validity_days": 365
        }))
        .to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(
        resp.status().as_u16(),
        403,
        "cross-org CA generate must return 403"
    );
}

/// A caller authenticated for org A gets 403 on GET a single CA cert under org B.
#[actix_rt::test]
async fn cross_org_get_ca_certificate_returns_403() {
    let (db, org_a_id, tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let user_id = create_admin_user(&db, tenant_id).await;

    let org_repo = SurrealOrganizationRepository::new(db.clone());
    let org_b = org_repo
        .create(CreateOrganization {
            name: "Org B".into(),
            slug: "org-b-ca-get".into(),
            metadata: None,
        })
        .await
        .unwrap();

    let token = mint_token(&auth, user_id, tenant_id, org_a_id);
    let app = test_app!(db, auth);

    let req = test::TestRequest::get()
        .uri(&format!(
            "/api/v1/organizations/{}/ca-certificates/{}",
            org_b.id,
            Uuid::new_v4()
        ))
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(
        resp.status().as_u16(),
        403,
        "cross-org CA get must return 403"
    );
}

// ---------------------------------------------------------------------------
// Importing a CA the organization already has (BYOK)
// ---------------------------------------------------------------------------
//
// The case an organization with an offline root, an HSM, or an existing
// internal PKI needs: AXIAM in the chain rather than at the top of it. Without
// it the only usable CA is one AXIAM generated, which means every
// AXIAM-issued certificate chains to a root nothing else in the estate trusts.

/// A self-signed CA, the way an external PKI hands one over.
///
/// The validity window is rcgen's default, which is far in the future — these
/// tests are about the import path, and `parse_ca_certificate`'s expiry refusal
/// has its own unit test in `axiam-pki` where the `time` crate is available to
/// build an expired one.
fn external_ca(cn: &str) -> (String, String) {
    let key_pair = rcgen::KeyPair::generate_for(&rcgen::PKCS_ED25519).unwrap();
    let mut params = rcgen::CertificateParams::new(Vec::<String>::new()).unwrap();
    params
        .distinguished_name
        .push(rcgen::DnType::CommonName, cn);
    params.is_ca = rcgen::IsCa::Ca(rcgen::BasicConstraints::Unconstrained);
    let cert = params.self_signed(&key_pair).unwrap();
    (key_pair.serialize_pem(), cert.pem())
}

async fn post_import(
    app: &impl actix_web::dev::Service<
        actix_http::Request,
        Response = actix_web::dev::ServiceResponse,
        Error = actix_web::Error,
    >,
    org_id: Uuid,
    token: &str,
    body: serde_json::Value,
) -> (u16, serde_json::Value) {
    let req = test::TestRequest::post()
        .uri(&format!(
            "/api/v1/organizations/{org_id}/ca-certificates/import"
        ))
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .set_json(body)
        .to_request();
    let resp = test::call_service(app, req).await;
    let status = resp.status().as_u16();
    let json = test::read_body_json(resp).await;
    (status, json)
}

#[actix_web::test]
async fn import_takes_custody_of_a_supplied_key() {
    let (db, org_id, tenant_id) = setup_db().await;
    let user_id = create_admin_user(&db, tenant_id).await;
    let auth = test_auth_config();
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let app = test_app!(db, auth);
    let (key_pem, cert_pem) = external_ca("Acme Offline Root");

    let (status, body) = post_import(
        &app,
        org_id,
        &token,
        serde_json::json!({
            "public_cert_pem": cert_pem,
            "private_key_pem": key_pem,
        }),
    )
    .await;

    assert_eq!(status, 201, "{body}");
    // Everything the record says comes from the certificate, not the request —
    // which never named a subject, a validity window or an algorithm.
    assert_eq!(body["subject"], "Acme Offline Root");
    assert_eq!(body["key_algorithm"], "Ed25519");
    assert_eq!(body["status"], "Active");
    assert_eq!(body["key_custody"], "database");
    // And the key itself never comes back out.
    assert!(body.get("private_key_pem").is_none(), "{body}");
    assert!(body.get("encrypted_private_key").is_none(), "{body}");
}

#[actix_web::test]
async fn import_without_a_key_records_the_ca_as_a_trust_anchor() {
    let (db, org_id, tenant_id) = setup_db().await;
    let user_id = create_admin_user(&db, tenant_id).await;
    let auth = test_auth_config();
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let app = test_app!(db, auth);
    let (_, cert_pem) = external_ca("Anchor Only Root");

    let (status, body) = post_import(
        &app,
        org_id,
        &token,
        serde_json::json!({ "public_cert_pem": cert_pem }),
    )
    .await;

    assert_eq!(status, 201, "{body}");
    assert_eq!(
        body["key_custody"], "external",
        "a CA with no key must say so, so the signing path can explain itself \
         instead of failing on an absent ciphertext"
    );
}

#[actix_web::test]
async fn an_empty_key_string_is_treated_as_no_key_at_all() {
    // An empty string is not a key. Storing one would produce a CA that lists
    // as issuable and dies at the first signature.
    let (db, org_id, tenant_id) = setup_db().await;
    let user_id = create_admin_user(&db, tenant_id).await;
    let auth = test_auth_config();
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let app = test_app!(db, auth);
    let (_, cert_pem) = external_ca("Empty Key Root");

    let (status, body) = post_import(
        &app,
        org_id,
        &token,
        serde_json::json!({ "public_cert_pem": cert_pem, "private_key_pem": "  " }),
    )
    .await;

    assert_eq!(status, 201, "{body}");
    assert_eq!(body["key_custody"], "external");
}

#[actix_web::test]
async fn import_refuses_a_key_that_belongs_to_a_different_ca() {
    let (db, org_id, tenant_id) = setup_db().await;
    let user_id = create_admin_user(&db, tenant_id).await;
    let auth = test_auth_config();
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let app = test_app!(db, auth);
    let (_, cert_pem) = external_ca("Acme Offline Root");
    let (other_key_pem, _) = external_ca("Somebody Else");

    let (status, body) = post_import(
        &app,
        org_id,
        &token,
        serde_json::json!({
            "public_cert_pem": cert_pem,
            "private_key_pem": other_key_pem,
        }),
    )
    .await;

    assert_eq!(status, 400, "{body}");
    assert!(
        body.to_string().contains("does not match"),
        "the message must name what is wrong: {body}"
    );
}

#[actix_web::test]
async fn import_refuses_something_that_is_not_a_ca() {
    let (db, org_id, tenant_id) = setup_db().await;
    let user_id = create_admin_user(&db, tenant_id).await;
    let auth = test_auth_config();
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let app = test_app!(db, auth);

    let (status, body) = post_import(
        &app,
        org_id,
        &token,
        serde_json::json!({ "public_cert_pem": "not a certificate" }),
    )
    .await;

    assert_eq!(status, 400, "{body}");
}

#[actix_web::test]
async fn an_imported_ca_can_sign_a_leaf_certificate() {
    // The whole point of importing a key rather than only a certificate. This
    // also exercises the custody read path end to end: the CA record says
    // `database`, and the signing path asks the record.
    let (db, org_id, tenant_id) = setup_db().await;
    let user_id = create_admin_user(&db, tenant_id).await;
    let auth = test_auth_config();
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let app = test_app!(db, auth);
    let (key_pem, cert_pem) = external_ca("Signing Root");

    let (status, ca) = post_import(
        &app,
        org_id,
        &token,
        serde_json::json!({
            "public_cert_pem": cert_pem,
            "private_key_pem": key_pem,
        }),
    )
    .await;
    assert_eq!(status, 201, "{ca}");

    let req = test::TestRequest::post()
        .uri("/api/v1/certificates")
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .set_json(serde_json::json!({
            "issuer_ca_id": ca["id"],
            "subject": "CN=device-1",
            "cert_type": "Device",
            "key_algorithm": "Ed25519",
            "validity_days": 30,
        }))
        .to_request();
    let resp = test::call_service(&app, req).await;
    let leaf_status = resp.status().as_u16();
    let leaf: serde_json::Value = test::read_body_json(resp).await;
    assert_eq!(leaf_status, 201, "{leaf}");
    assert!(leaf["private_key_pem"].is_string(), "{leaf}");
}

#[actix_web::test]
async fn a_trust_anchor_says_why_it_cannot_issue() {
    // Rather than the bare "no stored private key" this used to produce for
    // both a genuinely absent key and a decryption failure.
    let (db, org_id, tenant_id) = setup_db().await;
    let user_id = create_admin_user(&db, tenant_id).await;
    let auth = test_auth_config();
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let app = test_app!(db, auth);
    let (_, cert_pem) = external_ca("Anchor Only Root");

    let (_, ca) = post_import(
        &app,
        org_id,
        &token,
        serde_json::json!({ "public_cert_pem": cert_pem }),
    )
    .await;

    let req = test::TestRequest::post()
        .uri("/api/v1/certificates")
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .set_json(serde_json::json!({
            "issuer_ca_id": ca["id"],
            "subject": "CN=device-1",
            "cert_type": "Device",
            "key_algorithm": "Ed25519",
            "validity_days": 30,
        }))
        .to_request();
    let resp = test::call_service(&app, req).await;
    let body: serde_json::Value = test::read_body_json(resp).await;
    let msg = body.to_string();
    assert!(msg.contains("without a private key"), "{msg}");
    assert!(msg.contains("cannot issue"), "{msg}");
}

#[actix_web::test]
async fn cross_org_import_returns_403() {
    let (db, org_id, tenant_id) = setup_db().await;
    let user_id = create_admin_user(&db, tenant_id).await;
    let auth = test_auth_config();
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let app = test_app!(db, auth);
    let (_, cert_pem) = external_ca("Somebody Else's Root");

    let (status, _) = post_import(
        &app,
        Uuid::new_v4(),
        &token,
        serde_json::json!({ "public_cert_pem": cert_pem }),
    )
    .await;
    assert_eq!(status, 403);
}
