//! Integration tests for tenant certificate lifecycle endpoints.

use actix_web::{App, test, web};
use axiam_api_rest::RateLimitConfig;
use axiam_api_rest::authz::{AllowAllAuthzChecker, AuthzChecker};
use axiam_api_rest::register_api_v1_routes;
use axiam_api_rest::state::AppState;
use axiam_auth::config::AuthConfig;
use axiam_auth::token::issue_access_token;
use axiam_core::models::organization::CreateOrganization;
use axiam_core::models::tenant::{CreateTenant, TenantKind};
use axiam_core::models::user::CreateUser;
use axiam_core::repository::{OrganizationRepository, TenantRepository, UserRepository};
use axiam_db::{
    SurrealCaCertificateRepository, SurrealCertificateRepository, SurrealOrganizationRepository,
    SurrealTenantRepository, SurrealUserRepository,
};
use axiam_pki::{CaService, CertService, PkiConfig};
use std::sync::Arc;
use surrealdb::Surreal;
use surrealdb::engine::local::Mem;
use uuid::Uuid;

/// The CA key custodians these tests run against.
///
/// The same all-zero key `test_pki_config` uses, so a CA generated by one
/// service and signed with by another opens. Built through
/// `custodians_from_env` rather than by hand: it is the function the
/// composition root calls, and a test that assembled custody differently would
/// agree with itself and not with production.
#[allow(dead_code)]
fn test_ca_custodians() -> std::sync::Arc<axiam_pki::CaKeyCustodians> {
    std::sync::Arc::new(
        axiam_pki::custodians_from_env(Some([0u8; 32])) // gitleaks:allow
            .expect("test CA key custodians"),
    )
}

type TestDb = surrealdb::engine::local::Db;

/// Test-only placeholder password — not a real credential.
const TEST_PASSWORD: &str = "test-only-placeholder-not-a-real-password"; // gitleaks:allow

/// Arbitrary CSRF token for the double-submit check (SEC-046). These
/// Bearer-token tests have no login/`axiam_csrf` cookie, so we send a matching
/// `axiam_csrf` cookie + `X-CSRF-Token` header; the middleware only checks they
/// are equal (no session lookup). Safe (GET) requests ignore it.
const CSRF_TOKEN: &str = "test-csrf-token";

fn test_keypair() -> (String, String) {
    // Test-only non-secret Ed25519 key pair used solely for JWT signing in unit tests.
    let pem_header = "-----BEGIN PRIVATE KEY-----"; // nosemgrep: generic.secrets.security.detected-private-key
    let pem_body = "MC4CAQAwBQYDK2VwBCIEINvQFIZqeI5OX7TDEFKcYhLxO5R75FOv/nC4+o+HHPfM";
    let pem_footer = "-----END PRIVATE KEY-----";
    let private_key = format!("{pem_header}\n{pem_body}\n{pem_footer}");
    let public_key = "\
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAcweT2rPwpUxadO56wIhW1XBoMF63aWOE2UMAVsRudhs=
-----END PUBLIC KEY-----"
        .to_owned();
    (private_key, public_key)
}

fn test_auth_config() -> AuthConfig {
    let (priv_pem, pub_pem) = test_keypair();
    AuthConfig {
        jwt_private_key_pem: priv_pem,
        jwt_public_key_pem: pub_pem,
        access_token_lifetime_secs: 900,
        jwt_issuer: "axiam-test".into(),
        ..AuthConfig::default()
    }
}

/// Test-only PKI encryption key (32 zero bytes) — not a real key.
fn test_pki_config() -> PkiConfig {
    PkiConfig {
        encryption_key: Some([0u8; 32]), // gitleaks:allow
        ..Default::default()
    }
}

async fn setup_db() -> (Surreal<TestDb>, Uuid, Uuid) {
    let db = Surreal::new::<Mem>(()).await.unwrap();
    db.use_ns("test").use_db("test").await.unwrap();
    axiam_db::run_migrations(&db).await.unwrap();

    let org_repo = SurrealOrganizationRepository::new(db.clone());
    let org = org_repo
        .create(CreateOrganization {
            name: "Test Org".into(),
            slug: "test-org".into(),
            metadata: None,
        })
        .await
        .unwrap();

    let tenant_repo = SurrealTenantRepository::new(db.clone());
    let tenant = tenant_repo
        .create(CreateTenant {
            organization_id: org.id,
            kind: TenantKind::Standard,
            name: "Test Tenant".into(),
            slug: "test-tenant".into(),
            metadata: None,
        })
        .await
        .unwrap();

    (db, org.id, tenant.id)
}

async fn create_admin_user(db: &Surreal<TestDb>, tenant_id: Uuid) -> Uuid {
    let user_repo = SurrealUserRepository::new(db.clone());
    let user = user_repo
        .create(CreateUser {
            tenant_id,
            username: "admin".into(),
            email: "admin@example.com".into(),
            password: TEST_PASSWORD.into(),
            metadata: None,
        })
        .await
        .unwrap();
    user.id
}

/// A token for an administrator living in the organization's own reserved
/// tenant — for the one step in these tests that needs one.
///
/// Minting a CA is an organization-level action (B-04): a CA is the
/// organization's, and whoever holds its private key can sign certificates that
/// authenticate as principals in any tenant under it. So
/// `require_organization_principal` refuses `POST
/// /organizations/{id}/ca-certificates` to a tenant principal, whatever
/// permissions it holds, and the CA these tests need as a fixture cannot be
/// minted with the tenant token.
///
/// The leaf certificates this file is actually about stay tenant-level and keep
/// using the tenant token, which is the point: only the fixture step changes
/// principal, not the behaviour under test.
async fn organization_ca_token(db: &Surreal<TestDb>, auth: &AuthConfig, org_id: Uuid) -> String {
    let org_tenant = SurrealTenantRepository::new(db.clone())
        .create(CreateTenant::organization_scope(org_id))
        .await
        .unwrap();
    let user = SurrealUserRepository::new(db.clone())
        .create(CreateUser {
            tenant_id: org_tenant.id,
            username: "org-admin".into(),
            email: "org-admin@example.com".into(),
            password: TEST_PASSWORD.into(),
            metadata: None,
        })
        .await
        .unwrap();
    mint_token(auth, user.id, org_tenant.id, org_id)
}

fn mint_token(auth: &AuthConfig, user_id: Uuid, tenant_id: Uuid, org_id: Uuid) -> String {
    issue_access_token(
        user_id,
        tenant_id,
        org_id,
        &[],
        auth,
        uuid::Uuid::new_v4().to_string(),
        axiam_auth::token::AUD_USER,
    )
    .unwrap()
}

macro_rules! test_app {
    ($db:expr, $auth:expr) => {{
        let pki_config = test_pki_config();
        let ca_repo = SurrealCaCertificateRepository::new($db.clone());
        let cert_repo = SurrealCertificateRepository::new($db.clone());
        test::init_service(
            App::new()
                .app_data(web::Data::new($auth.clone()))
                .app_data(web::Data::new({
                    let mut state = AppState::for_test($db.clone(), $auth.clone());
                    state.pki.ca_service = CaService::new(
                        ca_repo.clone(),
                        pki_config.clone(),
                        std::sync::Arc::new(tokio::sync::Semaphore::new(4)),
                        test_ca_custodians(),
                    );
                    state.pki.cert_service = CertService::new(
                        ca_repo,
                        cert_repo,
                        pki_config,
                        std::sync::Arc::new(tokio::sync::Semaphore::new(4)),
                        test_ca_custodians(),
                    );
                    state
                }))
                .app_data(web::Data::new(
                    Arc::new(AllowAllAuthzChecker) as Arc<dyn AuthzChecker>
                ))
                .configure(|cfg| {
                    register_api_v1_routes::<TestDb>(cfg, &RateLimitConfig::default())
                }),
        )
        .await
    }};
}

/// Helper macro: generate a CA certificate and return its ID.
macro_rules! generate_ca {
    ($app:expr, $org_id:expr, $token:expr) => {{
        let req = test::TestRequest::post()
            .uri(&format!(
                "/api/v1/organizations/{}/ca-certificates",
                $org_id
            ))
            .insert_header(("Authorization", format!("Bearer {}", $token)))
            .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
            .insert_header(("X-CSRF-Token", CSRF_TOKEN))
            .insert_header(("Content-Type", "application/json"))
            .set_json(serde_json::json!({
                "subject": "Test CA",
                "key_algorithm": "Ed25519",
                "validity_days": 365
            }))
            .to_request();
        let resp = test::call_service(&$app, req).await;
        assert_eq!(resp.status().as_u16(), 201);
        let body: serde_json::Value = test::read_body_json(resp).await;
        body["id"].as_str().unwrap().to_string()
    }};
}

/// The tenant signing CA a leaf is issued under.
///
/// Since S-1 a tenant principal reaches exactly one CA: the one that signs for
/// the tenant it is acting on. The organization CA above it is reachable only
/// by a principal living in the organization scope, so every leaf test here
/// needs the two-tier shape the product actually deploys — which is the shape
/// tenant signing CAs were added for in the first place.
///
/// 364 days rather than 365: an intermediate may not outlive the CA that signed
/// it, and the parent was minted for 365 days a moment ago.
macro_rules! tenant_signing_ca {
    ($app:expr, $org_id:expr, $tenant_id:expr, $ca_token:expr, $parent:expr) => {{
        let req = test::TestRequest::post()
            .uri(&format!(
                "/api/v1/organizations/{}/tenants/{}/signing-cas",
                $org_id, $tenant_id
            ))
            .insert_header(("Authorization", format!("Bearer {}", $ca_token)))
            .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
            .insert_header(("X-CSRF-Token", CSRF_TOKEN))
            .insert_header(("Content-Type", "application/json"))
            .set_json(serde_json::json!({
                "parent_ca_id": $parent,
                "subject": "Tenant Signing CA",
                "key_algorithm": "Ed25519",
                "validity_days": 364
            }))
            .to_request();
        let resp = test::call_service(&$app, req).await;
        let status = resp.status().as_u16();
        let body: serde_json::Value = test::read_body_json(resp).await;
        assert_eq!(status, 201, "tenant signing CA: {body}");
        body["id"].as_str().unwrap().to_string()
    }};
}

#[actix_rt::test]
async fn generate_certificate_signed_by_ca() {
    let (db, org_id, tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let user_id = create_admin_user(&db, tenant_id).await;
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let ca_token = organization_ca_token(&db, &auth, org_id).await;
    let app = test_app!(db, auth);

    let org_ca_id = generate_ca!(app, org_id, ca_token);
    let ca_id = tenant_signing_ca!(app, org_id, tenant_id, ca_token, org_ca_id);

    let req = test::TestRequest::post()
        .uri("/api/v1/certificates")
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .insert_header(("Content-Type", "application/json"))
        .set_json(serde_json::json!({
            "issuer_ca_id": ca_id,
            "subject": "device-001",
            "cert_type": "Device",
            "key_algorithm": "Ed25519",
            "validity_days": 90
        }))
        .to_request();

    let resp = test::call_service(&app, req).await;
    let status = resp.status().as_u16();
    let body: serde_json::Value = test::read_body_json(resp).await;
    assert_eq!(status, 201, "body: {body}");
    assert!(
        body["private_key_pem"]
            .as_str()
            .unwrap()
            .contains("PRIVATE KEY")
    );
    assert!(
        body["public_cert_pem"]
            .as_str()
            .unwrap()
            .contains("CERTIFICATE")
    );
    assert_eq!(body["cert_type"], "Device");
    assert_eq!(body["status"], "Active");
    assert_eq!(body["issuer_ca_id"], ca_id);
}

#[actix_rt::test]
async fn list_certificates_returns_paginated() {
    let (db, org_id, tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let user_id = create_admin_user(&db, tenant_id).await;
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let ca_token = organization_ca_token(&db, &auth, org_id).await;
    let app = test_app!(db, auth);

    let org_ca_id = generate_ca!(app, org_id, ca_token);
    let ca_id = tenant_signing_ca!(app, org_id, tenant_id, ca_token, org_ca_id);

    for subject in ["svc-a", "svc-b"] {
        let req = test::TestRequest::post()
            .uri("/api/v1/certificates")
            .insert_header(("Authorization", format!("Bearer {token}")))
            .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
            .insert_header(("X-CSRF-Token", CSRF_TOKEN))
            .insert_header(("Content-Type", "application/json"))
            .set_json(serde_json::json!({
                "issuer_ca_id": ca_id,
                "subject": subject,
                "cert_type": "Service",
                "key_algorithm": "Ed25519",
                "validity_days": 90
            }))
            .to_request();
        let resp = test::call_service(&app, req).await;
        assert_eq!(resp.status().as_u16(), 201);
    }

    let req = test::TestRequest::get()
        .uri("/api/v1/certificates")
        .insert_header(("Authorization", format!("Bearer {token}")))
        .to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(resp.status().as_u16(), 200);

    let body: serde_json::Value = test::read_body_json(resp).await;
    assert_eq!(body["total"], 2);
    assert_eq!(body["items"].as_array().unwrap().len(), 2);
}

#[actix_rt::test]
async fn get_certificate_by_id() {
    let (db, org_id, tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let user_id = create_admin_user(&db, tenant_id).await;
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let ca_token = organization_ca_token(&db, &auth, org_id).await;
    let app = test_app!(db, auth);

    let org_ca_id = generate_ca!(app, org_id, ca_token);
    let ca_id = tenant_signing_ca!(app, org_id, tenant_id, ca_token, org_ca_id);

    let req = test::TestRequest::post()
        .uri("/api/v1/certificates")
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .insert_header(("Content-Type", "application/json"))
        .set_json(serde_json::json!({
            "issuer_ca_id": ca_id,
            "subject": "user-cert",
            "cert_type": "User",
            "key_algorithm": "Ed25519",
            // Inside the CA's window. The CA above is issued for 365 days a
            // moment earlier, so 365 here would end a few seconds AFTER its
            // issuer — which is now refused rather than silently truncated, the
            // truncation being the reported bug.
            "validity_days": 180
        }))
        .to_request();
    let resp = test::call_service(&app, req).await;
    let created: serde_json::Value = test::read_body_json(resp).await;
    let cert_id = created["id"].as_str().unwrap();

    let req = test::TestRequest::get()
        .uri(&format!("/api/v1/certificates/{cert_id}"))
        .insert_header(("Authorization", format!("Bearer {token}")))
        .to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(resp.status().as_u16(), 200);

    let body: serde_json::Value = test::read_body_json(resp).await;
    assert_eq!(body["subject"], "user-cert");
    assert_eq!(body["cert_type"], "User");
}

#[actix_rt::test]
async fn revoke_certificate() {
    let (db, org_id, tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let user_id = create_admin_user(&db, tenant_id).await;
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let ca_token = organization_ca_token(&db, &auth, org_id).await;
    let app = test_app!(db, auth);

    let org_ca_id = generate_ca!(app, org_id, ca_token);
    let ca_id = tenant_signing_ca!(app, org_id, tenant_id, ca_token, org_ca_id);

    let req = test::TestRequest::post()
        .uri("/api/v1/certificates")
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .insert_header(("Content-Type", "application/json"))
        .set_json(serde_json::json!({
            "issuer_ca_id": ca_id,
            "subject": "revocable",
            "cert_type": "Service",
            "key_algorithm": "Ed25519",
            "validity_days": 90
        }))
        .to_request();
    let resp = test::call_service(&app, req).await;
    let created: serde_json::Value = test::read_body_json(resp).await;
    let cert_id = created["id"].as_str().unwrap();

    let req = test::TestRequest::post()
        .uri(&format!("/api/v1/certificates/{cert_id}/revoke"))
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(resp.status().as_u16(), 200);

    let body: serde_json::Value = test::read_body_json(resp).await;
    assert_eq!(body["status"], "revoked");

    // Verify via GET.
    let req = test::TestRequest::get()
        .uri(&format!("/api/v1/certificates/{cert_id}"))
        .insert_header(("Authorization", format!("Bearer {token}")))
        .to_request();
    let resp = test::call_service(&app, req).await;
    let body: serde_json::Value = test::read_body_json(resp).await;
    assert_eq!(body["status"], "Revoked");
}

/// A leaf that would outlive its issuer is refused, and the error says by how
/// much it may live instead.
///
/// It used to be silently shortened to the CA's expiry: an operator asked for a
/// year against a 30-day CA, got 30 days, and nothing said so. A certificate
/// whose holder believes it is valid for longer than its chain validates is a
/// renewal that does not happen and an outage nobody predicted.
#[actix_rt::test]
async fn a_leaf_outliving_its_issuer_is_refused_with_the_real_maximum() {
    let (db, org_id, tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let user_id = create_admin_user(&db, tenant_id).await;
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let ca_token = organization_ca_token(&db, &auth, org_id).await;
    let app = test_app!(db, auth);

    // The organization CA is issued for 365 days a moment ago; the tenant
    // signing CA beneath it for 364, so it has 363 WHOLE days left.
    let org_ca_id = generate_ca!(app, org_id, ca_token);
    let ca_id = tenant_signing_ca!(app, org_id, tenant_id, ca_token, org_ca_id);

    let req = test::TestRequest::post()
        .uri("/api/v1/certificates")
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .insert_header(("Content-Type", "application/json"))
        .set_json(serde_json::json!({
            "issuer_ca_id": ca_id,
            "subject": "too-long",
            "cert_type": "Service",
            "key_algorithm": "Ed25519",
            // 365, not something larger. A bigger number never reaches the
            // issuer-expiry check at all: the tenant's own `max_validity_days`
            // cap (365 by default) refuses it first, with a message about the
            // tenant policy that says nothing about the CA. 365 is the smallest
            // request that clears every earlier gate and still outlives this
            // issuer — by the seconds that elapsed between the two calls.
            "validity_days": 365
        }))
        .to_request();

    let resp = test::call_service(&app, req).await;
    let status = resp.status().as_u16();
    let body: serde_json::Value = test::read_body_json(resp).await;
    assert_eq!(status, 400, "body: {body}");

    // The number is the point: an error that only says "too long" leaves the
    // operator guessing at the value the form should have offered. The issuer
    // is the tenant signing CA, minted moments ago for 364 days, so whole days
    // remaining is 363.
    let message = body.to_string();
    assert!(
        message.contains("cannot outlive its issuer"),
        "the refusal must say why, got: {message}"
    );
    assert!(
        message.contains("363 days"),
        "the refusal must quote the maximum the issuer can grant, got: {message}"
    );
}

#[actix_rt::test]
async fn certificate_endpoints_require_auth() {
    let (db, _org_id, _tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let app = test_app!(db, auth);

    let endpoints = vec![
        ("POST", "/api/v1/certificates".to_string()),
        ("POST", "/api/v1/certificates/sign-csr".to_string()),
        ("GET", "/api/v1/certificates".to_string()),
        ("GET", format!("/api/v1/certificates/{}", Uuid::new_v4())),
        (
            "POST",
            format!("/api/v1/certificates/{}/revoke", Uuid::new_v4()),
        ),
    ];

    for (method, uri) in endpoints {
        let req = match method {
            "POST" => test::TestRequest::post()
                .uri(&uri)
                .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
                .insert_header(("X-CSRF-Token", CSRF_TOKEN))
                .to_request(),
            _ => test::TestRequest::get().uri(&uri).to_request(),
        };
        let resp = test::call_service(&app, req).await;
        assert_eq!(
            resp.status().as_u16(),
            401,
            "{method} {uri} should require auth"
        );
    }
}

// ---------------------------------------------------------------------------
// `POST /api/v1/certificates/sign-csr` — a certificate for a key AXIAM never
// sees (C-1, T-268)
// ---------------------------------------------------------------------------

/// A PEM PKCS#10 request carrying nothing but a common name.
fn plain_csr(common_name: &str) -> String {
    let key = rcgen::KeyPair::generate_for(&rcgen::PKCS_ED25519).expect("key");
    let mut params = rcgen::CertificateParams::new(Vec::<String>::new()).expect("params");
    params
        .distinguished_name
        .push(rcgen::DnType::CommonName, common_name);
    params
        .serialize_request(&key)
        .expect("csr")
        .pem()
        .expect("pem")
}

#[actix_rt::test]
async fn sign_csr_issues_a_certificate_that_carries_no_private_key() {
    let (db, org_id, tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let user_id = create_admin_user(&db, tenant_id).await;
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let ca_token = organization_ca_token(&db, &auth, org_id).await;
    let app = test_app!(db, auth);
    let org_ca_id = generate_ca!(app, org_id, ca_token);
    let ca_id = tenant_signing_ca!(app, org_id, tenant_id, ca_token, org_ca_id);

    let req = test::TestRequest::post()
        .uri("/api/v1/certificates/sign-csr")
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .insert_header(("Content-Type", "application/json"))
        .set_json(serde_json::json!({
            "issuer_ca_id": ca_id,
            "csr_pem": plain_csr("byok-device-001"),
            "cert_type": "Device",
            "validity_days": 90
        }))
        .to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(resp.status().as_u16(), 201);

    let body: serde_json::Value = test::read_body_json(resp).await;
    // Not merely null or empty: the key is **absent**, because the response
    // type has no field for it. A `GeneratedCertificate` here would be a type
    // with a mandatory key field that is always missing.
    assert!(
        body.get("private_key_pem").is_none(),
        "the response must carry no key field at all, got: {body}"
    );
    assert!(
        !serde_json::to_string(&body)
            .unwrap()
            .contains("PRIVATE KEY"),
        "and no key material anywhere in it"
    );
    assert_eq!(body["subject"], "byok-device-001");
    assert_eq!(body["key_algorithm"], "Ed25519");
    assert_eq!(body["status"], "Active");

    // It is an ordinary certificate afterwards: readable, and listed unbound.
    let id = body["id"].as_str().unwrap().to_string();
    let req = test::TestRequest::get()
        .uri(&format!("/api/v1/certificates/{id}"))
        .insert_header(("Authorization", format!("Bearer {token}")))
        .to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(resp.status().as_u16(), 200);
    let fetched: serde_json::Value = test::read_body_json(resp).await;
    assert_eq!(fetched["fingerprint"], body["fingerprint"]);

    let req = test::TestRequest::get()
        .uri("/api/v1/certificates")
        .insert_header(("Authorization", format!("Bearer {token}")))
        .to_request();
    let listed: serde_json::Value = test::read_body_json(test::call_service(&app, req).await).await;
    let row = listed["items"]
        .as_array()
        .expect("a page of items")
        .iter()
        .find(|c| c["id"] == body["id"])
        .expect("the new certificate is listed");
    assert!(
        row["bound_to"].is_null(),
        "a freshly signed certificate is bound to nothing"
    );
}

#[actix_rt::test]
async fn sign_csr_refusals_are_400s_that_say_what_is_wrong() {
    let (db, org_id, tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let user_id = create_admin_user(&db, tenant_id).await;
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let ca_token = organization_ca_token(&db, &auth, org_id).await;
    let app = test_app!(db, auth);
    let org_ca_id = generate_ca!(app, org_id, ca_token);
    let ca_id = tenant_signing_ca!(app, org_id, tenant_id, ca_token, org_ca_id);

    // A CSR asking for a subjectAltName, which is refused by name rather than
    // dropped (D-3).
    let san_csr = {
        let key = rcgen::KeyPair::generate_for(&rcgen::PKCS_ED25519).expect("key");
        let mut params =
            rcgen::CertificateParams::new(vec!["svc.example.com".to_string()]).expect("params");
        params
            .distinguished_name
            .push(rcgen::DnType::CommonName, "svc.example.com");
        params
            .serialize_request(&key)
            .expect("csr")
            .pem()
            .expect("pem")
    };

    let cases: Vec<(&str, serde_json::Value, &str)> = vec![
        (
            "a request that is not a CSR at all",
            serde_json::json!({
                "issuer_ca_id": ca_id, "csr_pem": "hello",
                "cert_type": "Device", "validity_days": 30
            }),
            "certificate signing request",
        ),
        (
            "a CSR asking for a subjectAltName",
            serde_json::json!({
                "issuer_ca_id": ca_id, "csr_pem": san_csr,
                "cert_type": "Service", "validity_days": 30
            }),
            "subjectAltName",
        ),
        (
            "a validity beyond the 825-day hard cap",
            serde_json::json!({
                "issuer_ca_id": ca_id, "csr_pem": plain_csr("too-long"),
                "cert_type": "Device", "validity_days": 900
            }),
            "validity_days",
        ),
    ];

    for (what, payload, expected) in cases {
        let req = test::TestRequest::post()
            .uri("/api/v1/certificates/sign-csr")
            .insert_header(("Authorization", format!("Bearer {token}")))
            .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
            .insert_header(("X-CSRF-Token", CSRF_TOKEN))
            .insert_header(("Content-Type", "application/json"))
            .set_json(payload)
            .to_request();
        let resp = test::call_service(&app, req).await;
        assert_eq!(resp.status().as_u16(), 400, "{what} must be a 400");
        let body: serde_json::Value = test::read_body_json(resp).await;
        let message = body["message"].as_str().unwrap_or_default();
        assert!(
            message.contains(expected),
            "{what}: the message reaches the operator who pasted the request \
             and must name the problem — expected {expected:?}, got {message:?}"
        );
    }
}

#[actix_rt::test]
async fn sign_csr_cannot_reach_another_organizations_ca() {
    // T-98. The issuer is resolved within the caller's organization, so a CA id
    // from elsewhere is not found rather than usable.
    let (db, org_id, tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let user_id = create_admin_user(&db, tenant_id).await;
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let app = test_app!(db, auth);

    let req = test::TestRequest::post()
        .uri("/api/v1/certificates/sign-csr")
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .insert_header(("Content-Type", "application/json"))
        .set_json(serde_json::json!({
            "issuer_ca_id": Uuid::new_v4(),
            "csr_pem": plain_csr("stranger"),
            "cert_type": "Device",
            "validity_days": 30
        }))
        .to_request();
    assert_eq!(test::call_service(&app, req).await.status().as_u16(), 404);
}

#[actix_rt::test]
async fn sign_csr_cannot_reach_another_tenants_signing_ca() {
    // T-281, the tenant twin of the test above. The CA exists, is active, is in
    // its window, and belongs to this organization — every earlier gate passes.
    // It simply signs for somebody else.
    let (db, org_id, tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let user_id = create_admin_user(&db, tenant_id).await;
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let ca_token = organization_ca_token(&db, &auth, org_id).await;

    let neighbour = SurrealTenantRepository::new(db.clone())
        .create(CreateTenant {
            organization_id: org_id,
            kind: TenantKind::Standard,
            name: "Neighbour Tenant".into(),
            slug: "neighbour-tenant".into(),
            metadata: None,
        })
        .await
        .unwrap();

    let app = test_app!(db, auth);
    let org_ca_id = generate_ca!(app, org_id, ca_token);
    let theirs = tenant_signing_ca!(app, org_id, neighbour.id, ca_token, org_ca_id);

    let req = test::TestRequest::post()
        .uri("/api/v1/certificates/sign-csr")
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .insert_header(("Content-Type", "application/json"))
        .set_json(serde_json::json!({
            "issuer_ca_id": theirs,
            "csr_pem": plain_csr("poaching"),
            "cert_type": "Device",
            "validity_days": 30
        }))
        .to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(
        resp.status().as_u16(),
        404,
        "a CA that signs for another tenant must be invisible, not merely \
         refused"
    );
}

/// The I4 twin at the wire: the organization CA is still reachable by a
/// principal whose own record lives in the organization scope.
#[actix_rt::test]
async fn sign_csr_under_the_organization_ca_still_works_for_an_organization_principal() {
    let (db, org_id, _tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let ca_token = organization_ca_token(&db, &auth, org_id).await;
    let app = test_app!(db, auth);
    let org_ca_id = generate_ca!(app, org_id, ca_token);

    let req = test::TestRequest::post()
        .uri("/api/v1/certificates/sign-csr")
        .insert_header(("Authorization", format!("Bearer {ca_token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .insert_header(("Content-Type", "application/json"))
        .set_json(serde_json::json!({
            "issuer_ca_id": org_ca_id,
            "csr_pem": plain_csr("organization-issued"),
            "cert_type": "Service",
            "validity_days": 30
        }))
        .to_request();
    let resp = test::call_service(&app, req).await;
    let status = resp.status().as_u16();
    let body: serde_json::Value = test::read_body_json(resp).await;
    assert_eq!(status, 201, "body: {body}");
    assert_eq!(body["issuer_ca_id"], org_ca_id);
}

// ---------------------------------------------------------------------------
// `signing-cas/sign-csr` had no HTTP-level test at all before C-1
// ---------------------------------------------------------------------------

#[actix_rt::test]
async fn signing_a_tenant_ca_csr_over_http_yields_an_intermediate_with_external_custody() {
    // The review found `grep signing-cas crates/axiam-api-rest/tests` empty:
    // the endpoint the leaf path is modelled on had service-level coverage and
    // nothing at the wire. This is the twenty-line twin of the leaf test above.
    let (db, org_id, tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let ca_token = organization_ca_token(&db, &auth, org_id).await;
    let app = test_app!(db, auth);
    let ca_id = generate_ca!(app, org_id, ca_token);

    let req = test::TestRequest::post()
        .uri(&format!(
            "/api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas/sign-csr"
        ))
        .insert_header(("Authorization", format!("Bearer {ca_token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .insert_header(("Content-Type", "application/json"))
        .set_json(serde_json::json!({
            "parent_ca_id": ca_id,
            "csr_pem": plain_csr("Offline Tenant CA"),
            // Less than the parent's own 365: an intermediate may not outlive
            // the CA that signs it, and the refusal quotes the real remainder.
            "validity_days": 180
        }))
        .to_request();
    let resp = test::call_service(&app, req).await;
    let status = resp.status().as_u16();
    let body: serde_json::Value = test::read_body_json(resp).await;
    assert_eq!(status, 201, "a tenant CSR is signed; got {body}");

    assert_eq!(body["subject"], "Offline Tenant CA");
    // AXIAM signed it and holds nothing: the key is wherever the CSR was made
    // (T-194).
    assert_eq!(body["key_custody"], "external");
    assert!(
        body.get("private_key_pem").is_none() || body["private_key_pem"].is_null(),
        "there is no key to return, got: {body}"
    );
}
