//! Integration tests for IoT device certificate authentication (mTLS).

use std::sync::Arc;

use actix_web::{App, test, web};
use axiam_api_rest::RateLimitConfig;
use axiam_api_rest::authz::{AllowAllAuthzChecker, AuthzChecker};
use axiam_api_rest::register_api_v1_routes;
use axiam_api_rest::state::AppState;
use axiam_auth::config::AuthConfig;
use axiam_auth::token::{SubjectKind, decode_access_token, issue_access_token};
use axiam_core::models::organization::CreateOrganization;
use axiam_core::models::tenant::{CreateTenant, TenantKind};
use axiam_core::models::user::CreateUser;
use axiam_core::repository::{OrganizationRepository, TenantRepository, UserRepository};
use axiam_db::{
    SurrealCaCertificateRepository, SurrealCertificateRepository, SurrealOrganizationRepository,
    SurrealTenantRepository, SurrealUserRepository,
};
use axiam_pki::{CaService, CertService, DeviceAuthService, PkiConfig};
use surrealdb::Surreal;
use surrealdb::engine::local::Mem;
use uuid::Uuid;

/// The CA key custodians these tests run against.
///
/// The same all-zero key `test_pki_config` uses, so a CA generated by one
/// service and signed with by another opens. Built through
/// `custodians_from_env` rather than by hand: it is the function the
/// composition root calls, and a test that assembled custody differently would
/// agree with itself and not with production.
#[allow(dead_code)]
fn test_ca_custodians() -> std::sync::Arc<axiam_pki::CaKeyCustodians> {
    std::sync::Arc::new(
        axiam_pki::custodians_from_env(Some([0u8; 32])) // gitleaks:allow
            .expect("test CA key custodians"),
    )
}

type TestDb = surrealdb::engine::local::Db;

/// Test-only placeholder password — not a real credential.
const TEST_PASSWORD: &str = "test-only-placeholder-not-a-real-password"; // gitleaks:allow

/// Arbitrary CSRF token for the double-submit check (SEC-046). These
/// Bearer-token tests have no login/`axiam_csrf` cookie, so we send a matching
/// `axiam_csrf` cookie + `X-CSRF-Token` header; the middleware only checks they
/// are equal (no session lookup). Safe (GET) and CSRF-exempt requests ignore it.
const CSRF_TOKEN: &str = "test-csrf-token";

fn test_keypair() -> (String, String) {
    // Test-only non-secret Ed25519 key pair used solely for JWT signing in unit tests.
    let pem_header = "-----BEGIN PRIVATE KEY-----"; // nosemgrep: generic.secrets.security.detected-private-key
    let pem_body = "MC4CAQAwBQYDK2VwBCIEINvQFIZqeI5OX7TDEFKcYhLxO5R75FOv/nC4+o+HHPfM";
    let pem_footer = "-----END PRIVATE KEY-----";
    let private_key = format!("{pem_header}\n{pem_body}\n{pem_footer}");
    let public_key = "\
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAcweT2rPwpUxadO56wIhW1XBoMF63aWOE2UMAVsRudhs=
-----END PUBLIC KEY-----"
        .to_owned();
    (private_key, public_key)
}

fn test_auth_config() -> AuthConfig {
    let (priv_pem, pub_pem) = test_keypair();
    AuthConfig {
        jwt_private_key_pem: priv_pem,
        jwt_public_key_pem: pub_pem,
        access_token_lifetime_secs: 900,
        jwt_issuer: "axiam-test".into(),
        ..AuthConfig::default()
    }
}

/// Test-only PKI encryption key (32 zero bytes) — not a real key.
fn test_pki_config() -> PkiConfig {
    PkiConfig {
        encryption_key: Some([0u8; 32]), // gitleaks:allow
        ..Default::default()
    }
}

async fn setup_db() -> (Surreal<TestDb>, Uuid, Uuid) {
    let db = Surreal::new::<Mem>(()).await.unwrap();
    db.use_ns("test").use_db("test").await.unwrap();
    axiam_db::run_migrations(&db).await.unwrap();

    let org_repo = SurrealOrganizationRepository::new(db.clone());
    let org = org_repo
        .create(CreateOrganization {
            name: "Test Org".into(),
            slug: "test-org".into(),
            metadata: None,
        })
        .await
        .unwrap();

    let tenant_repo = SurrealTenantRepository::new(db.clone());
    let tenant = tenant_repo
        .create(CreateTenant {
            organization_id: org.id,
            kind: TenantKind::Standard,
            name: "Test Tenant".into(),
            slug: "test-tenant".into(),
            metadata: None,
        })
        .await
        .unwrap();

    (db, org.id, tenant.id)
}

async fn create_admin_user(db: &Surreal<TestDb>, tenant_id: Uuid) -> Uuid {
    let user_repo = SurrealUserRepository::new(db.clone());
    let user = user_repo
        .create(CreateUser {
            tenant_id,
            username: "admin".into(),
            email: "admin@example.com".into(),
            password: TEST_PASSWORD.into(),
            metadata: None,
        })
        .await
        .unwrap();
    user.id
}

/// A token for an administrator living in the organization's own reserved
/// tenant — for the one step in these tests that needs one.
///
/// Minting a CA is an organization-level action (B-04): a CA is the
/// organization's, and whoever holds its private key can sign certificates that
/// authenticate as principals in any tenant under it. So
/// `require_organization_principal` refuses `POST
/// /organizations/{id}/ca-certificates` to a tenant principal, whatever
/// permissions it holds, and the CA these tests need as a fixture cannot be
/// minted with the tenant token.
///
/// The leaf certificates this file is actually about stay tenant-level and keep
/// using the tenant token, which is the point: only the fixture step changes
/// principal, not the behaviour under test.
async fn organization_ca_token(db: &Surreal<TestDb>, auth: &AuthConfig, org_id: Uuid) -> String {
    let org_tenant = SurrealTenantRepository::new(db.clone())
        .create(CreateTenant::organization_scope(org_id))
        .await
        .unwrap();
    let user = SurrealUserRepository::new(db.clone())
        .create(CreateUser {
            tenant_id: org_tenant.id,
            username: "org-admin".into(),
            email: "org-admin@example.com".into(),
            password: TEST_PASSWORD.into(),
            metadata: None,
        })
        .await
        .unwrap();
    mint_token(auth, user.id, org_tenant.id, org_id)
}

/// Flag a CA as an organization-wide mTLS trust anchor.
///
/// B-06: `/auth/device` no longer accepts a client certificate merely because
/// it chains to some CA of the organization. `mtls::require_trust_anchor` walks
/// `parent_ca_id` until it reaches a CA an operator has flagged, and refuses if
/// it reaches none — a certificate under a never-flagged CA authenticating a
/// device was the defect the walk closed.
///
/// So the fixture now does what an operator has to do for a device to get in.
/// Applied to the refusal cases too, not only the happy path: without it they
/// would be refused for the missing anchor rather than for the revoked or
/// unbound certificate they are named after, and would pass without testing it.
async fn flag_trust_anchor(db: &Surreal<TestDb>, org_id: Uuid, ca_id: &str) {
    use axiam_core::repository::CaCertificateRepository as _;
    SurrealCaCertificateRepository::new(db.clone())
        .set_mtls_trust_anchor(org_id, ca_id.parse().unwrap(), true)
        .await
        .unwrap();
}

fn mint_token(auth: &AuthConfig, user_id: Uuid, tenant_id: Uuid, org_id: Uuid) -> String {
    issue_access_token(
        user_id,
        tenant_id,
        org_id,
        &[],
        auth,
        uuid::Uuid::new_v4().to_string(),
        axiam_auth::token::AUD_USER,
    )
    .unwrap()
}

macro_rules! test_app {
    ($db:expr, $auth:expr) => {{
        let pki_config = test_pki_config();
        let ca_repo = SurrealCaCertificateRepository::new($db.clone());
        let cert_repo = SurrealCertificateRepository::new($db.clone());
        let authz: Arc<dyn AuthzChecker> = Arc::new(AllowAllAuthzChecker);
        test::init_service(
            App::new()
                .app_data(web::Data::new($auth.clone()))
                .app_data(web::Data::new({
                    let mut state = AppState::for_test($db.clone(), $auth.clone());
                    state.pki.device_auth_service =
                        DeviceAuthService::new(cert_repo.clone(), ca_repo.clone());
                    state.pki.ca_service = CaService::new(
                        ca_repo.clone(),
                        pki_config.clone(),
                        std::sync::Arc::new(tokio::sync::Semaphore::new(4)),
                        test_ca_custodians(),
                    );
                    state.pki.cert_service = CertService::new(
                        ca_repo,
                        cert_repo.clone(),
                        pki_config,
                        std::sync::Arc::new(tokio::sync::Semaphore::new(4)),
                        test_ca_custodians(),
                    );
                    state.pki.cert_repo = cert_repo;
                    state
                }))
                .app_data(web::Data::new(authz))
                .configure(|cfg| {
                    register_api_v1_routes::<TestDb>(cfg, &RateLimitConfig::default())
                }),
        )
        .await
    }};
}

/// Helper: generate a CA certificate and return its ID.
macro_rules! generate_ca {
    ($app:expr, $org_id:expr, $token:expr) => {{
        let req = test::TestRequest::post()
            .uri(&format!(
                "/api/v1/organizations/{}/ca-certificates",
                $org_id
            ))
            .insert_header(("Authorization", format!("Bearer {}", $token)))
            .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
            .insert_header(("X-CSRF-Token", CSRF_TOKEN))
            .insert_header(("Content-Type", "application/json"))
            .set_json(serde_json::json!({
                "subject": "Test CA",
                "key_algorithm": "Ed25519",
                "validity_days": 365
            }))
            .to_request();
        let resp = test::call_service(&$app, req).await;
        assert_eq!(resp.status().as_u16(), 201);
        let body: serde_json::Value = test::read_body_json(resp).await;
        body["id"].as_str().unwrap().to_string()
    }};
}

/// Helper: generate a device certificate and return (cert_id, public_cert_pem).
macro_rules! generate_device_cert {
    ($app:expr, $ca_id:expr, $token:expr) => {{
        let req = test::TestRequest::post()
            .uri("/api/v1/certificates")
            .insert_header(("Authorization", format!("Bearer {}", $token)))
            .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
            .insert_header(("X-CSRF-Token", CSRF_TOKEN))
            .insert_header(("Content-Type", "application/json"))
            .set_json(serde_json::json!({
                "issuer_ca_id": $ca_id,
                "subject": "device-001",
                "cert_type": "Device",
                "key_algorithm": "Ed25519",
                "validity_days": 90
            }))
            .to_request();
        let resp = test::call_service(&$app, req).await;
        assert_eq!(resp.status().as_u16(), 201);
        let body: serde_json::Value = test::read_body_json(resp).await;
        let cert_id = body["id"].as_str().unwrap().to_string();
        let public_cert_pem = body["public_cert_pem"].as_str().unwrap().to_string();
        (cert_id, public_cert_pem)
    }};
}

/// Helper: create a service account and return its ID.
macro_rules! create_service_account {
    ($app:expr, $token:expr) => {{
        let req = test::TestRequest::post()
            .uri("/api/v1/service-accounts")
            .insert_header(("Authorization", format!("Bearer {}", $token)))
            .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
            .insert_header(("X-CSRF-Token", CSRF_TOKEN))
            .insert_header(("Content-Type", "application/json"))
            .set_json(serde_json::json!({
                "name": "iot-gateway"
            }))
            .to_request();
        let resp = test::call_service(&$app, req).await;
        assert_eq!(resp.status().as_u16(), 201);
        let body: serde_json::Value = test::read_body_json(resp).await;
        body["id"].as_str().unwrap().to_string()
    }};
}

/// URL-encode a PEM string for the X-Client-Certificate header.
fn urlencode(input: &str) -> String {
    let mut result = String::with_capacity(input.len() * 3);
    for byte in input.bytes() {
        match byte {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                result.push(byte as char);
            }
            _ => {
                result.push('%');
                result.push_str(&format!("{:02X}", byte));
            }
        }
    }
    result
}

#[actix_rt::test]
async fn device_auth_full_flow() {
    let (db, org_id, tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let user_id = create_admin_user(&db, tenant_id).await;
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let ca_token = organization_ca_token(&db, &auth, org_id).await;
    let app = test_app!(db, auth);

    // 1. Generate CA
    let ca_id = generate_ca!(app, org_id, ca_token);
    flag_trust_anchor(&db, org_id, &ca_id).await;

    // 2. Generate device certificate
    let (cert_id, public_cert_pem) = generate_device_cert!(app, ca_id, token);

    // 3. Create service account
    let sa_id = create_service_account!(app, token);

    // 4. Bind certificate to service account
    let req = test::TestRequest::post()
        .uri(&format!(
            "/api/v1/service-accounts/{sa_id}/bind-certificate"
        ))
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .insert_header(("Content-Type", "application/json"))
        .set_json(serde_json::json!({
            "certificate_id": cert_id
        }))
        .to_request();
    let resp = test::call_service(&app, req).await;
    let status = resp.status().as_u16();
    let body: serde_json::Value = test::read_body_json(resp).await;
    assert_eq!(status, 200, "bind failed: {body}");

    // 5. Authenticate via device cert
    let encoded_pem = urlencode(&public_cert_pem);
    let req = test::TestRequest::post()
        .uri("/api/v1/auth/device")
        .insert_header(("X-Client-Certificate", encoded_pem.as_str()))
        .to_request();
    let resp = test::call_service(&app, req).await;
    let status = resp.status().as_u16();
    let body: serde_json::Value = test::read_body_json(resp).await;
    assert_eq!(status, 200, "device auth failed: {body}");
    assert!(body["access_token"].as_str().unwrap().len() > 10);
    assert_eq!(body["token_type"], "Bearer");
}

#[actix_rt::test]
async fn device_auth_mints_service_account_sub_kind() {
    // FUNC-04 (D-09): the SA cert-auth device-auth path mints a token whose
    // decoded sub_kind claim is ServiceAccount (not the default User).
    let (db, org_id, tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let user_id = create_admin_user(&db, tenant_id).await;
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let ca_token = organization_ca_token(&db, &auth, org_id).await;
    let app = test_app!(db, auth.clone());

    let ca_id = generate_ca!(app, org_id, ca_token);
    flag_trust_anchor(&db, org_id, &ca_id).await;
    let (cert_id, public_cert_pem) = generate_device_cert!(app, ca_id, token);
    let sa_id = create_service_account!(app, token);

    let req = test::TestRequest::post()
        .uri(&format!(
            "/api/v1/service-accounts/{sa_id}/bind-certificate"
        ))
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .insert_header(("Content-Type", "application/json"))
        .set_json(serde_json::json!({ "certificate_id": cert_id }))
        .to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(resp.status().as_u16(), 200);

    let encoded_pem = urlencode(&public_cert_pem);
    let req = test::TestRequest::post()
        .uri("/api/v1/auth/device")
        .insert_header(("X-Client-Certificate", encoded_pem.as_str()))
        .to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(resp.status().as_u16(), 200);
    let body: serde_json::Value = test::read_body_json(resp).await;
    let access_token = body["access_token"].as_str().unwrap();

    let claims = decode_access_token(access_token, &auth).unwrap();
    assert_eq!(claims.sub_kind, SubjectKind::ServiceAccount);

    // §17.2 residual 1: the device path now mints the MACHINE audience. It
    // used to stamp `axiam:user`, which meant a certificate-authenticated
    // device passed every user-facing route guard — the same principal got a
    // user token by certificate and a machine token by secret, leaving the
    // SEC-006 / §4.3 narrowing half applied.
    //
    // Nothing pinned the audience on this path before, which is why the flip
    // was invisible to this suite.
    assert_eq!(
        claims.aud.as_deref(),
        Some(axiam_auth::token::AUD_M2M),
        "a device token must carry the machine audience"
    );

    // And the narrowing must actually bite: the same token is refused by a
    // user-facing route. Without this the assertion above only pins a string.
    let req = test::TestRequest::get()
        .uri("/api/v1/users")
        .insert_header(("Authorization", format!("Bearer {access_token}")))
        .to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(
        resp.status().as_u16(),
        401,
        "a device token must not be accepted on a user-facing route"
    );
}

#[actix_rt::test]
async fn device_auth_unbound_cert_returns_error() {
    let (db, org_id, tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let user_id = create_admin_user(&db, tenant_id).await;
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let ca_token = organization_ca_token(&db, &auth, org_id).await;
    let app = test_app!(db, auth);

    let ca_id = generate_ca!(app, org_id, ca_token);
    flag_trust_anchor(&db, org_id, &ca_id).await;
    let (_cert_id, public_cert_pem) = generate_device_cert!(app, ca_id, token);

    // Try to authenticate without binding
    let encoded_pem = urlencode(&public_cert_pem);
    let req = test::TestRequest::post()
        .uri("/api/v1/auth/device")
        .insert_header(("X-Client-Certificate", encoded_pem.as_str()))
        .to_request();
    let resp = test::call_service(&app, req).await;
    // Should fail because cert is not bound to a service account
    assert_ne!(resp.status().as_u16(), 200);
}

// ---------------------------------------------------------------------------
// R4: cert_auth.rs — invalid-encoding and unknown-certificate arms.
// ---------------------------------------------------------------------------

#[actix_rt::test]
async fn device_auth_invalid_url_encoding_returns_401() {
    let (db, _org_id, _tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let app = test_app!(db, auth);

    // "%zz" is not a valid percent-encoded byte (z is not a hex digit) —
    // exercises `urldecode`'s `hex_val` error arm.
    let req = test::TestRequest::post()
        .uri("/api/v1/auth/device")
        .insert_header(("X-Client-Certificate", "%zz-not-valid-percent-encoding"))
        .to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(resp.status().as_u16(), 401);
}

#[actix_rt::test]
async fn device_auth_unknown_certificate_returns_401() {
    let (db, _org_id, _tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let app = test_app!(db, auth);

    // A well-formed, self-signed certificate that was never registered
    // via the CA/certificate-issuance API — `DeviceAuthService::authenticate`
    // must reject it as unknown (NotFound -> AuthenticationFailed).
    let cert = rcgen::generate_simple_self_signed(vec!["never-registered.example.com".into()])
        .expect("generate self-signed cert");
    let pem = cert.cert.pem();

    let encoded_pem = urlencode(&pem);
    let req = test::TestRequest::post()
        .uri("/api/v1/auth/device")
        .insert_header(("X-Client-Certificate", encoded_pem.as_str()))
        .to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(resp.status().as_u16(), 401);
}

#[actix_rt::test]
async fn device_auth_missing_cert_header_returns_401() {
    let (db, _org_id, _tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let app = test_app!(db, auth);

    let req = test::TestRequest::post()
        .uri("/api/v1/auth/device")
        .to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(resp.status().as_u16(), 401);
}

#[actix_rt::test]
async fn bind_certificate_requires_auth() {
    let (db, _org_id, _tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let app = test_app!(db, auth);

    let req = test::TestRequest::post()
        .uri(&format!(
            "/api/v1/service-accounts/{}/bind-certificate",
            Uuid::new_v4()
        ))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .insert_header(("Content-Type", "application/json"))
        .set_json(serde_json::json!({
            "certificate_id": Uuid::new_v4().to_string()
        }))
        .to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(resp.status().as_u16(), 401);
}

#[actix_rt::test]
async fn device_auth_revoked_cert_returns_error() {
    let (db, org_id, tenant_id) = setup_db().await;
    let auth = test_auth_config();
    let user_id = create_admin_user(&db, tenant_id).await;
    let token = mint_token(&auth, user_id, tenant_id, org_id);
    let ca_token = organization_ca_token(&db, &auth, org_id).await;
    let app = test_app!(db, auth);

    let ca_id = generate_ca!(app, org_id, ca_token);
    flag_trust_anchor(&db, org_id, &ca_id).await;
    let (cert_id, public_cert_pem) = generate_device_cert!(app, ca_id, token);
    let sa_id = create_service_account!(app, token);

    // Bind
    let req = test::TestRequest::post()
        .uri(&format!(
            "/api/v1/service-accounts/{sa_id}/bind-certificate"
        ))
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .insert_header(("Content-Type", "application/json"))
        .set_json(serde_json::json!({ "certificate_id": cert_id }))
        .to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(resp.status().as_u16(), 200);

    // Revoke the certificate
    let req = test::TestRequest::post()
        .uri(&format!("/api/v1/certificates/{cert_id}/revoke"))
        .insert_header(("Authorization", format!("Bearer {token}")))
        .insert_header(("Cookie", format!("axiam_csrf={CSRF_TOKEN}")))
        .insert_header(("X-CSRF-Token", CSRF_TOKEN))
        .to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(resp.status().as_u16(), 200);

    // Try to authenticate with revoked cert
    let encoded_pem = urlencode(&public_cert_pem);
    let req = test::TestRequest::post()
        .uri("/api/v1/auth/device")
        .insert_header(("X-Client-Certificate", encoded_pem.as_str()))
        .to_request();
    let resp = test::call_service(&app, req).await;
    assert_ne!(resp.status().as_u16(), 200);
}
