//! The browser login hop (W3, plan §4.0 "Gap 0").
//!
//! Until this wave `/oauth2/authorize` had no way to answer an anonymous
//! browser. It required an already-authenticated principal — the `axiam_access`
//! cookie or a `Bearer`/`DPoP` header — and answered anything else with a 401
//! JSON body. That is a dead end for a real relying party, because
//! `axiam_access` is `SameSite=Strict` and a cross-site top-level navigation
//! (which is precisely what an RP redirect is) never carries a Strict cookie.
//! Even a signed-in user arrived anonymous.
//!
//! The hop closes that: an anonymous request from a client registered
//! `browser_sso` is redirected to the admin SPA's `/login`, carrying a
//! `return_to` that names where to come back to. This module owns the two
//! decisions in that sentence which must be right — **what a `return_to` is
//! allowed to be**, and **why the hop terminates** — as pure functions, so they
//! are tested without an HTTP server and cannot be re-derived slightly
//! differently by a second caller.
//!
//! # What a `return_to` may be
//!
//! Exactly one shape: `/oauth2/authorize?` followed by a query string. Not a
//! URL, not a path the caller chose, not a prefix — the authorization endpoint,
//! with parameters, and nothing else. [`validate_return_to`] is where that is
//! decided, and it is applied **twice on the server** (once when the value is
//! built, once when the browser comes back with it) as well as in the SPA
//! before it navigates. The plan calls for validation "on both sides"; the
//! third check is free and closes the case where a `return_to` is stored,
//! logged or replayed between the two.
//!
//! Anything else is an open redirect. The interesting members of that family
//! are foreign origins (`https://evil.example/…`), scheme-relative values
//! (`//evil.example/…`, which a browser resolves to a *different host* while
//! looking like a path), backslash variants (`/\evil.example`, which several
//! browsers normalise to `//`), and traversal (`/oauth2/authorize/../../admin`).
//! All four are refused here, and the REST layer additionally resolves the
//! result against the deployment's own origin and re-checks it through
//! `require_deployment_spa_origin` — the same rule that already guards the
//! federation SSO handoff. That second check is redundant while this function
//! demands an exact path, and it is kept precisely because a future edit to
//! this function is the way that stops being true.
//!
//! # Why the hop terminates
//!
//! `authorize → /login → authorize` is a loop if the second `authorize` can
//! produce a third. It cannot, because of one rule with two halves:
//!
//! 1. every login redirect this server builds carries [`LOGIN_HOP_MARKER`] in
//!    its `return_to`; and
//! 2. an authorization request that **arrives** carrying that marker is never
//!    answered with a login redirect — if it still has no principal, it is
//!    answered with a terminal error.
//!
//! So along any chain of authorization requests generated by this server's own
//! redirects, at most one redirect is emitted: the first request has no marker
//! and may hop; the request that hop produces has one and may not. The chain is
//! two authorization requests and one login page, whatever goes wrong in
//! between — a cookie the browser refused to store, a login into the wrong
//! tenant, a session that expired between the two legs.
//!
//! The marker is in a URL and the user agent could strip it. That costs the
//! guard nothing: the loop it prevents is a loop in *that same browser*, so
//! removing the guard only harms whoever removed it, and no security decision
//! anywhere reads the marker. It selects an error message and the shape of a
//! response; it never selects a principal.
//!
//! # What W4 added to the marker, and why it is still not a security decision
//!
//! W3 read the marker in one place: an anonymous return leg is answered rather
//! than redirected again. W4's honour lane reads it in two more (see
//! [`crate::honour`]) — a requirement that survives one interaction is
//! answered rather than retried, and `prompt=none` on a request that has been
//! through the sign-in page is refused because the interaction it forbade has
//! happened.
//!
//! Both are still, exactly, "which of two truthful answers to give". A relying
//! party can forge the marker on its own authorization request, and the
//! strongest thing forging it achieves is that the server skips an interaction
//! *the forger asked for*: no principal changes, no claim is added, and
//! `auth_time`, `acr` and `amr` still describe the authentication that really
//! happened rather than the one the request wanted. A third party cannot forge
//! it into somebody else's request without already being able to write that
//! request, at which point it is the relying party.

use std::fmt;

/// The query parameter that marks an authorization request as the return leg
/// of a login hop.
///
/// `axiam_`-prefixed so it cannot collide with an OAuth2 or OpenID Connect
/// parameter now or later: the registries do not issue names in a vendor
/// namespace, and a relying party that sends this one is sending a parameter
/// AXIAM defines.
pub const LOGIN_HOP_MARKER: &str = "axiam_login_hop";

/// The only path a `return_to` may name.
pub const AUTHORIZE_PATH: &str = "/oauth2/authorize";

/// The SPA route the hop sends the browser to.
pub const LOGIN_PATH: &str = "/login";

/// Largest `return_to` this server will build or accept, in bytes.
///
/// An authorization request is a query string, and a `request_uri` one is
/// short; 4 KiB is generous for the inline form (nine OIDC parameters, a
/// `state`, a `nonce`, a PKCE challenge) and small enough that the redirect
/// stays inside every deployment's URL limits, since the value is carried
/// *inside* another URL and is therefore percent-encoded on the way.
pub const MAX_RETURN_TO_LEN: usize = 4096;

/// Why a candidate `return_to` was refused.
///
/// A typed reason rather than a bool because these are the open-redirect
/// family and each member has a distinct test; a caller that logs the variant
/// can tell "a client sent us something long" from "someone tried to send a
/// browser to another host".
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReturnToError {
    /// Longer than [`MAX_RETURN_TO_LEN`].
    TooLong,
    /// Contains a control character, whitespace, or a fragment.
    ///
    /// Whitespace and control characters are header-injection material; a
    /// fragment is not something a server builds and is invisible to the
    /// server that would have to validate what follows it.
    IllegalCharacter,
    /// Not a path at all: it does not begin with a single `/`.
    ///
    /// This is the arm that refuses `https://evil.example/…` and every other
    /// absolute form.
    NotAPath,
    /// Begins `//` or `/\` — a scheme-relative reference.
    ///
    /// It reads as a path and resolves to a different **host**. This is the
    /// member of the family that gets missed, which is why it has its own
    /// variant and its own test.
    SchemeRelative,
    /// A path other than exactly [`AUTHORIZE_PATH`], or one with no query.
    ///
    /// Traversal (`/oauth2/authorize/../../admin`) lands here rather than in a
    /// variant of its own: there is no normalisation step to defeat, because
    /// nothing but the exact path is accepted in the first place.
    NotTheAuthorizeEndpoint,
}

impl fmt::Display for ReturnToError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let msg = match self {
            Self::TooLong => "return_to is too long",
            Self::IllegalCharacter => "return_to contains an illegal character",
            Self::NotAPath => "return_to must be a path on this deployment",
            Self::SchemeRelative => "return_to must not be scheme-relative",
            Self::NotTheAuthorizeEndpoint => {
                "return_to must name the authorization endpoint with a query"
            }
        };
        f.write_str(msg)
    }
}

/// Is this a `return_to` the server built and will honour?
///
/// See the module docs for the shape and for why it is checked more than once.
/// The check is *total and syntactic*: it reads the candidate and nothing else,
/// so it gives the same answer on the way out (when the server builds the
/// value) as on the way back (when a browser presents one), which is the whole
/// property "validated on both sides" is worth having.
///
/// # Errors
///
/// [`ReturnToError`], naming which member of the open-redirect family the
/// candidate belongs to.
pub fn validate_return_to(candidate: &str) -> Result<(), ReturnToError> {
    if candidate.len() > MAX_RETURN_TO_LEN {
        return Err(ReturnToError::TooLong);
    }
    // A fragment is refused with the control characters: everything after `#`
    // never reaches the server that would have to validate it, so a value
    // carrying one is a value only half of which was checked.
    if candidate
        .chars()
        .any(|c| c.is_control() || c.is_whitespace() || c == '#' || c == '\\')
    {
        return Err(ReturnToError::IllegalCharacter);
    }
    let mut chars = candidate.chars();
    if chars.next() != Some('/') {
        return Err(ReturnToError::NotAPath);
    }
    // `/\` is already gone with the backslashes above; `//` is checked here so
    // the two scheme-relative spellings answer with the same variant.
    if chars.next() == Some('/') {
        return Err(ReturnToError::SchemeRelative);
    }

    let Some((path, query)) = candidate.split_once('?') else {
        return Err(ReturnToError::NotTheAuthorizeEndpoint);
    };
    if path != AUTHORIZE_PATH || query.is_empty() {
        return Err(ReturnToError::NotTheAuthorizeEndpoint);
    }
    Ok(())
}

/// Build the `return_to` for an authorization request whose raw query string is
/// `query`.
///
/// The result carries [`LOGIN_HOP_MARKER`], which is what makes the hop
/// terminate (module docs). It is validated before it is returned, so a caller
/// cannot emit a `Location` this module would refuse to accept back — the two
/// directions are the same predicate by construction rather than by review.
///
/// `None` when the query is empty or the result would not validate. A caller
/// that gets `None` must not redirect: there is nothing safe to come back to.
pub fn build_return_to(query: &str) -> Option<String> {
    if query.is_empty() {
        return None;
    }
    let candidate = format!("{AUTHORIZE_PATH}?{query}&{LOGIN_HOP_MARKER}=1");
    validate_return_to(&candidate).ok()?;
    Some(candidate)
}

/// Build the `Location` that sends the browser to the SPA login page.
///
/// Relative on purpose. The SPA and the API are one origin in every shipped
/// topology (`docker/nginx.conf`, and the `baseURL: "/"` the admin UI is built
/// with), and they must be for this feature at all: `return_to` is a path on
/// the **API's** origin, and the `axiam_op_session` cookie the login sets is
/// scoped to `/oauth2/authorize` on that same origin. A deployment serving the
/// SPA from another host cannot complete this hop, and emitting an absolute URL
/// would hide that rather than fix it.
///
/// `reauth` asks the SPA to authenticate the user afresh rather than reuse
/// whatever it already holds. W3 sets it in exactly one case — a browser
/// arriving with an `axiam_op_session` cookie that resolves to no live session —
/// because that browser believes it is signed in and is not, and sending it to
/// a login page that might agree with it is how a hop becomes a loop the guard
/// then has to catch.
pub fn build_login_redirect(return_to: &str, reauth: bool) -> String {
    build_login_redirect_for(return_to, reauth, None)
}

/// [`build_login_redirect`], plus the one factor the sign-in page must demand
/// (W4, plan §4.4).
///
/// `required_acr` is a member of the closed two-value vocabulary
/// ([`crate::acr::Acr`]) and nothing else can be passed, which is the whole
/// design of the step-up: **the page never chooses an authentication context
/// class.** It learns which factor to insist on, from an allow-list of two,
/// and the class the resulting session earns is derived afterwards from what
/// the session actually proves ([`crate::acr::acr_for`]). A `String` parameter
/// here would be the first place an operator-chosen or relying-party-chosen
/// ACR could reach a user-facing page, and from there the temptation to echo
/// it into the claim is one refactor away.
///
/// A step-up is always a `reauth` in practice — the point is to authenticate
/// afresh — but the two are separate parameters because they answer different
/// questions: `reauth` says *do not trust what this browser already holds*,
/// and `acr` says *what to ask it for*.
pub fn build_login_redirect_for(
    return_to: &str,
    reauth: bool,
    required_acr: Option<crate::acr::Acr>,
) -> String {
    let encoded: String = url::form_urlencoded::byte_serialize(return_to.as_bytes()).collect();
    let mut location = format!("{LOGIN_PATH}?return_to={encoded}");
    if reauth {
        location.push_str("&reauth=1");
    }
    if let Some(acr) = required_acr {
        let value: String = url::form_urlencoded::byte_serialize(acr.as_str().as_bytes()).collect();
        location.push_str("&acr=");
        location.push_str(&value);
    }
    location
}

/// Is this authorization request the return leg of a hop this server started?
///
/// The half of the termination rule that reads. Any present value counts, not
/// only `1`: the guard's job is to stop a second redirect, and a caller who
/// sent `axiam_login_hop=0` has still been here before.
pub fn is_return_leg(marker: Option<&str>) -> bool {
    marker.is_some()
}

#[cfg(test)]
mod tests {
    use super::*;

    const GOOD: &str = "/oauth2/authorize?response_type=code&client_id=oa_1&\
                        redirect_uri=https%3A%2F%2Frp.example%2Fcb";

    #[test]
    fn the_shape_the_server_builds_is_the_shape_it_accepts() {
        assert_eq!(validate_return_to(GOOD), Ok(()));
        let built = build_return_to("response_type=code&client_id=oa_1").expect("a return_to");
        assert_eq!(validate_return_to(&built), Ok(()));
        assert!(
            built.contains(&format!("{LOGIN_HOP_MARKER}=1")),
            "every built return_to carries the loop guard's marker: {built}"
        );
    }

    /// T0.3 — the open-redirect family, one case per member.
    #[test]
    fn every_open_redirect_shape_is_refused() {
        for (candidate, expected) in [
            // A foreign origin, spelled out.
            (
                "https://evil.example/oauth2/authorize?x=1",
                ReturnToError::NotAPath,
            ),
            (
                "http://evil.example/oauth2/authorize?x=1",
                ReturnToError::NotAPath,
            ),
            // Same, without a scheme the eye can catch.
            (
                "//evil.example/oauth2/authorize?x=1",
                ReturnToError::SchemeRelative,
            ),
            // The backslash spellings browsers normalise to `//`.
            (
                "/\\evil.example/oauth2/authorize?x=1",
                ReturnToError::IllegalCharacter,
            ),
            ("\\\\evil.example", ReturnToError::IllegalCharacter),
            // Traversal out of the endpoint.
            (
                "/oauth2/authorize/../../admin/users?x=1",
                ReturnToError::NotTheAuthorizeEndpoint,
            ),
            // A same-origin path the deployment did not allow.
            ("/api/v1/users?x=1", ReturnToError::NotTheAuthorizeEndpoint),
            (
                "/login?return_to=%2F",
                ReturnToError::NotTheAuthorizeEndpoint,
            ),
            // A prefix that merely starts the same way.
            (
                "/oauth2/authorize_evil?x=1",
                ReturnToError::NotTheAuthorizeEndpoint,
            ),
            // The right path with nothing to authorize.
            ("/oauth2/authorize", ReturnToError::NotTheAuthorizeEndpoint),
            ("/oauth2/authorize?", ReturnToError::NotTheAuthorizeEndpoint),
            // Header injection and a fragment that hides the rest of the value.
            (
                "/oauth2/authorize?x=1\r\nSet-Cookie: a=b",
                ReturnToError::IllegalCharacter,
            ),
            (
                "/oauth2/authorize?x=1#@evil.example",
                ReturnToError::IllegalCharacter,
            ),
            // Not a path at all.
            ("oauth2/authorize?x=1", ReturnToError::NotAPath),
            ("", ReturnToError::NotAPath),
        ] {
            assert_eq!(
                validate_return_to(candidate),
                Err(expected),
                "must refuse {candidate:?}"
            );
        }
    }

    #[test]
    fn an_oversized_return_to_is_refused_before_anything_else_is_read() {
        let long = format!("/oauth2/authorize?x={}", "a".repeat(MAX_RETURN_TO_LEN));
        assert_eq!(validate_return_to(&long), Err(ReturnToError::TooLong));
        assert_eq!(
            build_return_to(&format!("x={}", "a".repeat(MAX_RETURN_TO_LEN))),
            None
        );
    }

    /// A builder that cannot emit a value the validator would refuse is the
    /// reason "validated on both sides" is a property rather than a habit.
    #[test]
    fn the_builder_refuses_a_query_that_would_produce_an_unacceptable_value() {
        assert_eq!(build_return_to(""), None);
        assert_eq!(build_return_to("state=a b"), None, "whitespace");
        assert_eq!(build_return_to("state=a#b"), None, "fragment");
        assert_eq!(build_return_to("state=a\\b"), None, "backslash");
    }

    #[test]
    fn the_login_redirect_is_a_same_origin_path_with_an_encoded_return_to() {
        let location = build_login_redirect(GOOD, false);
        assert!(
            location.starts_with("/login?return_to="),
            "the login redirect must stay on this origin: {location}"
        );
        assert!(!location.contains("&reauth"), "reauth was not asked for");
        // The `return_to` must survive as one parameter: an unencoded `&`
        // inside it would split into parameters the SPA reads separately.
        assert!(
            !location["/login?return_to=".len()..].contains('&'),
            "return_to must be percent-encoded into a single parameter: {location}"
        );

        let reauth = build_login_redirect(GOOD, true);
        assert!(reauth.ends_with("&reauth=1"), "{reauth}");
    }

    /// **W4.** The step-up redirect names one factor, from the closed
    /// vocabulary, percent-encoded so the URN's colons cannot be read as
    /// anything else. `reauth` and `acr` are independent parameters.
    #[test]
    fn a_step_up_redirect_names_the_factor_the_page_must_demand() {
        let location = build_login_redirect_for(GOOD, true, Some(crate::acr::Acr::MultiFactor));
        assert!(location.starts_with("/login?return_to="), "{location}");
        assert!(location.contains("&reauth=1"), "{location}");
        assert!(
            location.ends_with("&acr=urn%3Aaxiam%3Aacr%3Amfa"),
            "the factor must be percent-encoded: {location}"
        );

        // The W3 shape is exactly what it was: no `acr`, byte for byte.
        assert_eq!(
            build_login_redirect_for(GOOD, true, None),
            build_login_redirect(GOOD, true),
        );
        assert_eq!(
            build_login_redirect_for(GOOD, false, None),
            build_login_redirect(GOOD, false),
        );
    }

    /// The loop guard, stated as the property the module docs argue: a request
    /// carrying the marker is a return leg, and the server never builds a
    /// second redirect for one.
    #[test]
    fn the_marker_makes_the_second_leg_recognisable() {
        assert!(!is_return_leg(None));
        assert!(is_return_leg(Some("1")));
        assert!(
            is_return_leg(Some("0")),
            "presence is what the guard reads; a caller who sent 0 has still been here"
        );
        assert!(is_return_leg(Some("")));
    }
}
