//! The browser login hop (W3, plan §4.0 "Gap 0").
//!
//! Until this wave `/oauth2/authorize` had no way to answer an anonymous
//! browser. It required an already-authenticated principal — the `axiam_access`
//! cookie or a `Bearer`/`DPoP` header — and answered anything else with a 401
//! JSON body. That is a dead end for a real relying party, because
//! `axiam_access` is `SameSite=Strict` and a cross-site top-level navigation
//! (which is precisely what an RP redirect is) never carries a Strict cookie.
//! Even a signed-in user arrived anonymous.
//!
//! The hop closes that: an anonymous request from a client registered
//! `browser_sso` is redirected to the admin SPA's `/login`, carrying a
//! `return_to` that names where to come back to. This module owns the two
//! decisions in that sentence which must be right — **what a `return_to` is
//! allowed to be**, and **why the hop terminates** — as pure functions, so they
//! are tested without an HTTP server and cannot be re-derived slightly
//! differently by a second caller.
//!
//! # What a `return_to` may be
//!
//! Exactly one shape: `/oauth2/authorize?` followed by a query string. Not a
//! URL, not a path the caller chose, not a prefix — the authorization endpoint,
//! with parameters, and nothing else. [`validate_return_to`] is where that is
//! decided, and it is applied **twice on the server** (once when the value is
//! built, once when the browser comes back with it) as well as in the SPA
//! before it navigates. The plan calls for validation "on both sides"; the
//! third check is free and closes the case where a `return_to` is stored,
//! logged or replayed between the two.
//!
//! Anything else is an open redirect. The interesting members of that family
//! are foreign origins (`https://evil.example/…`), scheme-relative values
//! (`//evil.example/…`, which a browser resolves to a *different host* while
//! looking like a path), backslash variants (`/\evil.example`, which several
//! browsers normalise to `//`), and traversal (`/oauth2/authorize/../../admin`).
//! All four are refused here, and the REST layer additionally resolves the
//! result against the deployment's own origin and re-checks it through
//! `require_deployment_spa_origin` — the same rule that already guards the
//! federation SSO handoff. That second check is redundant while this function
//! demands an exact path, and it is kept precisely because a future edit to
//! this function is the way that stops being true.
//!
//! # Why the hop terminates
//!
//! `authorize → /login → authorize` is a loop if the second `authorize` can
//! produce a third. It cannot, because of one rule with two halves:
//!
//! 1. every login redirect this server builds carries [`LOGIN_HOP_MARKER`] in
//!    its `return_to`; and
//! 2. an authorization request that **arrives** carrying that marker is never
//!    answered with a login redirect — if it still has no principal, it is
//!    answered with a terminal error.
//!
//! So along any chain of authorization requests generated by this server's own
//! redirects, at most one redirect is emitted: the first request has no marker
//! and may hop; the request that hop produces has one and may not. The chain is
//! two authorization requests and one login page, whatever goes wrong in
//! between — a cookie the browser refused to store, a login into the wrong
//! tenant, a session that expired between the two legs.
//!
//! The marker is in a URL and the user agent could strip it. That costs the
//! guard nothing: the loop it prevents is a loop in *that same browser*, so
//! removing the guard only harms whoever removed it, and no security decision
//! anywhere reads the marker. It selects an error message and the shape of a
//! response; it never selects a principal.
//!
//! # What W4 added to the marker, and why it is still not a security decision
//!
//! W3 read the marker in one place: an anonymous return leg is answered rather
//! than redirected again. W4's honour lane reads it in two more (see
//! [`crate::honour`]) — a requirement that survives one interaction is
//! answered rather than retried, and `prompt=none` on a request that has been
//! through the sign-in page is refused because the interaction it forbade has
//! happened.
//!
//! Both are still, exactly, "which of two truthful answers to give". A relying
//! party can forge the marker on its own authorization request, and the
//! strongest thing forging it achieves is that the server skips an interaction
//! *the forger asked for*: no principal changes, no claim is added, and
//! `auth_time`, `acr` and `amr` still describe the authentication that really
//! happened rather than the one the request wanted. A third party cannot forge
//! it into somebody else's request without already being able to write that
//! request, at which point it is the relying party.
//!
//! # What W5 adds, and why it is all allow-listed types
//!
//! W5 lets the sign-in page be *presented* the way the relying party asked:
//! a pre-filled username (`login_hint`), a compact layout (`display`) and a
//! language (`ui_locales`). All three arrive as relying-party-controlled
//! strings and all three end up on a page a human types a password into, so
//! the rule for this module is the one W4 set for `acr`: **what crosses into
//! the URL is a type, not a string**, wherever a closed set exists.
//!
//! Two of the three have one — [`crate::locale::Locale`] and
//! [`crate::locale::Display`] — and are matched on the server, so the raw
//! `ui_locales` and `display` values never reach the SPA at all. The third,
//! `login_hint`, has no closed set by definition: it is whatever identifier
//! the relying party believes the user types. It is carried verbatim, and the
//! two things that make that safe are stated where they are decided rather
//! than here — the parser bounds it to
//! [`crate::authn_params::MAX_HINT_LEN`] bytes and drops it if it fails to
//! parse as UTF-8, and [`Cosmetic::login_hint`] documents the property that
//! actually matters: **no server-side lookup is ever performed on it.**

use std::fmt;

/// The query parameter that marks an authorization request as the return leg
/// of a login hop.
///
/// `axiam_`-prefixed so it cannot collide with an OAuth2 or OpenID Connect
/// parameter now or later: the registries do not issue names in a vendor
/// namespace, and a relying party that sends this one is sending a parameter
/// AXIAM defines.
pub const LOGIN_HOP_MARKER: &str = "axiam_login_hop";

/// The only path a `return_to` may name.
pub const AUTHORIZE_PATH: &str = "/oauth2/authorize";

/// The SPA route the hop sends the browser to.
pub const LOGIN_PATH: &str = "/login";

/// Largest `return_to` this server will build or accept, in bytes.
///
/// An authorization request is a query string, and a `request_uri` one is
/// short; 4 KiB is generous for the inline form (nine OIDC parameters, a
/// `state`, a `nonce`, a PKCE challenge) and small enough that the redirect
/// stays inside every deployment's URL limits, since the value is carried
/// *inside* another URL and is therefore percent-encoded on the way.
pub const MAX_RETURN_TO_LEN: usize = 4096;

/// Why a candidate `return_to` was refused.
///
/// A typed reason rather than a bool because these are the open-redirect
/// family and each member has a distinct test; a caller that logs the variant
/// can tell "a client sent us something long" from "someone tried to send a
/// browser to another host".
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReturnToError {
    /// Longer than [`MAX_RETURN_TO_LEN`].
    TooLong,
    /// Contains a control character, whitespace, or a fragment.
    ///
    /// Whitespace and control characters are header-injection material; a
    /// fragment is not something a server builds and is invisible to the
    /// server that would have to validate what follows it.
    IllegalCharacter,
    /// Not a path at all: it does not begin with a single `/`.
    ///
    /// This is the arm that refuses `https://evil.example/…` and every other
    /// absolute form.
    NotAPath,
    /// Begins `//` or `/\` — a scheme-relative reference.
    ///
    /// It reads as a path and resolves to a different **host**. This is the
    /// member of the family that gets missed, which is why it has its own
    /// variant and its own test.
    SchemeRelative,
    /// A path other than exactly [`AUTHORIZE_PATH`], or one with no query.
    ///
    /// Traversal (`/oauth2/authorize/../../admin`) lands here rather than in a
    /// variant of its own: there is no normalisation step to defeat, because
    /// nothing but the exact path is accepted in the first place.
    NotTheAuthorizeEndpoint,
}

impl fmt::Display for ReturnToError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let msg = match self {
            Self::TooLong => "return_to is too long",
            Self::IllegalCharacter => "return_to contains an illegal character",
            Self::NotAPath => "return_to must be a path on this deployment",
            Self::SchemeRelative => "return_to must not be scheme-relative",
            Self::NotTheAuthorizeEndpoint => {
                "return_to must name the authorization endpoint with a query"
            }
        };
        f.write_str(msg)
    }
}

/// Is this a `return_to` the server built and will honour?
///
/// See the module docs for the shape and for why it is checked more than once.
/// The check is *total and syntactic*: it reads the candidate and nothing else,
/// so it gives the same answer on the way out (when the server builds the
/// value) as on the way back (when a browser presents one), which is the whole
/// property "validated on both sides" is worth having.
///
/// # Errors
///
/// [`ReturnToError`], naming which member of the open-redirect family the
/// candidate belongs to.
pub fn validate_return_to(candidate: &str) -> Result<(), ReturnToError> {
    if candidate.len() > MAX_RETURN_TO_LEN {
        return Err(ReturnToError::TooLong);
    }
    // A fragment is refused with the control characters: everything after `#`
    // never reaches the server that would have to validate it, so a value
    // carrying one is a value only half of which was checked.
    if candidate
        .chars()
        .any(|c| c.is_control() || c.is_whitespace() || c == '#' || c == '\\')
    {
        return Err(ReturnToError::IllegalCharacter);
    }
    let mut chars = candidate.chars();
    if chars.next() != Some('/') {
        return Err(ReturnToError::NotAPath);
    }
    // `/\` is already gone with the backslashes above; `//` is checked here so
    // the two scheme-relative spellings answer with the same variant.
    if chars.next() == Some('/') {
        return Err(ReturnToError::SchemeRelative);
    }

    let Some((path, query)) = candidate.split_once('?') else {
        return Err(ReturnToError::NotTheAuthorizeEndpoint);
    };
    if path != AUTHORIZE_PATH || query.is_empty() {
        return Err(ReturnToError::NotTheAuthorizeEndpoint);
    }
    Ok(())
}

/// Build the `return_to` for an authorization request whose raw query string is
/// `query`.
///
/// The result carries [`LOGIN_HOP_MARKER`], which is what makes the hop
/// terminate (module docs). It is validated before it is returned, so a caller
/// cannot emit a `Location` this module would refuse to accept back — the two
/// directions are the same predicate by construction rather than by review.
///
/// `None` when the query is empty or the result would not validate. A caller
/// that gets `None` must not redirect: there is nothing safe to come back to.
pub fn build_return_to(query: &str) -> Option<String> {
    if query.is_empty() {
        return None;
    }
    let candidate = format!("{AUTHORIZE_PATH}?{query}&{LOGIN_HOP_MARKER}=1");
    validate_return_to(&candidate).ok()?;
    Some(candidate)
}

/// Build the `Location` that sends the browser to the SPA login page.
///
/// Relative on purpose. The SPA and the API are one origin in every shipped
/// topology (`docker/nginx.conf`, and the `baseURL: "/"` the admin UI is built
/// with), and they must be for this feature at all: `return_to` is a path on
/// the **API's** origin, and the `axiam_op_session` cookie the login sets is
/// scoped to `/oauth2/authorize` on that same origin. A deployment serving the
/// SPA from another host cannot complete this hop, and emitting an absolute URL
/// would hide that rather than fix it.
///
/// `reauth` asks the SPA to authenticate the user afresh rather than reuse
/// whatever it already holds. W3 sets it in exactly one case — a browser
/// arriving with an `axiam_op_session` cookie that resolves to no live session —
/// because that browser believes it is signed in and is not, and sending it to
/// a login page that might agree with it is how a hop becomes a loop the guard
/// then has to catch.
pub fn build_login_redirect(return_to: &str, reauth: bool) -> String {
    build_login_redirect_for(return_to, reauth, None, &Cosmetic::NONE)
}

/// The presentation an authorization request asked the sign-in page for
/// (W5, plan §4.5/§4.6).
///
/// A struct rather than three more positional arguments on
/// [`build_login_redirect_for`], which would otherwise take six — two of them
/// `Option`s a transposed call site would still compile with.
///
/// [`Cosmetic::NONE`] is what every request that asked for nothing produces,
/// and it is the value the *ignore* lane always passes: a client registered
/// today gets a `/login` URL byte-identical to the one W3 and W4 built, which
/// is invariant 4 for this wave.
#[derive(Debug, Clone, Copy, Default)]
pub struct Cosmetic<'a> {
    /// The relying party's guess at the identifier the end user will type, to
    /// be pre-filled into the username field.
    ///
    /// **The server performs no lookup on this value, on any path.** It is
    /// never compared to a user, never used to select a session or a tenant,
    /// and it is not read at all when a session already exists — the only
    /// place it is used is here, building a URL for a page that is being shown
    /// anyway.
    ///
    /// That is the enumeration mitigation the plan asks for, and it is worth
    /// being precise about *why* it is the strong form. The weak form of this
    /// defence looks up the hint, finds the account or does not, and then
    /// takes care to answer identically either way. It is one refactor away
    /// from a timing difference, an audit row, a cache entry or an error
    /// message that distinguishes the two — because the two branches exist and
    /// something has to keep them equal. Here there is no branch: the value is
    /// percent-encoded into a `Location` header and nothing else in this
    /// server ever reads it. Test **T5.1** asserts the responses for an
    /// existing and a non-existing hint are byte-identical apart from the
    /// echoed parameter, and it is asserting a property of the shape of the
    /// code rather than of anybody's diligence.
    ///
    /// Already bounded to [`crate::authn_params::MAX_HINT_LEN`] bytes and
    /// known to be valid UTF-8 by the time it arrives here: it comes from
    /// [`crate::authn_params::AuthnRequestParams`], which drops an over-long
    /// value rather than truncating it.
    pub login_hint: Option<&'a str>,
    /// The layout the relying party asked for, already allow-listed.
    pub display: Option<crate::locale::Display>,
    /// The language the sign-in page should render in — **the selected one**,
    /// not the `ui_locales` list that selected it.
    ///
    /// The matching happens in [`crate::locale::select_ui_locale`] precisely so
    /// that this field can be a five-value enum. See that module for why the
    /// raw value must never reach the SPA.
    pub ui_locale: Option<crate::locale::Locale>,
}

impl Cosmetic<'_> {
    /// A request that asked for no particular presentation — and the value the
    /// ignore lane always uses.
    pub const NONE: Self = Self {
        login_hint: None,
        display: None,
        ui_locale: None,
    };

    /// Whether anything at all was asked for.
    pub const fn is_empty(&self) -> bool {
        self.login_hint.is_none() && self.display.is_none() && self.ui_locale.is_none()
    }
}

impl<'a> Cosmetic<'a> {
    /// Assemble the presentation from a parsed request, on the honour lane.
    ///
    /// This is the **only** function that turns
    /// [`crate::authn_params::AuthnRequestParams`] into something a URL builder
    /// accepts, and it exists so that three properties are readable in one
    /// place instead of being spread across two call sites in the REST layer:
    ///
    /// 1. `display` and `ui_locales` are *matched here* and forwarded as
    ///    types, so the raw values stop at this function (T6.2).
    /// 2. `login_hint` is forwarded verbatim and nothing looks it up (T5.1;
    ///    see [`Cosmetic::login_hint`]).
    /// 3. **`claims_locales` is not read.** It has no field on [`Cosmetic`],
    ///    it is not a parameter of this function, and `select_ui_locale` is
    ///    called with `params.ui_locales` at exactly one call site — this one.
    ///
    /// That third property is the one worth a paragraph. `claims_locales` and
    /// `ui_locales` are adjacent in OIDC Core §3.1.2.1, carry the same BCP 47
    /// syntax, and differ by a prefix; one selects the language of the *page*
    /// and the other the language of *claim values*, of which AXIAM has none.
    /// A future edit reaching for "the locale the relying party asked for"
    /// could reach for either and look right in review. Having exactly one
    /// call site — pinned by a test that `claims_locales=it` alone leaves the
    /// page in the deployment default — is what makes the wrong one visible.
    ///
    /// `tenant_default` is the tenant's configured language, already parsed;
    /// it is consulted only when the relying party asked for nothing this
    /// deployment ships.
    pub fn from_params(
        params: &'a crate::authn_params::AuthnRequestParams,
        tenant_default: Option<crate::locale::Locale>,
    ) -> Self {
        Self {
            login_hint: params.login_hint.as_deref(),
            display: params
                .display
                .as_deref()
                .and_then(crate::locale::Display::from_wire),
            ui_locale: crate::locale::select_ui_locale(
                params.ui_locales.as_deref(),
                tenant_default,
            ),
        }
    }
}

/// [`build_login_redirect`], plus the one factor the sign-in page must demand
/// (W4, plan §4.4) and the presentation it was asked for (W5, plan §4.5/§4.6).
///
/// `required_acr` is a member of the closed two-value vocabulary
/// ([`crate::acr::Acr`]) and nothing else can be passed, which is the whole
/// design of the step-up: **the page never chooses an authentication context
/// class.** It learns which factor to insist on, from an allow-list of two,
/// and the class the resulting session earns is derived afterwards from what
/// the session actually proves ([`crate::acr::acr_for`]). A `String` parameter
/// here would be the first place an operator-chosen or relying-party-chosen
/// ACR could reach a user-facing page, and from there the temptation to echo
/// it into the claim is one refactor away.
///
/// A step-up is always a `reauth` in practice — the point is to authenticate
/// afresh — but the two are separate parameters because they answer different
/// questions: `reauth` says *do not trust what this browser already holds*,
/// and `acr` says *what to ask it for*.
///
/// `cosmetic` follows the same rule for the same reason (see [`Cosmetic`]).
/// Passing [`Cosmetic::NONE`] reproduces the W3/W4 URL byte for byte, which is
/// what the ignore lane does and what its test asserts.
///
/// This is the **only** place a `/login` URL is built. Keeping it that way is
/// what makes "the raw `ui_locales` appears in no redirect the server builds"
/// (T6.2) a claim about one function rather than a claim about the tree.
pub fn build_login_redirect_for(
    return_to: &str,
    reauth: bool,
    required_acr: Option<crate::acr::Acr>,
    cosmetic: &Cosmetic<'_>,
) -> String {
    let mut location = format!("{LOGIN_PATH}?return_to={}", encode(return_to));
    if reauth {
        location.push_str("&reauth=1");
    }
    if let Some(acr) = required_acr {
        location.push_str("&acr=");
        location.push_str(&encode(acr.as_str()));
    }
    // W5. `login_hint` is the only one of the three that is not a type, so it
    // is the only one that is encoded rather than merely written; the other
    // two can emit nothing but short lower-case ASCII identifiers and are
    // encoded anyway, because a builder that treats its inputs differently
    // depending on how much it trusts them is one whose next parameter gets
    // the wrong treatment.
    if let Some(hint) = cosmetic.login_hint {
        location.push_str("&login_hint=");
        location.push_str(&encode(hint));
    }
    if let Some(display) = cosmetic.display {
        location.push_str("&display=");
        location.push_str(&encode(display.as_str()));
    }
    if let Some(locale) = cosmetic.ui_locale {
        location.push_str("&ui_locale=");
        location.push_str(&encode(locale.as_tag()));
    }
    location
}

/// The SPA route that asks the end user to consent to a scope release (W7).
///
/// A sibling of [`LOGIN_PATH`] rather than a query flag on it, because the two
/// pages ask different questions of a different person-state: `/login` asks an
/// anonymous browser to prove who it is, `/consent` asks a signed-in person
/// what they are willing to hand over. Conflating them is how a consent
/// ceremony turns into "type your password again", which is a dark pattern
/// whatever the specification says.
pub const CONSENT_PATH: &str = "/consent";

/// Build the redirect for an interaction the authorization endpoint asked for.
///
/// The one place either first-party page's URL is chosen, so that "which page,
/// with which flags" is a single exhaustive decision rather than a condition
/// the two call sites could answer differently.
///
/// # `/login` — every reason but one
///
/// Byte-identical to what [`build_login_redirect_for`] built for W4 and W5:
/// `reauth=1`, the required `acr` when there is one, and the full cosmetic
/// presentation. This is the path invariant 4's golden tests pin.
///
/// # `/consent` — [`crate::honour::Reason::ConsentRequired`]
///
/// No `reauth`, because the end user is authenticated and re-authenticating
/// answers no question about consent. No `acr`, because the sign-in ceremony
/// is not being repeated and naming a factor for a page that will not run one
/// would be telling it something untrue.
///
/// And no `login_hint`: it is a guess at the identifier somebody is about to
/// type, and on this page nobody is about to type one. Dropping it is not
/// tidiness — it is the difference between a relying party's opaque string
/// reaching a page that renders it into a form field and it reaching no page
/// at all. `display` and `ui_locale` are kept, because how to render and in
/// which language are questions the consent page really does have to answer,
/// and both are closed vocabularies (`crate::authn_params::Display`,
/// `crate::locale::Locale`) rather than relying-party strings.
pub fn build_interaction_redirect(
    return_to: &str,
    reason: crate::honour::Reason,
    required_acr: Option<crate::acr::Acr>,
    cosmetic: &Cosmetic<'_>,
) -> String {
    if reason.requires_reauthentication() {
        return build_login_redirect_for(return_to, true, required_acr, cosmetic);
    }
    let mut location = format!("{CONSENT_PATH}?return_to={}", encode(return_to));
    if let Some(display) = cosmetic.display {
        location.push_str("&display=");
        location.push_str(&encode(display.as_str()));
    }
    if let Some(locale) = cosmetic.ui_locale {
        location.push_str("&ui_locale=");
        location.push_str(&encode(locale.as_tag()));
    }
    location
}

/// Percent-encode one query-parameter value.
///
/// `byte_serialize` rather than a hand-rolled escape: it is the encoder the
/// SPA's `URLSearchParams` is the decoder for, and the two have to agree about
/// `+`, `&`, `=` and every non-ASCII byte of a `login_hint` that is somebody's
/// name.
fn encode(value: &str) -> String {
    url::form_urlencoded::byte_serialize(value.as_bytes()).collect()
}

/// Is this authorization request the return leg of a hop this server started?
///
/// The half of the termination rule that reads. Any present value counts, not
/// only `1`: the guard's job is to stop a second redirect, and a caller who
/// sent `axiam_login_hop=0` has still been here before.
pub fn is_return_leg(marker: Option<&str>) -> bool {
    marker.is_some()
}

#[cfg(test)]
mod tests {
    use super::*;

    const GOOD: &str = "/oauth2/authorize?response_type=code&client_id=oa_1&\
                        redirect_uri=https%3A%2F%2Frp.example%2Fcb";

    #[test]
    fn the_shape_the_server_builds_is_the_shape_it_accepts() {
        assert_eq!(validate_return_to(GOOD), Ok(()));
        let built = build_return_to("response_type=code&client_id=oa_1").expect("a return_to");
        assert_eq!(validate_return_to(&built), Ok(()));
        assert!(
            built.contains(&format!("{LOGIN_HOP_MARKER}=1")),
            "every built return_to carries the loop guard's marker: {built}"
        );
    }

    /// T0.3 — the open-redirect family, one case per member.
    #[test]
    fn every_open_redirect_shape_is_refused() {
        for (candidate, expected) in [
            // A foreign origin, spelled out.
            (
                "https://evil.example/oauth2/authorize?x=1",
                ReturnToError::NotAPath,
            ),
            (
                "http://evil.example/oauth2/authorize?x=1",
                ReturnToError::NotAPath,
            ),
            // Same, without a scheme the eye can catch.
            (
                "//evil.example/oauth2/authorize?x=1",
                ReturnToError::SchemeRelative,
            ),
            // The backslash spellings browsers normalise to `//`.
            (
                "/\\evil.example/oauth2/authorize?x=1",
                ReturnToError::IllegalCharacter,
            ),
            ("\\\\evil.example", ReturnToError::IllegalCharacter),
            // Traversal out of the endpoint.
            (
                "/oauth2/authorize/../../admin/users?x=1",
                ReturnToError::NotTheAuthorizeEndpoint,
            ),
            // A same-origin path the deployment did not allow.
            ("/api/v1/users?x=1", ReturnToError::NotTheAuthorizeEndpoint),
            (
                "/login?return_to=%2F",
                ReturnToError::NotTheAuthorizeEndpoint,
            ),
            // A prefix that merely starts the same way.
            (
                "/oauth2/authorize_evil?x=1",
                ReturnToError::NotTheAuthorizeEndpoint,
            ),
            // The right path with nothing to authorize.
            ("/oauth2/authorize", ReturnToError::NotTheAuthorizeEndpoint),
            ("/oauth2/authorize?", ReturnToError::NotTheAuthorizeEndpoint),
            // Header injection and a fragment that hides the rest of the value.
            (
                "/oauth2/authorize?x=1\r\nSet-Cookie: a=b",
                ReturnToError::IllegalCharacter,
            ),
            (
                "/oauth2/authorize?x=1#@evil.example",
                ReturnToError::IllegalCharacter,
            ),
            // Not a path at all.
            ("oauth2/authorize?x=1", ReturnToError::NotAPath),
            ("", ReturnToError::NotAPath),
        ] {
            assert_eq!(
                validate_return_to(candidate),
                Err(expected),
                "must refuse {candidate:?}"
            );
        }
    }

    #[test]
    fn an_oversized_return_to_is_refused_before_anything_else_is_read() {
        let long = format!("/oauth2/authorize?x={}", "a".repeat(MAX_RETURN_TO_LEN));
        assert_eq!(validate_return_to(&long), Err(ReturnToError::TooLong));
        assert_eq!(
            build_return_to(&format!("x={}", "a".repeat(MAX_RETURN_TO_LEN))),
            None
        );
    }

    /// A builder that cannot emit a value the validator would refuse is the
    /// reason "validated on both sides" is a property rather than a habit.
    #[test]
    fn the_builder_refuses_a_query_that_would_produce_an_unacceptable_value() {
        assert_eq!(build_return_to(""), None);
        assert_eq!(build_return_to("state=a b"), None, "whitespace");
        assert_eq!(build_return_to("state=a#b"), None, "fragment");
        assert_eq!(build_return_to("state=a\\b"), None, "backslash");
    }

    #[test]
    fn the_login_redirect_is_a_same_origin_path_with_an_encoded_return_to() {
        let location = build_login_redirect(GOOD, false);
        assert!(
            location.starts_with("/login?return_to="),
            "the login redirect must stay on this origin: {location}"
        );
        assert!(!location.contains("&reauth"), "reauth was not asked for");
        // The `return_to` must survive as one parameter: an unencoded `&`
        // inside it would split into parameters the SPA reads separately.
        assert!(
            !location["/login?return_to=".len()..].contains('&'),
            "return_to must be percent-encoded into a single parameter: {location}"
        );

        let reauth = build_login_redirect(GOOD, true);
        assert!(reauth.ends_with("&reauth=1"), "{reauth}");
    }

    /// **W4.** The step-up redirect names one factor, from the closed
    /// vocabulary, percent-encoded so the URN's colons cannot be read as
    /// anything else. `reauth` and `acr` are independent parameters.
    #[test]
    fn a_step_up_redirect_names_the_factor_the_page_must_demand() {
        let location = build_login_redirect_for(
            GOOD,
            true,
            Some(crate::acr::Acr::MultiFactor),
            &Cosmetic::NONE,
        );
        assert!(location.starts_with("/login?return_to="), "{location}");
        assert!(location.contains("&reauth=1"), "{location}");
        assert!(
            location.ends_with("&acr=urn%3Aaxiam%3Aacr%3Amfa"),
            "the factor must be percent-encoded: {location}"
        );

        // The W3 shape is exactly what it was: no `acr`, byte for byte.
        assert_eq!(
            build_login_redirect_for(GOOD, true, None, &Cosmetic::NONE),
            build_login_redirect(GOOD, true),
        );
        assert_eq!(
            build_login_redirect_for(GOOD, false, None, &Cosmetic::NONE),
            build_login_redirect(GOOD, false),
        );
    }

    /// **W5, invariant 4.** A request that asked for no presentation produces
    /// exactly the URL W3 and W4 produced — which is what the ignore lane
    /// always does, since it never assembles anything but [`Cosmetic::NONE`].
    #[test]
    fn a_request_that_asked_for_no_presentation_builds_the_w4_url_byte_for_byte() {
        assert!(Cosmetic::NONE.is_empty());
        assert!(Cosmetic::default().is_empty());
        for reauth in [false, true] {
            for acr in [None, Some(crate::acr::Acr::MultiFactor)] {
                let with = build_login_redirect_for(GOOD, reauth, acr, &Cosmetic::NONE);
                assert!(
                    !with.contains("login_hint")
                        && !with.contains("display")
                        && !with.contains("ui_locale"),
                    "an empty presentation must add no parameter at all: {with}"
                );
            }
        }
    }

    /// **W5, T5.1's builder half.** The hint is carried verbatim and
    /// percent-encoded, and — the property that matters — the URL is the same
    /// whatever the hint says, because nothing here looks it up. Two hints of
    /// the same length produce URLs of the same length; the only difference
    /// between them is the echoed value.
    #[test]
    fn the_login_hint_is_echoed_and_never_interpreted() {
        let existing = build_login_redirect_for(
            GOOD,
            false,
            None,
            &Cosmetic {
                login_hint: Some("ada@example.com"),
                ..Cosmetic::NONE
            },
        );
        let missing = build_login_redirect_for(
            GOOD,
            false,
            None,
            &Cosmetic {
                login_hint: Some("bob@example.com"),
                ..Cosmetic::NONE
            },
        );
        assert!(
            existing.ends_with("&login_hint=ada%40example.com"),
            "{existing}"
        );
        assert!(
            missing.ends_with("&login_hint=bob%40example.com"),
            "{missing}"
        );
        assert_eq!(
            existing.replace("ada", "bob"),
            missing,
            "the two URLs may differ only in the echoed value"
        );
    }

    /// **T5.2's server half.** A hostile hint is a hostile *value*, not a
    /// hostile URL: everything that could terminate a parameter or a header is
    /// percent-encoded, so the `Location` still carries exactly one
    /// `login_hint`.
    #[test]
    fn a_hostile_login_hint_cannot_escape_its_parameter() {
        for hostile in [
            "<script>alert(1)</script>",
            "a&reauth=1",
            "a&acr=urn:axiam:acr:mfa",
            "a#fragment",
            "a b",
            "a\r\nSet-Cookie: x=y",
            "ada+bob@example.com",
            "%2e%2e%2f",
            "日本語@example.com",
        ] {
            let location = build_login_redirect_for(
                GOOD,
                false,
                None,
                &Cosmetic {
                    login_hint: Some(hostile),
                    ..Cosmetic::NONE
                },
            );
            assert_eq!(
                location.matches("login_hint=").count(),
                1,
                "{hostile:?} produced {location}"
            );
            // Everything after the parameter name is one encoded value: no
            // separator, no fragment, no whitespace, no control character.
            let value = location.rsplit("&login_hint=").next().expect("a value");
            assert!(
                !value.contains('&')
                    && !value.contains('#')
                    && !value.contains('=')
                    && value.chars().all(|c| !c.is_whitespace() && !c.is_control()),
                "{hostile:?} produced the value {value:?}"
            );
        }
    }

    /// **T6.2's builder half.** `display` and `ui_locale` are types, so the
    /// only strings that can appear are the ones the types can spell. There is
    /// no parameter on this function a raw `ui_locales` list could arrive
    /// through.
    #[test]
    fn only_allow_listed_tokens_reach_the_presentation_parameters() {
        use crate::locale::{ALL_LOCALES, Display, Locale};

        let location = build_login_redirect_for(
            GOOD,
            true,
            Some(crate::acr::Acr::MultiFactor),
            &Cosmetic {
                login_hint: Some("ada"),
                display: Some(Display::Popup),
                ui_locale: Some(Locale::Italian),
            },
        );
        assert!(location.contains("&display=popup"), "{location}");
        assert!(location.contains("&ui_locale=it"), "{location}");
        // The whole URL is one line of ASCII with no unencoded separators
        // beyond the ones this builder wrote.
        assert!(location.is_ascii(), "{location}");

        for locale in ALL_LOCALES {
            let built = build_login_redirect_for(
                GOOD,
                false,
                None,
                &Cosmetic {
                    ui_locale: Some(locale),
                    ..Cosmetic::NONE
                },
            );
            assert!(
                built.ends_with(&format!("&ui_locale={}", locale.as_tag())),
                "{built}"
            );
        }
        for display in [Display::Page, Display::Popup, Display::Touch, Display::Wap] {
            let built = build_login_redirect_for(
                GOOD,
                false,
                None,
                &Cosmetic {
                    display: Some(display),
                    ..Cosmetic::NONE
                },
            );
            assert!(
                built.ends_with(&format!("&display={}", display.as_str())),
                "{built}"
            );
        }
    }

    /// **W5.** `claims_locales` selects nothing, on its own or beside a
    /// `ui_locales` that matches: it is not a parameter of `from_params`, it
    /// has no field on `Cosmetic`, and this is the assertion that the one
    /// call site reads the other list.
    #[test]
    fn claims_locales_never_reaches_the_ui_locale_selection() {
        use crate::authn_params::{AuthnRequestParams, RawAuthnParams};
        use crate::locale::Locale;

        // `claims_locales=it` alone: parsed, present, and it changes nothing.
        let only_claims = AuthnRequestParams::parse(&RawAuthnParams {
            claims_locales: Some("it"),
            ..Default::default()
        });
        assert_eq!(only_claims.claims_locales.as_deref(), Some("it"));
        let cosmetic = Cosmetic::from_params(&only_claims, None);
        assert!(
            cosmetic.is_empty(),
            "claims_locales must select no page language: {cosmetic:?}"
        );
        assert_eq!(
            build_login_redirect_for(GOOD, false, None, &cosmetic),
            build_login_redirect(GOOD, false),
            "a request carrying only claims_locales must build the W3 URL"
        );

        // …and it does not override a `ui_locales` that did match, nor stand
        // in for one that did not.
        let both = AuthnRequestParams::parse(&RawAuthnParams {
            ui_locales: Some("fr"),
            claims_locales: Some("it"),
            ..Default::default()
        });
        assert_eq!(
            Cosmetic::from_params(&both, None).ui_locale,
            Some(Locale::French)
        );
        let claims_only_matches = AuthnRequestParams::parse(&RawAuthnParams {
            ui_locales: Some("zz"),
            claims_locales: Some("it"),
            ..Default::default()
        });
        assert_eq!(
            Cosmetic::from_params(&claims_only_matches, None).ui_locale,
            None
        );
    }

    /// **W5.** The assembly step, end to end: allow-listed values survive,
    /// out-of-list ones are dropped, and the tenant default is the second
    /// answer rather than the first.
    #[test]
    fn the_presentation_is_assembled_from_the_parsed_bundle_alone() {
        use crate::authn_params::{AuthnRequestParams, RawAuthnParams};
        use crate::locale::{Display, Locale};

        let params = AuthnRequestParams::parse(&RawAuthnParams {
            login_hint: Some("ada@example.com"),
            display: Some("popup"),
            ui_locales: Some("de-AT fr"),
            ..Default::default()
        });
        let cosmetic = Cosmetic::from_params(&params, Some(Locale::Italian));
        assert_eq!(cosmetic.login_hint, Some("ada@example.com"));
        assert_eq!(cosmetic.display, Some(Display::Popup));
        assert_eq!(
            cosmetic.ui_locale,
            Some(Locale::German),
            "de-AT truncates to de, and it is first in the RP's order"
        );

        // An out-of-list `display` is dropped; the tenant default answers a
        // `ui_locales` that matched nothing.
        let dropped = AuthnRequestParams::parse(&RawAuthnParams {
            display: Some("modal"),
            ui_locales: Some("zz"),
            ..Default::default()
        });
        let cosmetic = Cosmetic::from_params(&dropped, Some(Locale::Spanish));
        assert_eq!(cosmetic.display, None);
        assert_eq!(cosmetic.ui_locale, Some(Locale::Spanish));

        // Nothing asked for, no tenant default: the ignore lane's value.
        let nothing = AuthnRequestParams::parse(&RawAuthnParams::default());
        assert!(Cosmetic::from_params(&nothing, None).is_empty());
    }

    /// The parameters are appended in a fixed order, so a test that compares
    /// two URLs is comparing what it thinks it is.
    #[test]
    fn the_presentation_parameters_are_appended_in_a_fixed_order() {
        use crate::locale::{Display, Locale};
        let location = build_login_redirect_for(
            GOOD,
            true,
            Some(crate::acr::Acr::SingleFactor),
            &Cosmetic {
                login_hint: Some("ada"),
                display: Some(Display::Touch),
                ui_locale: Some(Locale::German),
            },
        );
        let order: Vec<usize> = [
            "&reauth=1",
            "&acr=",
            "&login_hint=",
            "&display=",
            "&ui_locale=",
        ]
        .iter()
        .map(|needle| {
            location
                .find(needle)
                .unwrap_or_else(|| panic!("{needle} in {location}"))
        })
        .collect();
        assert!(
            order.windows(2).all(|w| w[0] < w[1]),
            "parameters out of order in {location}"
        );
    }

    /// The loop guard, stated as the property the module docs argue: a request
    /// carrying the marker is a return leg, and the server never builds a
    /// second redirect for one.
    #[test]
    fn the_marker_makes_the_second_leg_recognisable() {
        assert!(!is_return_leg(None));
        assert!(is_return_leg(Some("1")));
        assert!(
            is_return_leg(Some("0")),
            "presence is what the guard reads; a caller who sent 0 has still been here"
        );
        assert!(is_return_leg(Some("")));
    }
}
