//! §22 reactor reference vectors — the byte-exact contract every SDK reactor
//! runtime must reproduce, in **both** directions.
//!
//! Sibling of [`reference_vectors.rs`], which pins the §8 v2 vectors for
//! `AuthzRequest`/`AuditEventMessage`. The reactor protocol is the first place
//! where an SDK both *verifies* a server signature (the event) and *produces*
//! one (the reply), so the fixture carries a positive vector for each
//! direction plus the negatives that a reply verifier must reject.
//!
//! The vectors are GENERATED BY THE SERVER'S OWN CODE
//! (`ReactorEventMessage::signed`'s sign path, `ReactorReply::sign`,
//! `ReactorReply::into_outcome`) so they are real server-produced bytes, not
//! hand-authored. `test_reactor_reference_vectors_match` asserts the committed
//! fixture still equals a fresh computation, so any drift in the signed wire
//! shape (field order, field set, serialization) fails CI.
//!
//! To regenerate the fixture after an INTENTIONAL contract change, run:
//!   AXIAM_REGEN_VECTORS=1 cargo test -p axiam-amqp --test reactor_reference_vectors
//! then review and commit `tests/fixtures/reactor_v2_reference_vectors.json`.

use std::collections::BTreeMap;

use axiam_amqp::messages::{
    CURRENT_KEY_VERSION, DEFAULT_FRESHNESS_SKEW_SECS, derive_tenant_key, sign_payload,
};
use axiam_amqp::reactor::protocol::{
    ReactorEventMessage, ReactorReply, ReplyDecision, ReplyRejection, queue_name, routing_key,
};
use axiam_amqp::reactor::{REACTOR_EXCHANGE, ReactorReply as ExportedReply};
use axiam_core::models::reactor::{ReactorOutcome, event_spec};
use chrono::{DateTime, TimeZone, Utc};
use uuid::Uuid;

const FIXTURE_PATH: &str = "tests/fixtures/reactor_v2_reference_vectors.json";

// The same fixed inputs the §8 v2 vectors use, so an SDK can reuse one loader
// and one derived subkey across both fixtures.
const MASTER_KEY_HEX: &str = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f";
const TENANT_ID: &str = "11111111-1111-1111-1111-111111111111";
const REACTOR_ID: &str = "99999999-9999-9999-9999-999999999999";
const CORRELATION_ID: &str = "22222222-2222-2222-2222-222222222222";
const OTHER_CORRELATION_ID: &str = "2a2a2a2a-2a2a-2a2a-2a2a-2a2a2a2a2a2a";
const EVENT_NONCE: &str = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa";
const REPLY_NONCE: &str = "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb";
const REPLAY_NONCE: &str = "cccccccc-cccc-cccc-cccc-cccccccccccc";
const KEY_VERSION: u8 = 2;

fn master_key() -> Vec<u8> {
    hex::decode(MASTER_KEY_HEX).expect("valid hex master key")
}

fn uuid(s: &str) -> Uuid {
    Uuid::parse_str(s).expect("valid uuid")
}

fn tenant_id() -> Uuid {
    uuid(TENANT_ID)
}

/// The reference instant. Every vector is signed at, and verified at, a fixed
/// clock so the freshness gate is deterministic.
fn base_time() -> DateTime<Utc> {
    Utc.with_ymd_and_hms(2026, 7, 10, 12, 0, 0).unwrap()
}

fn skew() -> chrono::Duration {
    chrono::Duration::seconds(DEFAULT_FRESHNESS_SKEW_SECS)
}

/// Sign canonical bytes exactly as the server does: HMAC-SHA256 under the
/// HKDF-derived per-tenant subkey.
fn sign(canonical_bytes: &[u8]) -> String {
    let subkey = derive_tenant_key(&master_key(), tenant_id(), KEY_VERSION);
    sign_payload(&subkey, canonical_bytes)
}

// ---------------------------------------------------------------------------
// Builders — fixed-field twins of the server's own constructors
// ---------------------------------------------------------------------------

/// A server→reactor event with a pinned nonce.
///
/// `ReactorEventMessage::signed` mints a fresh UUIDv4 nonce, which is correct
/// in production and useless in a fixture, so the nonce is pinned here and the
/// *signature* is produced by the same `derive_tenant_key` + `sign_payload`
/// pair that `signed()` calls. `verify()` — the real server/SDK verify path —
/// is asserted against every vector below.
fn event(
    name: &str,
    payload: serde_json::Value,
    timeout_ms: u32,
    nonce: Uuid,
    issued_at: DateTime<Utc>,
) -> ReactorEventMessage {
    let mut msg = ReactorEventMessage {
        tenant_id: tenant_id(),
        event: name.to_string(),
        correlation_id: uuid(CORRELATION_ID),
        payload,
        timeout_ms,
        key_version: KEY_VERSION,
        nonce,
        issued_at,
        hmac_signature: None,
    };
    let canonical = serde_json::to_vec(&msg).expect("serialize event");
    msg.hmac_signature = Some(sign(&canonical));
    msg
}

/// A reactor→server reply, signed through the server's own `sign()`.
fn reply(
    name: &str,
    decision: ReplyDecision,
    reason: Option<&str>,
    patch: Option<&[(&str, &str)]>,
    require_mfa: bool,
    nonce: Uuid,
    issued_at: DateTime<Utc>,
) -> ReactorReply {
    let mut r = ReactorReply {
        correlation_id: uuid(CORRELATION_ID),
        tenant_id: tenant_id(),
        event: name.to_string(),
        decision,
        reason: reason.map(str::to_string),
        patch: patch.map(|pairs| {
            pairs
                .iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect::<BTreeMap<String, String>>()
        }),
        require_mfa,
        key_version: KEY_VERSION,
        nonce,
        issued_at,
        hmac_signature: None,
    };
    r.sign(&master_key()).expect("sign reply");
    r
}

/// The canonical signed bytes of an already-signed message: the same value
/// with `hmac_signature` cleared, re-serialized. This is exactly the
/// reconstruction a verifier performs.
fn canonical_of_event(msg: &ReactorEventMessage) -> String {
    let mut unsigned = msg.clone();
    unsigned.hmac_signature = None;
    String::from_utf8(serde_json::to_vec(&unsigned).unwrap()).unwrap()
}

fn canonical_of_reply(r: &ReactorReply) -> String {
    let mut unsigned = r.clone();
    unsigned.hmac_signature = None;
    String::from_utf8(serde_json::to_vec(&unsigned).unwrap()).unwrap()
}

fn event_vector(msg: &ReactorEventMessage) -> serde_json::Value {
    serde_json::json!({
        "message": serde_json::to_value(msg).unwrap(),
        "canonical_signed_json": canonical_of_event(msg),
        "hmac_signature_hex": msg.hmac_signature.clone().unwrap(),
        "routing_key": routing_key(msg.tenant_id, &msg.event),
    })
}

fn reply_vector(r: &ReactorReply, expected: &serde_json::Value) -> serde_json::Value {
    serde_json::json!({
        "message": serde_json::to_value(r).unwrap(),
        "canonical_signed_json": canonical_of_reply(r),
        "hmac_signature_hex": r.hmac_signature.clone().unwrap(),
        "expected_outcome": expected,
    })
}

/// Render an outcome as the fixture's language-neutral shape.
fn outcome_json(outcome: &ReactorOutcome) -> serde_json::Value {
    match outcome {
        ReactorOutcome::Allow => serde_json::json!({ "kind": "allow" }),
        ReactorOutcome::Deny { reason } => serde_json::json!({ "kind": "deny", "reason": reason }),
        ReactorOutcome::Mutate { patch } => serde_json::json!({ "kind": "mutate", "patch": patch }),
        ReactorOutcome::RequireMfa => serde_json::json!({ "kind": "require_mfa" }),
    }
}

/// Stable, language-neutral names for the rejection reasons, so an SDK's own
/// error enum can be asserted against the fixture without matching on Rust
/// `Debug` output.
fn rejection_name(r: &ReplyRejection) -> String {
    match r {
        ReplyRejection::WrongCorrelation => "wrong_correlation".into(),
        ReplyRejection::TenantMismatch => "tenant_mismatch".into(),
        ReplyRejection::EventMismatch => "event_mismatch".into(),
        ReplyRejection::KeyVersionTooOld(_) => "key_version_too_old".into(),
        ReplyRejection::Stale => "stale".into(),
        ReplyRejection::BadSignature => "bad_signature".into(),
        ReplyRejection::NotMutable => "not_mutable".into(),
        ReplyRejection::ForbiddenPatchField(f) => format!("forbidden_patch_field:{f}"),
        ReplyRejection::MalformedMutation => "malformed_mutation".into(),
        ReplyRejection::RequireMfaNotSupported => "require_mfa_not_supported".into(),
    }
}

/// Resolve a reply through the real server verify path.
fn resolve(
    r: &ReactorReply,
    expected_correlation: Uuid,
    now: DateTime<Utc>,
) -> Result<ReactorOutcome, ReplyRejection> {
    let spec = event_spec(&r.event).expect("registry event");
    r.clone().into_outcome(
        &master_key(),
        expected_correlation,
        tenant_id(),
        spec,
        now,
        skew(),
    )
}

// ---------------------------------------------------------------------------
// Fixture construction
// ---------------------------------------------------------------------------

fn build_fixture() -> serde_json::Value {
    assert_eq!(
        KEY_VERSION, CURRENT_KEY_VERSION,
        "reactor vectors must target the current key version"
    );

    let now = base_time();
    let subkey = derive_tenant_key(&master_key(), tenant_id(), KEY_VERSION);

    // --- server → reactor ---------------------------------------------------
    let token_event = event(
        "token.pre_issue",
        serde_json::json!({ "sub": "alice", "client_id": "portal" }),
        500,
        uuid(EVENT_NONCE),
        now,
    );
    let login_event = event(
        "login.post_auth",
        serde_json::json!({ "sub": "alice", "ip": "203.0.113.7" }),
        1_000,
        uuid(REPLAY_NONCE),
        now,
    );

    // --- reactor → server ---------------------------------------------------
    let allow = reply(
        "login.post_auth",
        ReplyDecision::Allow,
        None,
        None,
        false,
        uuid(REPLY_NONCE),
        now,
    );
    let deny = reply(
        "login.post_auth",
        ReplyDecision::Deny,
        Some("embargoed region"),
        None,
        false,
        uuid(REPLY_NONCE),
        now,
    );
    let require_mfa = reply(
        "login.post_auth",
        ReplyDecision::Allow,
        None,
        None,
        true,
        uuid(REPLY_NONCE),
        now,
    );
    let mutate = reply(
        "token.pre_issue",
        ReplyDecision::Mutate,
        None,
        Some(&[("ext.cost_center", "42"), ("ext.department", "eng")]),
        false,
        uuid(REPLY_NONCE),
        now,
    );

    // --- negatives a reply verifier MUST reject -----------------------------
    //
    // Every one of these is correctly signed. That is the point: a verifier
    // that stops at the signature accepts all four.
    let stale = reply(
        "login.post_auth",
        ReplyDecision::Allow,
        None,
        None,
        false,
        uuid(REPLY_NONCE),
        now - chrono::Duration::seconds(DEFAULT_FRESHNESS_SKEW_SECS + 1),
    );
    let forbidden = reply(
        "token.pre_issue",
        ReplyDecision::Mutate,
        None,
        Some(&[("ext.department", "eng"), ("sub", "root")]),
        false,
        uuid(REPLY_NONCE),
        now,
    );
    let veto_only_mutation = reply(
        "grant.pre_assign",
        ReplyDecision::Mutate,
        None,
        Some(&[("role", "admin")]),
        false,
        uuid(REPLY_NONCE),
        now,
    );

    // The replay vector: `allow` above, re-presented against a *different*
    // correlation. Same bytes, same valid signature, same fresh `issued_at` —
    // rejected because the correlation the dispatcher is waiting on is the
    // single-use handle that binds a reply to its request.
    let replay = serde_json::json!({
        "description": "the `reactor_to_server.allow` vector replayed against another \
                        in-flight event: identical bytes, valid signature, inside the \
                        freshness window, and still rejected",
        "message": serde_json::to_value(&allow).unwrap(),
        "canonical_signed_json": canonical_of_reply(&allow),
        "hmac_signature_hex": allow.hmac_signature.clone().unwrap(),
        "verify_against_correlation_id": OTHER_CORRELATION_ID,
        "expected_rejection": rejection_name(
            &resolve(&allow, uuid(OTHER_CORRELATION_ID), now).unwrap_err(),
        ),
    });

    // The nonce is inside the signed bytes: two replies differing in nothing
    // but `nonce` carry different MACs, so a captured reply cannot be
    // re-signed onto a fresh nonce without the key.
    let nonce_a = reply(
        "login.post_auth",
        ReplyDecision::Allow,
        None,
        None,
        false,
        uuid(REPLY_NONCE),
        now,
    );
    let nonce_b = reply(
        "login.post_auth",
        ReplyDecision::Allow,
        None,
        None,
        false,
        uuid(REPLAY_NONCE),
        now,
    );

    serde_json::json!({
        "_comment": "§22 reactor wire vectors. GENERATED by the AXIAM server's own reactor \
            sign/verify path (axiam-amqp::reactor::protocol). Both directions are signed with \
            the SAME §8 v2 primitives as the audit/authz vectors in v2_reference_vectors.json: \
            HMAC-SHA256 over the message serialized with `hmac_signature` set to JSON null, \
            keyed by HKDF-SHA256(salt=APP_SALT, ikm=master_key, info=DOMAIN_TAG || \
            key_version(1 byte) || tenant_id(16 raw bytes)). NOTE the difference from §8's own \
            two message types: on a reactor event and a reactor reply `hmac_signature` is \
            SERIALIZED AS null inside the signed bytes rather than omitted. An SDK MUST \
            reproduce `canonical_signed_json` byte-for-byte and recompute the same \
            `hmac_signature_hex`.",
        "hkdf": {
            "app_salt_utf8": "axiam-amqp-hkdf-salt-v1",
            "domain_tag_utf8": "axiam-amqp-v1",
            "info_layout": "domain_tag_bytes || key_version_u8 || tenant_id_16_raw_bytes",
            "derived_subkey_hex": hex::encode(subkey),
        },
        "master_signing_key_hex": MASTER_KEY_HEX,
        "tenant_id": TENANT_ID,
        "reactor_id": REACTOR_ID,
        "key_version": KEY_VERSION,
        "freshness_skew_secs": DEFAULT_FRESHNESS_SKEW_SECS,
        "verified_at": base_time().to_rfc3339_opts(chrono::SecondsFormat::Secs, true),
        "expected_correlation_id": CORRELATION_ID,
        "topology": {
            "exchange": REACTOR_EXCHANGE,
            "exchange_type": "topic",
            "routing_key_token_pre_issue": routing_key(tenant_id(), "token.pre_issue"),
            "routing_key_login_post_auth": routing_key(tenant_id(), "login.post_auth"),
            "queue": queue_name(tenant_id(), uuid(REACTOR_ID)),
        },
        "field_order": {
            "reactor_event": [
                "tenant_id", "event", "correlation_id", "payload", "timeout_ms",
                "key_version", "nonce", "issued_at",
                "hmac_signature (SERIALIZED AS null while signing, not omitted)"
            ],
            "reactor_reply": [
                "correlation_id", "tenant_id", "event", "decision",
                "reason (omitted when null)", "patch (omitted when null)",
                "require_mfa (omitted when false)", "key_version", "nonce", "issued_at",
                "hmac_signature (SERIALIZED AS null while signing, not omitted)"
            ]
        },
        "server_to_reactor": {
            "token_pre_issue": event_vector(&token_event),
            "login_post_auth": event_vector(&login_event),
        },
        "reactor_to_server": {
            "allow": reply_vector(&allow, &outcome_json(&resolve(&allow, uuid(CORRELATION_ID), now).unwrap())),
            "deny": reply_vector(&deny, &outcome_json(&resolve(&deny, uuid(CORRELATION_ID), now).unwrap())),
            "require_mfa": reply_vector(&require_mfa, &outcome_json(&resolve(&require_mfa, uuid(CORRELATION_ID), now).unwrap())),
            "mutate": reply_vector(&mutate, &outcome_json(&resolve(&mutate, uuid(CORRELATION_ID), now).unwrap())),
        },
        "rejected_replies": {
            "stale": {
                "message": serde_json::to_value(&stale).unwrap(),
                "canonical_signed_json": canonical_of_reply(&stale),
                "hmac_signature_hex": stale.hmac_signature.clone().unwrap(),
                "expected_rejection": rejection_name(&resolve(&stale, uuid(CORRELATION_ID), now).unwrap_err()),
            },
            "forbidden_patch_field": {
                "message": serde_json::to_value(&forbidden).unwrap(),
                "canonical_signed_json": canonical_of_reply(&forbidden),
                "hmac_signature_hex": forbidden.hmac_signature.clone().unwrap(),
                "expected_rejection": rejection_name(&resolve(&forbidden, uuid(CORRELATION_ID), now).unwrap_err()),
            },
            "mutation_on_veto_only_event": {
                "message": serde_json::to_value(&veto_only_mutation).unwrap(),
                "canonical_signed_json": canonical_of_reply(&veto_only_mutation),
                "hmac_signature_hex": veto_only_mutation.hmac_signature.clone().unwrap(),
                "expected_rejection": rejection_name(&resolve(&veto_only_mutation, uuid(CORRELATION_ID), now).unwrap_err()),
            },
            "correlation_replay": replay,
        },
        "nonce_binding": {
            "_comment": "Two replies identical in every field but `nonce`. Different MACs — \
                the nonce is inside the signed bytes, so a captured reply cannot be re-aimed \
                at a later event by swapping its nonce.",
            "nonce_a": nonce_a.nonce,
            "hmac_a_hex": nonce_a.hmac_signature.clone().unwrap(),
            "nonce_b": nonce_b.nonce,
            "hmac_b_hex": nonce_b.hmac_signature.clone().unwrap(),
        }
    })
}

fn fixture_path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(FIXTURE_PATH)
}

/// Rewrite the fixture from the server's sign path when `AXIAM_REGEN_VECTORS`
/// is set — exactly once per process, whichever test reaches it first.
///
/// The `Once` is not decoration. The harness runs these tests on parallel
/// threads, so putting the regeneration inside a single test means the other
/// tests race it and read a fixture that does not exist yet. Regeneration is a
/// property of the *run*, not of one test.
fn regenerate_if_requested() {
    static ONCE: std::sync::Once = std::sync::Once::new();
    ONCE.call_once(|| {
        if std::env::var("AXIAM_REGEN_VECTORS").is_ok() {
            let pretty = serde_json::to_string_pretty(&build_fixture()).unwrap();
            std::fs::write(fixture_path(), pretty + "\n").expect("write fixture");
            eprintln!("regenerated {}", fixture_path().display());
        }
    });
}

fn load_fixture() -> serde_json::Value {
    regenerate_if_requested();
    let raw = std::fs::read_to_string(fixture_path()).expect(
        "reactor reference-vectors fixture must exist — regenerate with AXIAM_REGEN_VECTORS=1 if \
         this is a deliberate contract change",
    );
    serde_json::from_str(&raw).expect("fixture is valid JSON")
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

/// The committed fixture must equal a fresh computation from the server's own
/// code. This is what locks the signed wire shape for eleven SDKs.
#[test]
fn test_reactor_reference_vectors_match() {
    let computed = build_fixture();
    let fixture = load_fixture();
    assert_eq!(
        fixture, computed,
        "the committed reactor vectors drifted from the server's sign path — regenerate with \
         AXIAM_REGEN_VECTORS=1 only if the wire shape change was intended"
    );
}

/// **Sign direction.** Reconstruct the canonical bytes from each committed
/// message and recompute the MAC — the exact work a reactor runtime does when
/// it produces a reply. Covers both directions' message types.
#[test]
fn test_sign_direction_recomputes_every_committed_mac() {
    let fixture = load_fixture();

    for key in ["token_pre_issue", "login_post_auth"] {
        let vector = &fixture["server_to_reactor"][key];
        let mut msg: ReactorEventMessage =
            serde_json::from_value(vector["message"].clone()).unwrap();
        msg.hmac_signature = None;
        let canonical = String::from_utf8(serde_json::to_vec(&msg).unwrap()).unwrap();
        assert_eq!(
            canonical,
            vector["canonical_signed_json"].as_str().unwrap(),
            "{key}: re-serializing the event with the signature cleared must reproduce the \
             canonical signed bytes"
        );
        assert_eq!(
            sign(canonical.as_bytes()),
            vector["hmac_signature_hex"].as_str().unwrap(),
            "{key}: recomputed event MAC differs from the committed one"
        );
    }

    for key in ["allow", "deny", "require_mfa", "mutate"] {
        let vector = &fixture["reactor_to_server"][key];
        let mut r: ReactorReply = serde_json::from_value(vector["message"].clone()).unwrap();
        r.hmac_signature = None;
        let canonical = String::from_utf8(serde_json::to_vec(&r).unwrap()).unwrap();
        assert_eq!(
            canonical,
            vector["canonical_signed_json"].as_str().unwrap(),
            "{key}: re-serializing the reply with the signature cleared must reproduce the \
             canonical signed bytes"
        );
        assert_eq!(
            sign(canonical.as_bytes()),
            vector["hmac_signature_hex"].as_str().unwrap(),
            "{key}: recomputed reply MAC differs from the committed one"
        );

        // And the server's own `sign()` must land on the same bytes.
        let mut resigned: ReactorReply = serde_json::from_value(vector["message"].clone()).unwrap();
        resigned.sign(&master_key()).unwrap();
        assert_eq!(
            resigned.hmac_signature.as_deref(),
            Some(vector["hmac_signature_hex"].as_str().unwrap()),
            "{key}: ReactorReply::sign must reproduce the committed signature"
        );
    }
}

/// **Verify direction, server→reactor.** Each committed event verifies under
/// the tenant subkey, and every tampering the wire admits invalidates it.
#[test]
fn test_verify_direction_accepts_events_and_rejects_tampering() {
    let fixture = load_fixture();
    let master = master_key();

    for key in ["token_pre_issue", "login_post_auth"] {
        let vector = &fixture["server_to_reactor"][key];
        let msg: ReactorEventMessage = serde_json::from_value(vector["message"].clone()).unwrap();

        assert!(msg.verify(&master), "{key}: committed event must verify");
        assert!(
            !msg.verify(b"a different master key"),
            "{key}: must not verify under another key"
        );

        // The routing key an SDK binds on is part of the vector, and derives
        // from fields inside the signed body.
        assert_eq!(
            routing_key(msg.tenant_id, &msg.event),
            vector["routing_key"].as_str().unwrap()
        );

        let mut cross_tenant = msg.clone();
        cross_tenant.tenant_id = Uuid::nil();
        assert!(
            !cross_tenant.verify(&master),
            "{key}: a captured event replayed into another tenant must not verify"
        );

        let mut stretched = msg.clone();
        stretched.timeout_ms += 1;
        assert!(
            !stretched.verify(&master),
            "{key}: widening the answer window is tampering"
        );

        let mut renonced = msg;
        renonced.nonce = Uuid::nil();
        assert!(
            !renonced.verify(&master),
            "{key}: the nonce is inside the signed body"
        );
    }
}

/// **Verify direction, reactor→server.** Each committed reply resolves to the
/// outcome the fixture claims, and each committed negative is rejected for the
/// reason the fixture names — including the replay case.
#[test]
fn test_verify_direction_resolves_replies_and_rejects_the_negatives() {
    let fixture = load_fixture();
    let now = base_time();
    let correlation = uuid(fixture["expected_correlation_id"].as_str().unwrap());

    for key in ["allow", "deny", "require_mfa", "mutate"] {
        let vector = &fixture["reactor_to_server"][key];
        let r: ExportedReply = serde_json::from_value(vector["message"].clone()).unwrap();
        let outcome = resolve(&r, correlation, now)
            .unwrap_or_else(|e| panic!("{key}: committed reply must resolve, got {e}"));
        assert_eq!(
            outcome_json(&outcome),
            vector["expected_outcome"],
            "{key}: resolved outcome differs from the committed one"
        );
    }

    for key in [
        "stale",
        "forbidden_patch_field",
        "mutation_on_veto_only_event",
        "correlation_replay",
    ] {
        let vector = &fixture["rejected_replies"][key];
        let r: ReactorReply = serde_json::from_value(vector["message"].clone()).unwrap();
        let against = vector
            .get("verify_against_correlation_id")
            .and_then(|v| v.as_str())
            .map(uuid)
            .unwrap_or(correlation);

        let rejection = resolve(&r, against, now)
            .expect_err(&format!("{key}: committed negative must be rejected"));
        assert_eq!(
            rejection_name(&rejection),
            vector["expected_rejection"].as_str().unwrap(),
            "{key}: rejected for a different reason than the fixture records"
        );
    }
}

/// The replay vector, stated as its own claim: the very bytes that resolve for
/// one correlation are refused for another. A verifier that checks only the
/// signature and the clock passes the positive vector and fails this one.
#[test]
fn test_a_valid_reply_is_not_valid_for_a_different_event() {
    let fixture = load_fixture();
    let now = base_time();

    let allow: ReactorReply =
        serde_json::from_value(fixture["reactor_to_server"]["allow"]["message"].clone()).unwrap();
    let replayed: ReactorReply = serde_json::from_value(
        fixture["rejected_replies"]["correlation_replay"]["message"].clone(),
    )
    .unwrap();

    assert_eq!(
        serde_json::to_value(&allow).unwrap(),
        serde_json::to_value(&replayed).unwrap(),
        "the replay vector must be the accepted reply verbatim — otherwise it proves nothing"
    );

    assert!(resolve(&allow, uuid(CORRELATION_ID), now).is_ok());
    assert_eq!(
        rejection_name(&resolve(&replayed, uuid(OTHER_CORRELATION_ID), now).unwrap_err()),
        "wrong_correlation"
    );
}

/// The nonce is signed: swapping it changes the MAC, so a captured reply
/// cannot be re-aimed at a later event without the tenant key.
#[test]
fn test_the_nonce_is_covered_by_the_signature() {
    let fixture = load_fixture();
    let binding = &fixture["nonce_binding"];

    assert_ne!(
        binding["nonce_a"], binding["nonce_b"],
        "the two nonce vectors must actually differ"
    );
    assert_ne!(
        binding["hmac_a_hex"], binding["hmac_b_hex"],
        "two replies differing only in nonce must not share a MAC"
    );

    // And re-signing the accepted reply onto the other nonce lands on the
    // committed value — i.e. the difference is the nonce and nothing else.
    let mut r: ReactorReply =
        serde_json::from_value(fixture["reactor_to_server"]["allow"]["message"].clone()).unwrap();
    r.nonce = uuid(binding["nonce_b"].as_str().unwrap());
    r.sign(&master_key()).unwrap();
    assert_eq!(r.hmac_signature.as_deref(), binding["hmac_b_hex"].as_str());
}
