//! OIDC federation management endpoints (tenant-scoped via JWT).
//!
//! Provides CRUD for federation configurations, the OIDC authorization
//! and callback flow, and federation link management.

use actix_web::{HttpResponse, web};
use axiam_core::models::federation::{
    CreateFederationConfig, FederationConfig, FederationLink, FederationProtocol,
    UpdateFederationConfig,
};
use axiam_core::repository::{
    FederationConfigRepository, FederationLinkRepository, PaginatedResult, Pagination,
};
use axiam_db::{
    SurrealFederationConfigRepository, SurrealFederationLinkRepository, SurrealUserRepository,
};
use axiam_federation::oidc::OidcFederationService;
use axiam_federation::saml::SamlFederationService;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use surrealdb::Connection;
use uuid::Uuid;

use crate::error::AxiamApiError;
use crate::extractors::auth::AuthenticatedUser;

// ---------------------------------------------------------------------------
// Request / response DTOs
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize, utoipa::ToSchema)]
pub struct CreateFederationConfigRequest {
    /// Display name for the identity provider (e.g., "Google", "Okta").
    pub provider: String,
    /// Federation protocol: "OidcConnect" or "Saml".
    pub protocol: String,
    /// OIDC discovery URL or SAML metadata URL.
    pub metadata_url: Option<String>,
    /// OAuth2 client ID registered with the external IdP.
    pub client_id: String,
    /// OAuth2 client secret registered with the external IdP.
    pub client_secret: String,
    /// Maps external IdP attributes to AXIAM user fields.
    pub attribute_map: Option<serde_json::Value>,
}

#[derive(Debug, Deserialize, utoipa::ToSchema)]
pub struct UpdateFederationConfigRequest {
    pub provider: Option<String>,
    pub metadata_url: Option<Option<String>>,
    pub client_id: Option<String>,
    pub client_secret: Option<String>,
    pub attribute_map: Option<serde_json::Value>,
    pub enabled: Option<bool>,
}

/// Federation config response -- omits client_secret.
#[derive(Debug, Serialize, utoipa::ToSchema)]
pub struct FederationConfigResponse {
    pub id: Uuid,
    pub tenant_id: Uuid,
    pub provider: String,
    pub protocol: String,
    pub metadata_url: Option<String>,
    pub client_id: String,
    pub attribute_map: serde_json::Value,
    pub enabled: bool,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

impl From<FederationConfig> for FederationConfigResponse {
    fn from(c: FederationConfig) -> Self {
        Self {
            id: c.id,
            tenant_id: c.tenant_id,
            provider: c.provider,
            protocol: protocol_to_string(&c.protocol).to_owned(),
            metadata_url: c.metadata_url,
            client_id: c.client_id,
            attribute_map: c.attribute_map,
            enabled: c.enabled,
            created_at: c.created_at,
            updated_at: c.updated_at,
        }
    }
}

#[derive(Debug, Deserialize, utoipa::ToSchema)]
pub struct OidcAuthorizeRequest {
    /// ID of the federation config to use.
    pub config_id: Uuid,
    /// Redirect URI the external IdP should return the user to.
    pub redirect_uri: String,
    /// CSRF state value (generated by the caller).
    pub state: String,
    /// Nonce for replay protection (generated by the caller).
    pub nonce: String,
}

#[derive(Debug, Deserialize, utoipa::ToSchema)]
pub struct OidcCallbackRequest {
    /// ID of the federation config used in the authorization request.
    pub config_id: Uuid,
    /// Authorization code returned by the external IdP.
    pub code: String,
    /// Redirect URI that was used in the authorization request.
    pub redirect_uri: String,
    /// The nonce originally sent in the authorization request.
    pub nonce: String,
}

#[derive(Debug, Serialize, utoipa::ToSchema)]
pub struct OidcAuthorizeResponse {
    /// The full authorization URL to redirect the user to.
    pub url: String,
}

#[derive(Debug, Serialize, utoipa::ToSchema)]
pub struct OidcCallbackResponse {
    pub user_id: Uuid,
    pub federation_link_id: Uuid,
    pub newly_provisioned: bool,
}

#[derive(Debug, Serialize, utoipa::ToSchema)]
pub struct FederationLinkResponse {
    pub id: Uuid,
    pub tenant_id: Uuid,
    pub user_id: Uuid,
    pub federation_config_id: Uuid,
    pub external_subject: String,
    pub external_email: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

impl From<FederationLink> for FederationLinkResponse {
    fn from(l: FederationLink) -> Self {
        Self {
            id: l.id,
            tenant_id: l.tenant_id,
            user_id: l.user_id,
            federation_config_id: l.federation_config_id,
            external_subject: l.external_subject,
            external_email: l.external_email,
            created_at: l.created_at,
            updated_at: l.updated_at,
        }
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn validation_err(msg: impl Into<String>) -> AxiamApiError {
    axiam_core::error::AxiamError::Validation {
        message: msg.into(),
    }
    .into()
}

fn protocol_to_string(p: &FederationProtocol) -> &'static str {
    match p {
        FederationProtocol::OidcConnect => "OidcConnect",
        FederationProtocol::Saml => "Saml",
    }
}

// ---------------------------------------------------------------------------
// Federation Config CRUD
// ---------------------------------------------------------------------------

/// `POST /api/v1/federation-configs`
#[utoipa::path(
    post,
    path = "/api/v1/federation-configs",
    tag = "federation",
    request_body = CreateFederationConfigRequest,
    responses(
        (status = 201, description = "Federation config created",
         body = FederationConfigResponse),
    ),
    security(("bearer" = []))
)]
pub async fn create<C: Connection>(
    user: AuthenticatedUser,
    repo: web::Data<SurrealFederationConfigRepository<C>>,
    body: web::Json<CreateFederationConfigRequest>,
) -> Result<HttpResponse, AxiamApiError> {
    let req = body.into_inner();

    if req.provider.is_empty() {
        return Err(validation_err("provider must not be empty"));
    }
    if req.client_id.is_empty() {
        return Err(validation_err("client_id must not be empty"));
    }
    if req.client_secret.is_empty() {
        return Err(validation_err("client_secret must not be empty"));
    }
    if let Some(ref url) = req.metadata_url
        && url.is_empty()
    {
        return Err(validation_err("metadata_url must not be empty"));
    }

    let protocol = match req.protocol.as_str() {
        "OidcConnect" => FederationProtocol::OidcConnect,
        "Saml" => FederationProtocol::Saml,
        _ => return Err(validation_err("protocol must be 'OidcConnect' or 'Saml'")),
    };

    let config = repo
        .create(CreateFederationConfig {
            tenant_id: user.tenant_id,
            provider: req.provider,
            protocol,
            metadata_url: req.metadata_url,
            client_id: req.client_id,
            client_secret: req.client_secret,
            attribute_map: req.attribute_map,
        })
        .await?;

    Ok(HttpResponse::Created().json(FederationConfigResponse::from(config)))
}

/// `GET /api/v1/federation-configs`
#[utoipa::path(
    get,
    path = "/api/v1/federation-configs",
    tag = "federation",
    params(Pagination),
    responses(
        (status = 200, description = "List of federation configs",
         body = inline(PaginatedResult<FederationConfigResponse>)),
    ),
    security(("bearer" = []))
)]
pub async fn list<C: Connection>(
    user: AuthenticatedUser,
    repo: web::Data<SurrealFederationConfigRepository<C>>,
    pagination: web::Query<Pagination>,
) -> Result<HttpResponse, AxiamApiError> {
    let result = repo.list(user.tenant_id, pagination.into_inner()).await?;
    let response = PaginatedResult {
        items: result
            .items
            .into_iter()
            .map(FederationConfigResponse::from)
            .collect(),
        total: result.total,
        offset: result.offset,
        limit: result.limit,
    };
    Ok(HttpResponse::Ok().json(response))
}

/// `GET /api/v1/federation-configs/{id}`
#[utoipa::path(
    get,
    path = "/api/v1/federation-configs/{id}",
    tag = "federation",
    params(("id" = Uuid, Path, description = "Federation config ID")),
    responses(
        (status = 200, description = "Federation config found",
         body = FederationConfigResponse),
        (status = 404, description = "Federation config not found"),
    ),
    security(("bearer" = []))
)]
pub async fn get<C: Connection>(
    user: AuthenticatedUser,
    path: web::Path<Uuid>,
    repo: web::Data<SurrealFederationConfigRepository<C>>,
) -> Result<HttpResponse, AxiamApiError> {
    let id = path.into_inner();
    let config = repo.get_by_id(user.tenant_id, id).await?;
    Ok(HttpResponse::Ok().json(FederationConfigResponse::from(config)))
}

/// `PUT /api/v1/federation-configs/{id}`
#[utoipa::path(
    put,
    path = "/api/v1/federation-configs/{id}",
    tag = "federation",
    params(("id" = Uuid, Path, description = "Federation config ID")),
    request_body = UpdateFederationConfigRequest,
    responses(
        (status = 200, description = "Federation config updated",
         body = FederationConfigResponse),
        (status = 404, description = "Federation config not found"),
    ),
    security(("bearer" = []))
)]
pub async fn update<C: Connection>(
    user: AuthenticatedUser,
    path: web::Path<Uuid>,
    repo: web::Data<SurrealFederationConfigRepository<C>>,
    body: web::Json<UpdateFederationConfigRequest>,
) -> Result<HttpResponse, AxiamApiError> {
    let id = path.into_inner();
    let req = body.into_inner();

    if let Some(ref provider) = req.provider
        && provider.is_empty()
    {
        return Err(validation_err("provider must not be empty"));
    }
    if let Some(ref client_id) = req.client_id
        && client_id.is_empty()
    {
        return Err(validation_err("client_id must not be empty"));
    }
    if let Some(ref client_secret) = req.client_secret
        && client_secret.is_empty()
    {
        return Err(validation_err("client_secret must not be empty"));
    }
    if let Some(Some(ref url)) = req.metadata_url
        && url.is_empty()
    {
        return Err(validation_err("metadata_url must not be empty"));
    }

    let config = repo
        .update(
            user.tenant_id,
            id,
            UpdateFederationConfig {
                provider: req.provider,
                metadata_url: req.metadata_url,
                client_id: req.client_id,
                client_secret: req.client_secret,
                attribute_map: req.attribute_map,
                enabled: req.enabled,
            },
        )
        .await?;
    Ok(HttpResponse::Ok().json(FederationConfigResponse::from(config)))
}

/// `DELETE /api/v1/federation-configs/{id}`
#[utoipa::path(
    delete,
    path = "/api/v1/federation-configs/{id}",
    tag = "federation",
    params(("id" = Uuid, Path, description = "Federation config ID")),
    responses(
        (status = 204, description = "Federation config deleted"),
        (status = 404, description = "Federation config not found"),
    ),
    security(("bearer" = []))
)]
pub async fn delete<C: Connection>(
    user: AuthenticatedUser,
    path: web::Path<Uuid>,
    repo: web::Data<SurrealFederationConfigRepository<C>>,
) -> Result<HttpResponse, AxiamApiError> {
    let id = path.into_inner();
    repo.delete(user.tenant_id, id).await?;
    Ok(HttpResponse::NoContent().finish())
}

// ---------------------------------------------------------------------------
// OIDC Flow
// ---------------------------------------------------------------------------

/// `POST /api/v1/federation/oidc/authorize`
///
/// Builds the authorization URL for the external OIDC provider. The caller
/// is responsible for generating and storing `state` and `nonce` values
/// for CSRF and replay protection.
///
/// TODO(T19.9): This endpoint currently requires authentication, making it
/// usable only for account-linking (already-authenticated users). Add
/// separate unauthenticated federation login endpoints that complete the
/// external flow and return access/refresh tokens for first-time login.
#[utoipa::path(
    post,
    path = "/api/v1/federation/oidc/authorize",
    tag = "federation",
    request_body = OidcAuthorizeRequest,
    responses(
        (status = 200, description = "Authorization URL built successfully",
         body = OidcAuthorizeResponse),
    ),
    security(("bearer" = []))
)]
pub async fn oidc_authorize<C: Connection>(
    user: AuthenticatedUser,
    config_repo: web::Data<SurrealFederationConfigRepository<C>>,
    link_repo: web::Data<SurrealFederationLinkRepository<C>>,
    user_repo: web::Data<SurrealUserRepository<C>>,
    http_client: web::Data<reqwest::Client>,
    body: web::Json<OidcAuthorizeRequest>,
) -> Result<HttpResponse, AxiamApiError> {
    let req = body.into_inner();

    if req.redirect_uri.is_empty() {
        return Err(validation_err("redirect_uri must not be empty"));
    }
    if req.state.is_empty() {
        return Err(validation_err("state must not be empty"));
    }
    if req.nonce.is_empty() {
        return Err(validation_err("nonce must not be empty"));
    }

    let service = OidcFederationService::new(
        (**config_repo).clone(),
        (**link_repo).clone(),
        (**user_repo).clone(),
        (**http_client).clone(),
    );

    let auth_url = service
        .build_authorization_url(
            user.tenant_id,
            req.config_id,
            &req.redirect_uri,
            &req.state,
            &req.nonce,
        )
        .await
        .map_err(axiam_core::error::AxiamError::from)?;

    Ok(HttpResponse::Ok().json(OidcAuthorizeResponse { url: auth_url.url }))
}

/// `POST /api/v1/federation/oidc/callback`
///
/// Handles the callback from the external OIDC provider after user
/// authentication. Exchanges the authorization code for tokens,
/// validates the ID token, and provisions or links the local user.
#[utoipa::path(
    post,
    path = "/api/v1/federation/oidc/callback",
    tag = "federation",
    request_body = OidcCallbackRequest,
    responses(
        (status = 200, description = "OIDC callback processed",
         body = OidcCallbackResponse),
    ),
    security(("bearer" = []))
)]
pub async fn oidc_callback<C: Connection>(
    user: AuthenticatedUser,
    config_repo: web::Data<SurrealFederationConfigRepository<C>>,
    link_repo: web::Data<SurrealFederationLinkRepository<C>>,
    user_repo: web::Data<SurrealUserRepository<C>>,
    http_client: web::Data<reqwest::Client>,
    body: web::Json<OidcCallbackRequest>,
) -> Result<HttpResponse, AxiamApiError> {
    let req = body.into_inner();

    if req.code.is_empty() {
        return Err(validation_err("code must not be empty"));
    }
    if req.redirect_uri.is_empty() {
        return Err(validation_err("redirect_uri must not be empty"));
    }
    if req.nonce.is_empty() {
        return Err(validation_err("nonce must not be empty"));
    }

    let service = OidcFederationService::new(
        (**config_repo).clone(),
        (**link_repo).clone(),
        (**user_repo).clone(),
        (**http_client).clone(),
    );

    let result = service
        .handle_callback(
            user.tenant_id,
            req.config_id,
            &req.code,
            &req.redirect_uri,
            &req.nonce,
        )
        .await
        .map_err(axiam_core::error::AxiamError::from)?;

    Ok(HttpResponse::Ok().json(OidcCallbackResponse {
        user_id: result.user.id,
        federation_link_id: result.federation_link.id,
        newly_provisioned: result.newly_provisioned,
    }))
}

// ---------------------------------------------------------------------------
// Federation Links
// ---------------------------------------------------------------------------

/// `GET /api/v1/federation-links/user/{user_id}`
#[utoipa::path(
    get,
    path = "/api/v1/federation-links/user/{user_id}",
    tag = "federation",
    params(("user_id" = Uuid, Path, description = "User ID")),
    responses(
        (status = 200, description = "Federation links for the user",
         body = Vec<FederationLinkResponse>),
    ),
    security(("bearer" = []))
)]
pub async fn list_user_links<C: Connection>(
    user: AuthenticatedUser,
    path: web::Path<Uuid>,
    repo: web::Data<SurrealFederationLinkRepository<C>>,
) -> Result<HttpResponse, AxiamApiError> {
    let target_user_id = path.into_inner();
    let links = repo.get_by_user_id(user.tenant_id, target_user_id).await?;
    let response: Vec<FederationLinkResponse> = links
        .into_iter()
        .map(FederationLinkResponse::from)
        .collect();
    Ok(HttpResponse::Ok().json(response))
}

/// `DELETE /api/v1/federation-links/{id}`
#[utoipa::path(
    delete,
    path = "/api/v1/federation-links/{id}",
    tag = "federation",
    params(("id" = Uuid, Path, description = "Federation link ID")),
    responses(
        (status = 204, description = "Federation link deleted"),
        (status = 404, description = "Federation link not found"),
    ),
    security(("bearer" = []))
)]
pub async fn delete_link<C: Connection>(
    user: AuthenticatedUser,
    path: web::Path<Uuid>,
    repo: web::Data<SurrealFederationLinkRepository<C>>,
) -> Result<HttpResponse, AxiamApiError> {
    let id = path.into_inner();
    repo.delete(user.tenant_id, id).await?;
    Ok(HttpResponse::NoContent().finish())
}

// ---------------------------------------------------------------------------
// SAML SP Flow — DTOs
// ---------------------------------------------------------------------------

/// Request to build a SAML AuthnRequest.
#[derive(Debug, Deserialize, utoipa::ToSchema)]
pub struct SamlAuthnRequestRequest {
    /// ID of the SAML federation config.
    pub config_id: Uuid,
    /// Assertion Consumer Service URL where the IdP will POST the
    /// response.
    pub acs_url: String,
    /// Optional relay state to pass through the SSO flow.
    pub relay_state: Option<String>,
}

/// Response containing the SAML AuthnRequest details.
#[derive(Debug, Serialize, utoipa::ToSchema)]
pub struct SamlAuthnRequestResponse {
    /// Full redirect URL (HTTP-Redirect) or IdP SSO URL (HTTP-POST).
    pub url: String,
    /// Base64-encoded AuthnRequest XML.
    pub saml_request: String,
    /// SAML binding URI (e.g.,
    /// `urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST`).
    pub binding: String,
    /// Relay state, if provided.
    pub relay_state: Option<String>,
}

/// Request to handle a SAML Response at the ACS endpoint.
#[derive(Debug, Deserialize, utoipa::ToSchema)]
pub struct SamlAcsRequest {
    /// ID of the SAML federation config.
    pub config_id: Uuid,
    /// Base64-encoded SAML Response XML from the IdP.
    pub saml_response: String,
    /// Relay state returned by the IdP.
    pub relay_state: Option<String>,
}

/// Query parameters for SP metadata generation.
#[derive(Debug, Deserialize, utoipa::ToSchema)]
pub struct SamlMetadataQuery {
    /// ID of the SAML federation config.
    pub config_id: Uuid,
    /// Assertion Consumer Service URL for the generated metadata.
    /// Must match the actual ACS endpoint URL for the deployment.
    pub acs_url: String,
}

// ---------------------------------------------------------------------------
// SAML SP Flow — Handlers
// ---------------------------------------------------------------------------

/// `POST /api/v1/federation/saml/authn-request`
///
/// Builds a SAML AuthnRequest for the specified federation config.
/// Returns the SSO URL, encoded request, and binding type for the
/// caller to initiate the redirect or POST to the IdP.
#[utoipa::path(
    post,
    path = "/api/v1/federation/saml/authn-request",
    tag = "federation",
    request_body = SamlAuthnRequestRequest,
    responses(
        (status = 200, description = "SAML AuthnRequest built",
         body = SamlAuthnRequestResponse),
    ),
    security(("bearer" = []))
)]
pub async fn saml_authn_request<C: Connection>(
    user: AuthenticatedUser,
    config_repo: web::Data<SurrealFederationConfigRepository<C>>,
    link_repo: web::Data<SurrealFederationLinkRepository<C>>,
    user_repo: web::Data<SurrealUserRepository<C>>,
    http_client: web::Data<reqwest::Client>,
    body: web::Json<SamlAuthnRequestRequest>,
) -> Result<HttpResponse, AxiamApiError> {
    let req = body.into_inner();

    if req.acs_url.is_empty() {
        return Err(validation_err("acs_url must not be empty"));
    }

    let service = SamlFederationService::new(
        (**config_repo).clone(),
        (**link_repo).clone(),
        (**user_repo).clone(),
        (**http_client).clone(),
    );

    let result = service
        .build_authn_request(user.tenant_id, req.config_id, &req.acs_url, req.relay_state)
        .await
        .map_err(axiam_core::error::AxiamError::from)?;

    Ok(HttpResponse::Ok().json(SamlAuthnRequestResponse {
        url: result.url,
        saml_request: result.saml_request,
        binding: result.binding,
        relay_state: result.relay_state,
    }))
}

/// `POST /api/v1/federation/saml/acs`
///
/// Handles the SAML Response received from the external IdP after
/// user authentication. Validates the assertion, extracts claims,
/// and provisions or links the local user.
#[utoipa::path(
    post,
    path = "/api/v1/federation/saml/acs",
    tag = "federation",
    request_body = SamlAcsRequest,
    responses(
        (status = 200, description = "SAML ACS processed",
         body = OidcCallbackResponse),
    ),
    security(("bearer" = []))
)]
pub async fn saml_acs<C: Connection>(
    user: AuthenticatedUser,
    config_repo: web::Data<SurrealFederationConfigRepository<C>>,
    link_repo: web::Data<SurrealFederationLinkRepository<C>>,
    user_repo: web::Data<SurrealUserRepository<C>>,
    http_client: web::Data<reqwest::Client>,
    body: web::Json<SamlAcsRequest>,
) -> Result<HttpResponse, AxiamApiError> {
    let req = body.into_inner();

    if req.saml_response.is_empty() {
        return Err(validation_err("saml_response must not be empty"));
    }

    let service = SamlFederationService::new(
        (**config_repo).clone(),
        (**link_repo).clone(),
        (**user_repo).clone(),
        (**http_client).clone(),
    );

    let result = service
        .handle_saml_response(
            user.tenant_id,
            req.config_id,
            &req.saml_response,
            req.relay_state.as_deref(),
        )
        .await
        .map_err(axiam_core::error::AxiamError::from)?;

    Ok(HttpResponse::Ok().json(OidcCallbackResponse {
        user_id: result.user.id,
        federation_link_id: result.federation_link.id,
        newly_provisioned: result.newly_provisioned,
    }))
}

/// `GET /api/v1/federation/saml/metadata`
///
/// Generates the SP metadata XML for the specified SAML federation
/// config. Returns XML with content type `application/samlmetadata+xml`.
#[utoipa::path(
    get,
    path = "/api/v1/federation/saml/metadata",
    tag = "federation",
    params(
        ("config_id" = Uuid, Query, description = "SAML federation config ID"),
        ("acs_url" = String, Query, description = "ACS URL for the SP metadata"),
    ),
    responses(
        (status = 200, description = "SP metadata XML",
         content_type = "application/samlmetadata+xml"),
    ),
    security(("bearer" = []))
)]
pub async fn saml_metadata<C: Connection>(
    user: AuthenticatedUser,
    config_repo: web::Data<SurrealFederationConfigRepository<C>>,
    link_repo: web::Data<SurrealFederationLinkRepository<C>>,
    user_repo: web::Data<SurrealUserRepository<C>>,
    http_client: web::Data<reqwest::Client>,
    query: web::Query<SamlMetadataQuery>,
) -> Result<HttpResponse, AxiamApiError> {
    let service = SamlFederationService::new(
        (**config_repo).clone(),
        (**link_repo).clone(),
        (**user_repo).clone(),
        (**http_client).clone(),
    );

    if query.acs_url.is_empty() {
        return Err(validation_err("acs_url must not be empty"));
    }

    let xml = service
        .generate_sp_metadata(user.tenant_id, query.config_id, &query.acs_url)
        .await
        .map_err(axiam_core::error::AxiamError::from)?;

    Ok(HttpResponse::Ok()
        .content_type("application/samlmetadata+xml")
        .body(xml))
}
