pub mod audit;
pub mod auth;
pub mod authz_check;
pub mod bootstrap;
pub mod ca_certificates;
pub mod certificates;
pub mod ciba;
pub mod ciba_approval;
pub mod dcr;
pub mod device;
pub mod directory;
pub mod email_config;
pub mod email_verification;
pub mod federation;
pub mod federation_login;
pub mod gdpr;
pub mod groups;
pub mod mds;
pub mod mfa_methods;
pub mod notification_rules;
pub mod oauth2;
pub mod oauth2_clients;
pub mod opaque;
pub mod opaque_enrollment;
pub mod org_scope;
pub mod organizations;
pub mod password_reset;
pub mod permissions;
pub mod pgp_keys;
pub mod reactors;
pub mod resources;
pub mod roles;
/// SAML IdP registry and credential management (contract §29): compiled into
/// every build, so it is **not** behind `saml`.
pub mod saml_admin;
#[cfg(feature = "saml")]
pub mod saml_idp;
/// The SAML IdP's single-logout endpoint and the IdP-initiated logout trigger
/// (T23.2.4). Behind `saml`, like the SSO endpoint it sits beside.
#[cfg(feature = "saml")]
pub mod saml_idp_slo;
pub mod scim_targets;
pub mod scim_tokens;
pub mod scopes;
pub mod service_accounts;
pub mod sessions;
pub mod settings;
pub mod ssf;
pub mod ssf_admin;
pub mod tenants;
pub mod uma;
pub mod users;
pub mod webauthn;
pub mod webauthn_policy;
pub mod webhooks;
