//! Generates and drift-gates `sdks/opaque-test-vectors.json`.
//!
//! # Why this file looks nothing like `srp_vectors_test.rs`
//!
//! The SRP fixture existed because eleven SDKs each contained their own
//! implementation of the protocol. It pinned every intermediate — `k`, `v`,
//! `A`, `B`, `u`, `S`, `K`, `M1`, `M2` — precisely so that an SDK which got
//! `u` wrong found out at `u` rather than at "one login in 256 fails".
//!
//! No SDK computes any of that any more. Every one of them binds
//! `axiam-opaque`, compiled or through a C ABI or through WebAssembly, so
//! there are no eleven implementations to disagree. Re-pinning OPAQUE's
//! internals across eleven SDKs would be eleven copies of one test of one
//! library.
//!
//! What each SDK *does* still own, and can still get wrong, is the layer
//! around the protocol: hex in and out, which JSON field goes where, honouring
//! the KSF parameters the server named instead of its own defaults, and
//! mapping failures onto the §2 error taxonomy. That is what this fixture
//! pins. It is a smaller surface than SRP's, and that is the point — the
//! surface shrank because the implementation count went from eleven to one.
//!
//! One thing an SDK cannot do locally is complete a real exchange: OPAQUE is
//! randomized and the client's blind is generated inside the core, so there is
//! no pre-recorded server response that a fresh `KE1` would match. Round-trip
//! correctness is therefore asserted here and in `axiam-api-rest`'s end-to-end
//! tests, against a real server, rather than eleven times against a fixture.
//!
//! Regenerate with:
//!
//! ```bash
//! UPDATE_OPAQUE_VECTORS=1 cargo test -p axiam-opaque --test vectors_test
//! ```
//!
//! and re-sync into all eleven SDK repositories. A change here without that
//! fan-out is a silent cross-language break.

use std::path::PathBuf;
use std::sync::OnceLock;

use axiam_opaque::{AxiamKsf, ClientLoginState, ClientRegistrationState, testing};

fn vectors_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../sdks/opaque-test-vectors.json")
}

/// Passwords minted per process rather than written as literals.
///
/// CodeQL's `rust/hardcoded-cryptographic-value` flags a literal that reaches a
/// KDF, and that rule is right about shipping code. Nothing here depends on the
/// values, and — unlike the SRP fixture, whose vectors pinned `x` and therefore
/// needed a fixed password — nothing in the generated file carries them either,
/// because with one implementation there are no two parties to agree.
fn fixture_password() -> &'static str {
    static VALUE: OnceLock<String> = OnceLock::new();
    VALUE.get_or_init(|| format!("ascii-{}", random_suffix()))
}

/// A non-ASCII password, present for the same reason the SRP fixture carried a
/// non-ASCII *identity*: a caller that hands its platform's default encoding to
/// the core rather than UTF-8 fails here, rather than for one unlucky user.
///
/// The literal part is deliberately not a password — it is an alphabet — so the
/// property being tested survives without a hard-coded credential.
fn fixture_password_unicode() -> &'static str {
    static VALUE: OnceLock<String> = OnceLock::new();
    VALUE.get_or_init(|| format!("hünter²-Ωmega-🔑-{}", random_suffix()))
}

fn random_suffix() -> String {
    let mut bytes = [0u8; 16];
    getrandom::fill(&mut bytes).expect("a CSPRNG");
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn build() -> serde_json::Value {
    let ksf = AxiamKsf::argon2id(8192, 1, 1).unwrap();

    // A full exchange, run here so the recorded lengths are measured rather
    // than asserted from the specification.
    let (reg_state, reg_request) = ClientRegistrationState::start(fixture_password()).unwrap();
    let (setup, reg_response) = testing::server_registration_start(&reg_request);
    let registered = reg_state
        .finish(fixture_password(), &reg_response, &ksf)
        .unwrap();

    let (login_state, ke1) = ClientLoginState::start(fixture_password()).unwrap();
    let ke2 = testing::server_login_start(&setup, &registered.record, &ke1);
    let logged_in = login_state.finish(fixture_password(), &ke2, &ksf).unwrap();

    serde_json::json!({
        "_comment": "Generated by `cargo test -p axiam-opaque --test vectors_test`. \
                     Do not edit by hand. Re-sync into every SDK repository when it changes.",
        "suite": "ristretto255_sha512",
        "rfc": 9807,
        "configuration": {
            "_comment": "RFC 9807's recommended configuration. An SDK MUST NOT \
                         accept a `suite` value it does not recognise, and MUST NOT \
                         let a server select primitives outside this table.",
            "oprf": "ristretto255-SHA512",
            "hash": "SHA-512",
            "kdf": "HKDF-SHA-512",
            "mac": "HMAC-SHA-512",
            "ake": "3DH"
        },
        // Every message on the wire is lowercase hex of a fixed-width byte
        // string. An SDK that mis-sizes one finds out here rather than at a
        // login that fails for no visible reason.
        "message_lengths_bytes": {
            "registration_request": reg_request.len() / 2,
            "registration_response": reg_response.len() / 2,
            "registration_record": registered.record.len() / 2,
            "ke1": ke1.len() / 2,
            "ke2": ke2.len() / 2,
            "ke3": logged_in.ke3.len() / 2,
            "export_key": registered.export_key.len() / 2,
            "session_key": logged_in.session_key.len() / 2,
            "credential_identifier": 32
        },
        // The KSF parameters arrive flat and optional, and which fields are
        // present depends on which function the server named. An SDK that read
        // an absent field as zero would stretch with the wrong cost and fail
        // against a record that is perfectly good.
        "ksf_wire_cases": [
            {
                "_comment": "argon2id: memory_kib, iterations and parallelism present; \
                             scrypt fields absent, NOT zero.",
                "response": {
                    "ksf": "argon2id",
                    "memory_kib": 19456,
                    "iterations": 2,
                    "parallelism": 1
                },
                "expect": { "ksf": "argon2id", "memory_kib": 19456, "iterations": 2, "parallelism": 1 }
            },
            {
                "_comment": "scrypt: log_n, r and p present; argon2id fields absent.",
                "response": { "ksf": "scrypt", "log_n": 17, "r": 8, "p": 1 },
                "expect": { "ksf": "scrypt", "log_n": 17, "r": 8, "p": 1 }
            },
            {
                "_comment": "An unrecognised KSF MUST be refused, never substituted. \
                             Substituting produces a well-formed randomized password \
                             that no AXIAM server agrees with, reported to the user as \
                             a wrong password.",
                "response": { "ksf": "pbkdf2_sha256", "iterations": 600000 },
                "expect_error": "unsupported_ksf"
            }
        ],
        // Accepted cost bands. A server is trusted to name its own policy, but
        // not to name one that would wedge every device an account owns, so a
        // client range-checks before it stretches.
        "ksf_bounds": {
            "argon2id": {
                "memory_kib": { "min": 8192, "max": 1048576 },
                "iterations": { "min": 1, "max": 10 },
                "parallelism": { "min": 1, "max": 16 }
            },
            "scrypt": {
                "log_n": { "min": 14, "max": 20 },
                "r": { "min": 1, "max": 16 },
                "p": { "min": 1, "max": 16 }
            }
        },
        "utf8": {
            "_comment": "There is no shared password fixture, deliberately. The SRP \
                         file carried one because its vectors pinned `x`, which two \
                         implementations had to agree on; with one implementation \
                         there is nothing to agree about. What remains is the \
                         obligation: every SDK MUST drive a non-ASCII password \
                         through its binding, choosing its own, so that a binding \
                         handing the core its platform's default encoding fails in a \
                         test rather than for one unlucky user.",
            "required": true
        },
        "endpoints": {
            "register_start": "/api/v1/auth/opaque/register/start",
            "login_start": "/api/v1/auth/opaque/login/start",
            "login_finish": "/api/v1/auth/opaque/login/finish"
        },
        "error_mapping": {
            "_comment": "How an SDK maps what it sees. `opaque_required` is the one that \
                         matters: mapping it to an authentication error would send a user \
                         off to reset a password that works, and would stop the SDK \
                         switching to the OPAQUE endpoints on its own.",
            "403_opaque_required": "distinguishable, NOT AuthenticationError",
            "404_login_start": "OPAQUE disabled for this tenant, NOT 'no such user'",
            "401_login_finish": "AuthenticationError (wrong password, unknown identity, \
                                 or expired session — indistinguishable by design)",
            "400_login_start": "NetworkError (a malformed message is the SDK's own fault)",
            "500_login_start": "server misconfiguration: keys absent while policy is on"
        }
    })
}

#[test]
fn the_vectors_file_matches_the_implementation() {
    let generated = build();
    let path = vectors_path();

    if std::env::var("UPDATE_OPAQUE_VECTORS").is_ok() {
        std::fs::write(
            &path,
            format!("{}\n", serde_json::to_string_pretty(&generated).unwrap()),
        )
        .unwrap();
        return;
    }

    let on_disk: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&path).unwrap_or_else(|e| {
            panic!(
                "{} is missing ({e}). Generate it with \
                 UPDATE_OPAQUE_VECTORS=1 cargo test -p axiam-opaque --test vectors_test",
                path.display()
            )
        }))
        .unwrap();

    assert_eq!(
        on_disk, generated,
        "sdks/opaque-test-vectors.json has drifted from the implementation. \
         Regenerate it with UPDATE_OPAQUE_VECTORS=1 and re-sync it into all \
         eleven SDK repositories — a change here without that fan-out is a \
         silent cross-language break."
    );
}

#[test]
fn a_full_exchange_round_trips_and_both_sides_agree() {
    let ksf = AxiamKsf::argon2id(8192, 1, 1).unwrap();

    let (reg_state, reg_request) = ClientRegistrationState::start(fixture_password()).unwrap();
    let (setup, reg_response) = testing::server_registration_start(&reg_request);
    let registered = reg_state
        .finish(fixture_password(), &reg_response, &ksf)
        .unwrap();

    let (login_state, ke1) = ClientLoginState::start(fixture_password()).unwrap();
    let ke2 = testing::server_login_start(&setup, &registered.record, &ke1);
    let logged_in = login_state.finish(fixture_password(), &ke2, &ksf).unwrap();

    assert_eq!(
        registered.export_key, logged_in.export_key,
        "the export key must be reproducible from the password alone; an \
         application building end-to-end encryption on it depends on that"
    );
}

#[test]
fn a_unicode_password_survives_the_round_trip() {
    let ksf = AxiamKsf::argon2id(8192, 1, 1).unwrap();

    let (reg_state, reg_request) =
        ClientRegistrationState::start(fixture_password_unicode()).unwrap();
    let (setup, reg_response) = testing::server_registration_start(&reg_request);
    let registered = reg_state
        .finish(fixture_password_unicode(), &reg_response, &ksf)
        .unwrap();

    let (login_state, ke1) = ClientLoginState::start(fixture_password_unicode()).unwrap();
    let ke2 = testing::server_login_start(&setup, &registered.record, &ke1);
    assert!(
        login_state
            .finish(fixture_password_unicode(), &ke2, &ksf)
            .is_ok()
    );
}

#[test]
fn a_wrong_password_cannot_open_the_envelope() {
    let ksf = AxiamKsf::argon2id(8192, 1, 1).unwrap();

    let (reg_state, reg_request) = ClientRegistrationState::start(fixture_password()).unwrap();
    let (setup, reg_response) = testing::server_registration_start(&reg_request);
    let registered = reg_state
        .finish(fixture_password(), &reg_response, &ksf)
        .unwrap();

    let (login_state, ke1) = ClientLoginState::start("not the password").unwrap();
    let ke2 = testing::server_login_start(&setup, &registered.record, &ke1);
    assert!(login_state.finish("not the password", &ke2, &ksf).is_err());
}

#[test]
fn a_ksf_mismatch_between_enrolment_and_login_is_fatal() {
    // Which is why the server stores the parameters per credential and echoes
    // them at login, rather than the client reading its own configuration.
    let enrol_ksf = AxiamKsf::argon2id(8192, 1, 1).unwrap();
    let login_ksf = AxiamKsf::argon2id(8192, 2, 1).unwrap();

    let (reg_state, reg_request) = ClientRegistrationState::start(fixture_password()).unwrap();
    let (setup, reg_response) = testing::server_registration_start(&reg_request);
    let registered = reg_state
        .finish(fixture_password(), &reg_response, &enrol_ksf)
        .unwrap();

    let (login_state, ke1) = ClientLoginState::start(fixture_password()).unwrap();
    let ke2 = testing::server_login_start(&setup, &registered.record, &ke1);
    assert!(
        login_state
            .finish(fixture_password(), &ke2, &login_ksf)
            .is_err()
    );
}

#[test]
fn ksf_parameters_outside_the_accepted_band_are_refused() {
    // A client range-checks what the server names. A server is trusted to set
    // its own policy, but not to name a cost that would wedge every device an
    // account owns.
    assert!(AxiamKsf::argon2id(64, 1, 1).is_err());
    assert!(AxiamKsf::argon2id(4_194_304, 1, 1).is_err());
    assert!(AxiamKsf::argon2id(19456, 99, 1).is_err());
    assert!(AxiamKsf::argon2id(19456, 2, 99).is_err());
    assert!(AxiamKsf::scrypt(10, 8, 1).is_err());
    assert!(AxiamKsf::scrypt(24, 8, 1).is_err());
    assert!(AxiamKsf::scrypt(17, 64, 1).is_err());
    assert!(AxiamKsf::scrypt(17, 8, 64).is_err());

    assert!(AxiamKsf::argon2id(19456, 2, 1).is_ok());
    assert!(AxiamKsf::scrypt(17, 8, 1).is_ok());
}

#[test]
fn malformed_hex_is_rejected_rather_than_silently_truncated() {
    let ksf = AxiamKsf::argon2id(8192, 1, 1).unwrap();
    let (state, _) = ClientRegistrationState::start(fixture_password()).unwrap();
    assert!(state.finish(fixture_password(), "zzzz", &ksf).is_err());

    let (state, _) = ClientLoginState::start(fixture_password()).unwrap();
    assert!(
        state
            .finish(fixture_password(), "not hex at all", &ksf)
            .is_err()
    );
}
