//! Integration tests for CaService — CA keypair generation and validation.

use axiam_core::models::certificate::{CreateCaCertificate, KeyAlgorithm};
use axiam_core::repository::CaCertificateRepository as _;
use axiam_db::repository::SurrealCaCertificateRepository;
use axiam_pki::ca::{CaService, PkiConfig};
use surrealdb::Surreal;
use surrealdb::engine::local::Mem;

/// The CA key custodians these tests run against.
///
/// The same all-zero key `test_pki_config` uses, so a CA generated by one
/// service and signed with by another opens. Built through
/// `custodians_from_env` rather than by hand: it is the function the
/// composition root calls, and a test that assembled custody differently would
/// agree with itself and not with production.
#[allow(dead_code)]
fn test_ca_custodians() -> std::sync::Arc<axiam_pki::CaKeyCustodians> {
    std::sync::Arc::new(
        axiam_pki::custodians_from_env(Some([0u8; 32])) // gitleaks:allow
            .expect("test CA key custodians"),
    )
}

type TestDb = surrealdb::engine::local::Db;

async fn setup_db() -> Surreal<TestDb> {
    let db = Surreal::new::<Mem>(()).await.unwrap();
    db.use_ns("test").use_db("test").await.unwrap();
    axiam_db::run_migrations(&db).await.unwrap();
    db
}

fn test_pki_config() -> PkiConfig {
    PkiConfig {
        encryption_key: Some([0u8; 32]), // gitleaks:allow
        ..Default::default()
    }
}

// ---------------------------------------------------------------------------
// Happy path
// ---------------------------------------------------------------------------

#[tokio::test]
async fn ca_generate_ed25519_returns_valid_pem_and_fingerprint() {
    let db = setup_db().await;
    let repo = SurrealCaCertificateRepository::new(db);
    let svc = CaService::new(
        repo,
        test_pki_config(),
        std::sync::Arc::new(tokio::sync::Semaphore::new(4)),
        test_ca_custodians(),
    );

    let result = svc
        .generate(CreateCaCertificate {
            organization_id: uuid::Uuid::new_v4(),
            subject: "Test CA Ed25519".into(),
            key_algorithm: KeyAlgorithm::Ed25519,
            validity_days: 365,
            intermediate_subject: None,
            intermediate_validity_days: None,
            issue_from_root: false,
        })
        .await
        .expect("CA generation must succeed");

    assert!(
        // `Option` since Vault's PKI engine became a custodian: under
        // `vault_pki` there is no key to return. Under this test's database
        // custody there is, and its absence would be the bug.
        !result.private_key_pem.unwrap_or_default().is_empty(),
        "private key PEM must be non-empty"
    );
    assert!(
        result.certificate.public_cert_pem.contains("CERTIFICATE"),
        "public cert PEM must contain CERTIFICATE header"
    );
    assert!(
        !result.certificate.fingerprint.is_empty(),
        "fingerprint must be non-empty"
    );
}

// ---------------------------------------------------------------------------
// Reject cases
// ---------------------------------------------------------------------------

#[tokio::test]
async fn ca_generate_rejects_zero_validity() {
    let db = setup_db().await;
    let repo = SurrealCaCertificateRepository::new(db);
    let svc = CaService::new(
        repo,
        test_pki_config(),
        std::sync::Arc::new(tokio::sync::Semaphore::new(4)),
        test_ca_custodians(),
    );

    let result = svc
        .generate(CreateCaCertificate {
            organization_id: uuid::Uuid::new_v4(),
            subject: "Test CA".into(),
            key_algorithm: KeyAlgorithm::Ed25519,
            validity_days: 0,
            intermediate_subject: None,
            intermediate_validity_days: None,
            issue_from_root: false,
        })
        .await;

    assert!(result.is_err(), "validity_days=0 must be rejected");
}

#[tokio::test]
async fn ca_generate_rejects_validity_above_max() {
    let db = setup_db().await;
    let repo = SurrealCaCertificateRepository::new(db);
    let svc = CaService::new(
        repo,
        test_pki_config(),
        std::sync::Arc::new(tokio::sync::Semaphore::new(4)),
        test_ca_custodians(),
    );

    let result = svc
        .generate(CreateCaCertificate {
            organization_id: uuid::Uuid::new_v4(),
            subject: "Test CA".into(),
            key_algorithm: KeyAlgorithm::Ed25519,
            validity_days: 99_999,
            intermediate_subject: None,
            intermediate_validity_days: None,
            issue_from_root: false,
        })
        .await;

    assert!(result.is_err(), "validity_days above MAX must be rejected");
}

// ---------------------------------------------------------------------------
// Key custody migration
// ---------------------------------------------------------------------------
//
// Custody is recorded per CA rather than read from configuration, which is what
// lets a deployment that adopts Vault keep issuing from the CAs it already had.
// The cost is that adopting Vault otherwise changes nothing about those keys —
// they stay in the database forever. `migrate_key_custody` is the way out, and
// these pin the guard rails around it.

#[tokio::test]
async fn migrating_to_the_custodian_a_ca_already_uses_is_refused() {
    // Not an error out of paranoia: a "successful" no-op would tell an operator
    // their key had moved when it had not.
    let db = setup_db().await;
    let repo = SurrealCaCertificateRepository::new(db);
    let svc = CaService::new(
        repo,
        test_pki_config(),
        std::sync::Arc::new(tokio::sync::Semaphore::new(4)),
        test_ca_custodians(),
    );

    let org_id = uuid::Uuid::new_v4();
    let ca = svc
        .generate(CreateCaCertificate {
            organization_id: org_id,
            subject: "CN=Already Here".into(),
            key_algorithm: KeyAlgorithm::Ed25519,
            validity_days: 365,
            intermediate_subject: None,
            intermediate_validity_days: None,
            issue_from_root: false,
        })
        .await
        .expect("CA generation");

    let err = svc
        .migrate_key_custody(org_id, ca.certificate.id)
        .await
        .expect_err("moving a key to where it already is must be refused");
    assert!(
        err.to_string().contains("already held"),
        "the error must say why, got: {err}"
    );
}

#[tokio::test]
async fn migrating_a_ca_axiam_holds_no_key_for_is_refused() {
    // An imported trust anchor with no `private_key_pem`. There is nothing to
    // move, and saying so is more use than a decryption failure would be.
    let db = setup_db().await;
    let repo = SurrealCaCertificateRepository::new(db.clone());
    let svc = CaService::new(
        repo.clone(),
        test_pki_config(),
        std::sync::Arc::new(tokio::sync::Semaphore::new(4)),
        test_ca_custodians(),
    );

    let org_id = uuid::Uuid::new_v4();
    // Write the row directly: `External` custody is what an import with no key
    // produces, and constructing it here keeps the test about the migration.
    let stored = repo
        .create(axiam_core::models::certificate::StoreCaCertificate {
            id: uuid::Uuid::new_v4(),
            organization_id: org_id,
            tenant_id: None,
            parent_ca_id: None,
            subject: "CN=Offline Root".into(),
            public_cert_pem: "-----BEGIN CERTIFICATE-----\nX\n-----END CERTIFICATE-----".into(),
            chain_pem: None,
            fingerprint: "sha256:abc".into(),
            key_algorithm: KeyAlgorithm::Ed25519,
            not_before: chrono::Utc::now() - chrono::Duration::minutes(1),
            not_after: chrono::Utc::now() + chrono::Duration::days(365),
            encrypted_private_key: None,
            key_custody: axiam_core::ca_keys::CaKeyCustody::External,
            key_locator: None,
        })
        .await
        .expect("store");

    let err = svc
        .migrate_key_custody(org_id, stored.id)
        .await
        .expect_err("there is no key to move");
    assert!(
        err.to_string().contains("no private key"),
        "the error must name the reason, got: {err}"
    );
}
