//! mTLS chain verification tests (SEC-024).
//!
//! Validates that `DeviceAuthService::authenticate` cryptographically verifies
//! the client certificate chain to the tenant/org CA — not just the stored
//! fingerprint — so a forged leaf with a matching fingerprint is rejected.
//!
//! Three cases:
//!   1. Accept: leaf signed by the tenant CA → authentication succeeds
//!   2. Reject: self-signed leaf with a matching stored fingerprint (forged) → chain error
//!   3. Reject: issuer CA not found (no-CA case) → fails closed

use axiam_core::models::certificate::{
    CertificateType, CreateCaCertificate, CreateCertificate, KeyAlgorithm, StoreCertificate,
};
use axiam_core::models::service_account::CreateServiceAccount;
use axiam_core::repository::{
    CaCertificateRepository, CertificateRepository, ServiceAccountRepository,
};
use axiam_db::repository::{
    SurrealCaCertificateRepository, SurrealCertificateRepository, SurrealServiceAccountRepository,
};
use axiam_pki::ca::{CaService, PkiConfig};
use axiam_pki::cert::CertService;
use axiam_pki::mtls::DeviceAuthService;
use chrono::{Duration, Utc};
use rcgen::{CertificateParams, DnType, IsCa, KeyPair};
use sha2::{Digest, Sha256};
use surrealdb::Surreal;
use surrealdb::engine::local::Mem;

/// The CA key custodians these tests run against.
///
/// The same all-zero key `test_pki_config` uses, so a CA generated by one
/// service and signed with by another opens. Built through
/// `custodians_from_env` rather than by hand: it is the function the
/// composition root calls, and a test that assembled custody differently would
/// agree with itself and not with production.
#[allow(dead_code)]
fn test_ca_custodians() -> std::sync::Arc<axiam_pki::CaKeyCustodians> {
    std::sync::Arc::new(
        axiam_pki::custodians_from_env(Some([0u8; 32])) // gitleaks:allow
            .expect("test CA key custodians"),
    )
}

type TestDb = surrealdb::engine::local::Db;

async fn setup_db() -> Surreal<TestDb> {
    let db = Surreal::new::<Mem>(()).await.unwrap();
    db.use_ns("test").use_db("test").await.unwrap();
    axiam_db::run_migrations(&db).await.unwrap();
    db
}

fn test_pki_config() -> PkiConfig {
    PkiConfig {
        encryption_key: Some([0u8; 32]), // gitleaks:allow
        ..Default::default()
    }
}

// ---------------------------------------------------------------------------
// Case 1: Accept — leaf cert properly signed by the tenant CA
// ---------------------------------------------------------------------------

#[tokio::test]
async fn mtls_chain_accept_leaf_signed_by_tenant_ca() {
    let db = setup_db().await;

    let org_id = uuid::Uuid::new_v4();
    let tenant_id = uuid::Uuid::new_v4();
    let sem = std::sync::Arc::new(tokio::sync::Semaphore::new(4));

    // Generate a real CA via CaService (stored in DB)
    let ca_repo = SurrealCaCertificateRepository::new(db.clone());
    let ca_svc = CaService::new(
        ca_repo.clone(),
        test_pki_config(),
        sem.clone(),
        test_ca_custodians(),
    );
    let ca = ca_svc
        .generate(CreateCaCertificate {
            organization_id: org_id,
            subject: "Chain Test CA".into(),
            key_algorithm: KeyAlgorithm::Ed25519,
            validity_days: 365,
            intermediate_subject: None,
            intermediate_validity_days: None,
            issue_from_root: false,
        })
        .await
        .expect("CA generation must succeed");

    // Issue a leaf cert via CertService (signed by the CA, stored in DB)
    let cert_repo = SurrealCertificateRepository::new(db.clone());
    let cert_svc = CertService::new(
        ca_repo.clone(),
        cert_repo.clone(),
        test_pki_config(),
        sem.clone(),
        test_ca_custodians(),
    );
    let leaf = cert_svc
        .generate(
            org_id,
            CreateCertificate {
                tenant_id,
                issuer_ca_id: ca.certificate.id,
                subject: "CN=chain-test-device-001".into(),
                cert_type: CertificateType::Device,
                key_algorithm: KeyAlgorithm::Ed25519,
                validity_days: 30,
                metadata: None,
            },
            None,
        )
        .await
        .expect("leaf cert generation must succeed");

    // Bind leaf to a service account
    let sa_repo = SurrealServiceAccountRepository::new(db.clone());
    let (sa, _secret) = sa_repo
        .create(CreateServiceAccount {
            tenant_id,
            name: "Chain Test SA".into(),
            description: None,
        })
        .await
        .expect("service account creation must succeed");
    cert_repo
        .bind_to_service_account(tenant_id, leaf.certificate.id, sa.id)
        .await
        .expect("cert bind must succeed");

    // Enable the CA as an mTLS trust anchor.
    //
    // Being signed by a CA that exists is not sufficient and no longer was the
    // moment the flag was introduced: authentication requires chaining to a CA
    // an operator actually enabled for it. Without this the leaf below is
    // correctly refused, and this fixture would be asserting the behaviour the
    // flag exists to prevent.
    ca_repo
        .set_mtls_trust_anchor(org_id, ca.certificate.id, true)
        .await
        .expect("enabling the CA as an mTLS trust anchor must succeed");

    // Authenticate — the leaf is signed by a CA in the DB that is enabled as an
    // anchor → must succeed
    let svc_auth = DeviceAuthService::new(cert_repo, ca_repo);
    let identity = svc_auth
        .authenticate(&leaf.certificate.public_cert_pem)
        .await
        .expect("leaf signed by a trusted tenant CA must authenticate successfully");

    assert_eq!(identity.service_account_id, sa.id);
    assert_eq!(identity.tenant_id, tenant_id);
}

// ---------------------------------------------------------------------------
// Case 1b: Reject — leaf signed by a real CA that is NOT a trust anchor
// ---------------------------------------------------------------------------
//
// The mirror of case 1, and the one that was missing. Everything is valid —
// the CA exists, is Active and in date, the signature verifies, and the leaf is
// bound to a service account. The only thing wrong is that nobody enabled the
// CA for mTLS. Before the anchor check this authenticated, which made
// `mtls_trust_anchor` decorative on the proxy-terminated path.

#[tokio::test]
async fn mtls_chain_reject_leaf_from_ca_that_is_not_a_trust_anchor() {
    let db = setup_db().await;

    let org_id = uuid::Uuid::new_v4();
    let tenant_id = uuid::Uuid::new_v4();
    let sem = std::sync::Arc::new(tokio::sync::Semaphore::new(4));

    let ca_repo = SurrealCaCertificateRepository::new(db.clone());
    let ca_svc = CaService::new(
        ca_repo.clone(),
        test_pki_config(),
        sem.clone(),
        test_ca_custodians(),
    );
    let ca = ca_svc
        .generate(CreateCaCertificate {
            organization_id: org_id,
            subject: "Unflagged CA".into(),
            key_algorithm: KeyAlgorithm::Ed25519,
            validity_days: 365,
            intermediate_subject: None,
            intermediate_validity_days: None,
            issue_from_root: false,
        })
        .await
        .expect("CA generation must succeed");
    // Deliberately NOT flagged as an mTLS trust anchor.

    let cert_repo = SurrealCertificateRepository::new(db.clone());
    let cert_svc = CertService::new(
        ca_repo.clone(),
        cert_repo.clone(),
        test_pki_config(),
        sem.clone(),
        test_ca_custodians(),
    );
    let leaf = cert_svc
        .generate(
            org_id,
            CreateCertificate {
                tenant_id,
                issuer_ca_id: ca.certificate.id,
                subject: "CN=unflagged-device-001".into(),
                cert_type: CertificateType::Device,
                key_algorithm: KeyAlgorithm::Ed25519,
                validity_days: 30,
                metadata: None,
            },
            None,
        )
        .await
        .expect("leaf cert generation must succeed");

    // Bound, so a refusal cannot be attributed to a missing binding — which is
    // the other reason this endpoint says no, and would make the assertion pass
    // without testing trust at all.
    let sa_repo = SurrealServiceAccountRepository::new(db.clone());
    let (sa, _secret) = sa_repo
        .create(CreateServiceAccount {
            tenant_id,
            name: "Unflagged CA SA".into(),
            description: None,
        })
        .await
        .expect("service account creation must succeed");
    cert_repo
        .bind_to_service_account(tenant_id, leaf.certificate.id, sa.id)
        .await
        .expect("cert bind must succeed");

    let svc_auth = DeviceAuthService::new(cert_repo, ca_repo);
    let err = svc_auth
        .authenticate(&leaf.certificate.public_cert_pem)
        .await
        .expect_err("a leaf whose CA is not an mTLS trust anchor must be refused");

    assert!(
        err.to_string().contains("trust anchor"),
        "the refusal must name the reason, so an operator can tell it from a \
         missing binding or a bad signature; got: {err}"
    );
}

// ---------------------------------------------------------------------------
// Case 2: Reject — self-signed (forged) leaf with matching stored fingerprint
// ---------------------------------------------------------------------------
//
// Attack: an attacker generates a self-signed cert, submits it for registration
// (or exploits a race), and authenticates. The fingerprint matches the DB
// record but the cert was not signed by the tenant CA.
//
// The chain verify in DeviceAuthService::authenticate must catch this.

#[tokio::test]
async fn mtls_chain_reject_forged_leaf_with_matching_fingerprint() {
    let db = setup_db().await;
    let tenant_id = uuid::Uuid::new_v4();
    let org_id = uuid::Uuid::new_v4();
    let now = Utc::now();

    // 1. Generate a self-signed "forged" leaf cert using rcgen directly
    //    (NOT signed by any CA stored in the DB).
    let key_pair = KeyPair::generate_for(&rcgen::PKCS_ED25519).expect("keygen must succeed");
    let mut params = CertificateParams::new(Vec::<String>::new()).expect("params must build");
    params
        .distinguished_name
        .push(DnType::CommonName, "forged-device");
    params.is_ca = IsCa::NoCa;
    params.not_before = time::OffsetDateTime::from_unix_timestamp(now.timestamp()).unwrap();
    params.not_after =
        time::OffsetDateTime::from_unix_timestamp(now.timestamp() + 86_400 * 30).unwrap();
    let forged_cert = params
        .self_signed(&key_pair)
        .expect("self-sign must succeed");
    let forged_pem = forged_cert.pem();
    let forged_der = forged_cert.der().to_vec();
    let fingerprint = hex::encode(Sha256::digest(&forged_der));

    // 2. Store a real CA in the DB (so the CA lookup succeeds, but the cert
    //    was NOT signed by this CA — the signature verify must fail).
    let ca_repo = SurrealCaCertificateRepository::new(db.clone());
    let sem = std::sync::Arc::new(tokio::sync::Semaphore::new(4));
    let ca_svc = CaService::new(
        ca_repo.clone(),
        test_pki_config(),
        sem.clone(),
        test_ca_custodians(),
    );
    let real_ca = ca_svc
        .generate(CreateCaCertificate {
            organization_id: org_id,
            subject: "Real CA (forged-leaf test)".into(),
            key_algorithm: KeyAlgorithm::Ed25519,
            validity_days: 365,
            intermediate_subject: None,
            intermediate_validity_days: None,
            issue_from_root: false,
        })
        .await
        .expect("real CA must be created");

    // 3. Register the forged cert in the DB with `issuer_ca_id` pointing to the
    //    real CA. The fingerprint matches what authenticate() will compute from the PEM.
    let cert_repo = SurrealCertificateRepository::new(db.clone());
    let _stored = cert_repo
        .create(StoreCertificate {
            tenant_id,
            issuer_ca_id: real_ca.certificate.id,
            subject: "CN=forged-device".into(),
            public_cert_pem: forged_pem.clone(),
            fingerprint,
            cert_type: CertificateType::Device,
            key_algorithm: KeyAlgorithm::Ed25519,
            not_before: now,
            not_after: now + Duration::days(30),
            metadata: serde_json::json!({}),
        })
        .await
        .expect("storing forged cert in DB must succeed");

    // 4. Authenticate — fingerprint matches (passes step 2), status/expiry pass,
    //    but chain verify must FAIL because the cert is self-signed, not by real_ca.
    let svc_auth = DeviceAuthService::new(cert_repo, ca_repo);
    let result = svc_auth.authenticate(&forged_pem).await;

    assert!(result.is_err(), "forged self-signed leaf must be rejected");
    let err_msg = format!("{:?}", result.unwrap_err());
    assert!(
        err_msg.contains("chain verify failed") || err_msg.contains("verify"),
        "error must mention chain/signature verify failure, got: {err_msg}"
    );
}

// ---------------------------------------------------------------------------
// Case 3: Reject — no active CA cert (fail-closed when CA is missing)
// ---------------------------------------------------------------------------

#[tokio::test]
async fn mtls_chain_reject_when_no_ca_cert_found() {
    let db = setup_db().await;
    let tenant_id = uuid::Uuid::new_v4();
    let now = Utc::now();

    // Generate a self-signed leaf cert (rcgen) and store it in DB with a
    // random issuer_ca_id that does NOT exist in the ca_certificate table.
    let key_pair = KeyPair::generate_for(&rcgen::PKCS_ED25519).unwrap();
    let mut params = CertificateParams::new(Vec::<String>::new()).unwrap();
    params
        .distinguished_name
        .push(DnType::CommonName, "no-ca-device");
    params.is_ca = IsCa::NoCa;
    params.not_before = time::OffsetDateTime::from_unix_timestamp(now.timestamp()).unwrap();
    params.not_after =
        time::OffsetDateTime::from_unix_timestamp(now.timestamp() + 86_400 * 30).unwrap();
    let leaf_cert = params.self_signed(&key_pair).unwrap();
    let leaf_pem = leaf_cert.pem();
    let leaf_der = leaf_cert.der().to_vec();
    let fingerprint = hex::encode(Sha256::digest(&leaf_der));

    let nonexistent_ca_id = uuid::Uuid::new_v4();

    let cert_repo = SurrealCertificateRepository::new(db.clone());
    let ca_repo = SurrealCaCertificateRepository::new(db.clone());

    cert_repo
        .create(StoreCertificate {
            tenant_id,
            issuer_ca_id: nonexistent_ca_id,
            subject: "CN=no-ca-device".into(),
            public_cert_pem: leaf_pem.clone(),
            fingerprint,
            cert_type: CertificateType::Device,
            key_algorithm: KeyAlgorithm::Ed25519,
            not_before: now,
            not_after: now + Duration::days(30),
            metadata: serde_json::json!({}),
        })
        .await
        .expect("storing cert with missing CA must succeed");

    // Authenticate — CA lookup fails → must fail closed
    let svc_auth = DeviceAuthService::new(cert_repo, ca_repo);
    let result = svc_auth.authenticate(&leaf_pem).await;

    assert!(result.is_err(), "no-CA case must fail closed");
    let err_msg = format!("{:?}", result.unwrap_err());
    assert!(
        err_msg.contains("no CA certificate")
            || err_msg.contains("Certificate")
            || err_msg.contains("chain verify"),
        "error must indicate CA lookup failure, got: {err_msg}"
    );
}

// ---------------------------------------------------------------------------
// Case 4: Reject — issuing CA has been revoked (SECHRD-05)
// ---------------------------------------------------------------------------
//
// The leaf cert is genuinely signed by the CA and would otherwise pass chain
// verification, but the issuing CA itself has since been revoked. Device
// auth must fail closed before `verify_signature` runs.

#[tokio::test]
async fn mtls_rejects_revoked_issuing_ca() {
    let db = setup_db().await;

    let org_id = uuid::Uuid::new_v4();
    let tenant_id = uuid::Uuid::new_v4();
    let sem = std::sync::Arc::new(tokio::sync::Semaphore::new(4));

    let ca_repo = SurrealCaCertificateRepository::new(db.clone());
    let ca_svc = CaService::new(
        ca_repo.clone(),
        test_pki_config(),
        sem.clone(),
        test_ca_custodians(),
    );
    let ca = ca_svc
        .generate(CreateCaCertificate {
            organization_id: org_id,
            subject: "Revoked CA Test".into(),
            key_algorithm: KeyAlgorithm::Ed25519,
            validity_days: 365,
            intermediate_subject: None,
            intermediate_validity_days: None,
            issue_from_root: false,
        })
        .await
        .expect("CA generation must succeed");

    let cert_repo = SurrealCertificateRepository::new(db.clone());
    let cert_svc = CertService::new(
        ca_repo.clone(),
        cert_repo.clone(),
        test_pki_config(),
        sem.clone(),
        test_ca_custodians(),
    );
    let leaf = cert_svc
        .generate(
            org_id,
            CreateCertificate {
                tenant_id,
                issuer_ca_id: ca.certificate.id,
                subject: "CN=revoked-ca-device".into(),
                cert_type: CertificateType::Device,
                key_algorithm: KeyAlgorithm::Ed25519,
                validity_days: 30,
                metadata: None,
            },
            None,
        )
        .await
        .expect("leaf cert generation must succeed");

    let sa_repo = SurrealServiceAccountRepository::new(db.clone());
    let (sa, _secret) = sa_repo
        .create(CreateServiceAccount {
            tenant_id,
            name: "Revoked CA Test SA".into(),
            description: None,
        })
        .await
        .expect("service account creation must succeed");
    cert_repo
        .bind_to_service_account(tenant_id, leaf.certificate.id, sa.id)
        .await
        .expect("cert bind must succeed");

    // Revoke the issuing CA via the repository's own revoke method (no direct
    // SurrealDB escape hatch needed here — a real production path exists).
    ca_repo
        .revoke(org_id, ca.certificate.id)
        .await
        .expect("CA revoke must succeed");

    let svc_auth = DeviceAuthService::new(cert_repo, ca_repo);
    let result = svc_auth
        .authenticate(&leaf.certificate.public_cert_pem)
        .await;

    assert!(
        result.is_err(),
        "device auth against a revoked issuing CA must fail closed"
    );
    let err_msg = format!("{:?}", result.unwrap_err());
    assert!(
        err_msg.contains("issuing CA is not active") || err_msg.contains("Certificate"),
        "error must indicate the issuing CA is not active, got: {err_msg}"
    );
}

// ---------------------------------------------------------------------------
// Case 5: Reject — issuing CA is outside its validity window (SECHRD-05)
// ---------------------------------------------------------------------------
//
// The leaf cert is genuinely signed by the CA and would otherwise pass chain
// verification, but the issuing CA's own `not_after` has passed. Device auth
// must fail closed before `verify_signature` runs.

#[tokio::test]
async fn mtls_rejects_expired_issuing_ca() {
    let db = setup_db().await;

    let org_id = uuid::Uuid::new_v4();
    let tenant_id = uuid::Uuid::new_v4();
    let sem = std::sync::Arc::new(tokio::sync::Semaphore::new(4));

    let ca_repo = SurrealCaCertificateRepository::new(db.clone());
    let ca_svc = CaService::new(
        ca_repo.clone(),
        test_pki_config(),
        sem.clone(),
        test_ca_custodians(),
    );
    let ca = ca_svc
        .generate(CreateCaCertificate {
            organization_id: org_id,
            subject: "Expired CA Test".into(),
            key_algorithm: KeyAlgorithm::Ed25519,
            validity_days: 365,
            intermediate_subject: None,
            intermediate_validity_days: None,
            issue_from_root: false,
        })
        .await
        .expect("CA generation must succeed");

    let cert_repo = SurrealCertificateRepository::new(db.clone());
    let cert_svc = CertService::new(
        ca_repo.clone(),
        cert_repo.clone(),
        test_pki_config(),
        sem.clone(),
        test_ca_custodians(),
    );
    let leaf = cert_svc
        .generate(
            org_id,
            CreateCertificate {
                tenant_id,
                issuer_ca_id: ca.certificate.id,
                subject: "CN=expired-ca-device".into(),
                cert_type: CertificateType::Device,
                key_algorithm: KeyAlgorithm::Ed25519,
                validity_days: 30,
                metadata: None,
            },
            None,
        )
        .await
        .expect("leaf cert generation must succeed");

    let sa_repo = SurrealServiceAccountRepository::new(db.clone());
    let (sa, _secret) = sa_repo
        .create(CreateServiceAccount {
            tenant_id,
            name: "Expired CA Test SA".into(),
            description: None,
        })
        .await
        .expect("service account creation must succeed");
    cert_repo
        .bind_to_service_account(tenant_id, leaf.certificate.id, sa.id)
        .await
        .expect("cert bind must succeed");

    // Test-only escape hatch: no repo method sets an arbitrary validity
    // window, so backdate the CA's `not_after` via a direct SurrealDB
    // UPDATE. This is NOT a new production API — it exists solely to
    // simulate an issuing CA that has aged out of its validity window.
    let past = Utc::now() - Duration::days(1);
    db.query("UPDATE type::record('ca_certificate', $id) SET not_after = $not_after")
        .bind(("id", ca.certificate.id.to_string()))
        .bind(("not_after", past))
        .await
        .expect("test-only backdate query must succeed")
        .check()
        .expect("test-only backdate update must succeed");

    let svc_auth = DeviceAuthService::new(cert_repo, ca_repo);
    let result = svc_auth
        .authenticate(&leaf.certificate.public_cert_pem)
        .await;

    assert!(
        result.is_err(),
        "device auth against an expired issuing CA must fail closed"
    );
    let err_msg = format!("{:?}", result.unwrap_err());
    assert!(
        err_msg.contains("issuing CA certificate is expired") || err_msg.contains("Certificate"),
        "error must indicate the issuing CA is expired, got: {err_msg}"
    );
}

// ---------------------------------------------------------------------------
// Cases 7-9: the chain WALK — a leaf issued by an intermediate
// ---------------------------------------------------------------------------
//
// Every case above ends at the leaf's immediate issuer, so `require_trust_anchor`
// never took a second lap: no test had a CA with a parent at all. That left the
// whole walk — the parent lookup, the per-hop usability check, and the depth
// bound that stops a cycle in `parent_ca_id` hanging a request handler —
// asserted nowhere, in the function that decides whether a client certificate
// is trusted.

/// Root (flagged as the anchor) -> intermediate (not flagged) -> leaf.
///
/// Returns the pieces a test needs to drive `authenticate`.
struct Hierarchy {
    org_id: uuid::Uuid,
    root_id: uuid::Uuid,
    leaf_id: uuid::Uuid,
    service_account_id: uuid::Uuid,
    leaf_pem: String,
    cert_repo: SurrealCaCertificateRepository<TestDb>,
}

async fn a_leaf_beneath_an_intermediate(
    db: &Surreal<TestDb>,
    flag_root_as_anchor: bool,
) -> (Hierarchy, SurrealCertificateRepository<TestDb>) {
    let org_id = uuid::Uuid::new_v4();
    let tenant_id = uuid::Uuid::new_v4();
    let sem = std::sync::Arc::new(tokio::sync::Semaphore::new(4));

    let ca_repo = SurrealCaCertificateRepository::new(db.clone());
    let ca_svc = CaService::new(
        ca_repo.clone(),
        test_pki_config(),
        sem.clone(),
        test_ca_custodians(),
    );

    let root = ca_svc
        .generate(CreateCaCertificate {
            organization_id: org_id,
            subject: "Root CA".into(),
            key_algorithm: KeyAlgorithm::Ed25519,
            validity_days: 3650,
            intermediate_subject: None,
            intermediate_validity_days: None,
            issue_from_root: true,
        })
        .await
        .expect("root CA generation must succeed");

    if flag_root_as_anchor {
        ca_repo
            .set_mtls_trust_anchor(org_id, root.certificate.id, true)
            .await
            .expect("flagging the root as an mTLS trust anchor must succeed");
    }

    let intermediate = ca_svc
        .generate_intermediate(axiam_core::models::certificate::CreateIntermediateCa {
            organization_id: org_id,
            tenant_id,
            parent_ca_id: root.certificate.id,
            subject: "Tenant Signing CA".into(),
            key_algorithm: KeyAlgorithm::Ed25519,
            validity_days: 365,
        })
        .await
        .expect("intermediate CA generation must succeed");
    // Deliberately NOT flagged: the anchor is its parent, which is the whole
    // point of walking.

    let cert_repo = SurrealCertificateRepository::new(db.clone());
    let cert_svc = CertService::new(
        ca_repo.clone(),
        cert_repo.clone(),
        test_pki_config(),
        sem.clone(),
        test_ca_custodians(),
    );
    let leaf = cert_svc
        .generate(
            org_id,
            CreateCertificate {
                tenant_id,
                issuer_ca_id: intermediate.certificate.id,
                subject: "CN=intermediate-issued-device".into(),
                cert_type: CertificateType::Device,
                key_algorithm: KeyAlgorithm::Ed25519,
                validity_days: 30,
                metadata: None,
            },
            None,
        )
        .await
        .expect("leaf cert generation must succeed");

    // Bound, so a refusal can never be attributed to a missing binding.
    let sa_repo = SurrealServiceAccountRepository::new(db.clone());
    let (sa, _secret) = sa_repo
        .create(CreateServiceAccount {
            tenant_id,
            name: "Chain walk SA".into(),
            description: None,
        })
        .await
        .expect("service account creation must succeed");
    cert_repo
        .bind_to_service_account(tenant_id, leaf.certificate.id, sa.id)
        .await
        .expect("cert bind must succeed");

    (
        Hierarchy {
            org_id,
            root_id: root.certificate.id,
            leaf_id: leaf.certificate.id,
            service_account_id: sa.id,
            leaf_pem: leaf.certificate.public_cert_pem.clone(),
            cert_repo: ca_repo,
        },
        cert_repo,
    )
}

#[tokio::test]
async fn mtls_accepts_a_leaf_whose_anchor_is_its_grandparent() {
    // The intermediate is not itself an anchor, so accepting this leaf requires
    // the walk to take a second lap and find the root. If the walk stopped at
    // the immediate issuer, every intermediate-issued device in the fleet would
    // be refused.
    let db = setup_db().await;
    let (h, leaf_repo) = a_leaf_beneath_an_intermediate(&db, true).await;

    let identity = DeviceAuthService::new(leaf_repo, h.cert_repo)
        .authenticate(&h.leaf_pem)
        .await
        .expect("a leaf chaining to a flagged root must authenticate");

    // Resolving to the *right* principal is the point — an accept that
    // returned some other service account would be worse than a refusal.
    assert_eq!(identity.certificate_id, h.leaf_id);
    assert_eq!(identity.service_account_id, h.service_account_id);
}

#[tokio::test]
async fn mtls_refuses_a_chain_whose_only_anchor_has_been_revoked() {
    // An anchor reached through — or as — a revoked CA is not reached at all.
    // The check runs per hop, so revoking the root must refuse a leaf two
    // levels below it, and the message must say which condition failed.
    let db = setup_db().await;
    let (h, leaf_repo) = a_leaf_beneath_an_intermediate(&db, true).await;

    h.cert_repo
        .revoke(h.org_id, h.root_id)
        .await
        .expect("revoking the root CA must succeed");

    let err = DeviceAuthService::new(leaf_repo, h.cert_repo)
        .authenticate(&h.leaf_pem)
        .await
        .expect_err("a chain whose anchor is revoked must fail closed");

    assert!(
        err.to_string().contains("revoked")
            || err.to_string().contains("validity window")
            || err.to_string().contains("trust anchor"),
        "the refusal must name the reason; got: {err}"
    );
}

#[tokio::test]
async fn mtls_refuses_an_intermediate_chain_that_reaches_no_anchor() {
    // Same hierarchy, root left unflagged. The walk runs out of parents rather
    // than out of depth, and that is a different refusal from "not signed by
    // the CA" — an operator who sees this one needs to flag a CA, not reissue
    // a certificate.
    let db = setup_db().await;
    let (h, leaf_repo) = a_leaf_beneath_an_intermediate(&db, false).await;

    let err = DeviceAuthService::new(leaf_repo, h.cert_repo)
        .authenticate(&h.leaf_pem)
        .await
        .expect_err("a chain that reaches no anchor must fail closed");

    assert!(
        err.to_string().contains("trust anchor"),
        "the refusal must name the reason; got: {err}"
    );
}

#[tokio::test]
async fn mtls_refuses_a_client_certificate_that_is_not_parseable_pem() {
    // The first thing `authenticate` does with attacker-controlled input. It
    // reaches the same code on the proxy-header path, where the bytes are
    // whatever a header contained, so failing closed here is what keeps a
    // malformed header from becoming a panic or an unchecked DER parse.
    let db = setup_db().await;
    let cert_repo = SurrealCertificateRepository::new(db.clone());
    let ca_repo = SurrealCaCertificateRepository::new(db.clone());

    let err = DeviceAuthService::new(cert_repo, ca_repo)
        .authenticate("not a certificate at all")
        .await
        .expect_err("unparseable input must be refused, not parsed further");

    assert!(
        err.to_string().contains("invalid client certificate PEM"),
        "the refusal must name the stage that failed; got: {err}"
    );
}

#[tokio::test]
async fn mtls_refuses_a_ca_row_whose_parent_chain_is_a_cycle() {
    // The walk's depth bound exists because `parent_ca_id` is data, and data
    // can describe a cycle. It cannot be reached by building certificates:
    // `CaService` constrains a tenant signing CA to `pathlen: 0`, so a real
    // hierarchy is at most root -> intermediate -> leaf, two hops against a
    // budget of eight. The case the bound actually defends against is a
    // corrupt row, so that is what this writes — straight through the
    // repository, bypassing the service that would refuse it.
    //
    // Without the bound this test does not fail; it hangs, which on a request
    // handler is a worker that never comes back.
    let db = setup_db().await;
    let org_id = uuid::Uuid::new_v4();
    let tenant_id = uuid::Uuid::new_v4();
    let now = Utc::now();

    // A CA that really did sign the leaf, so the run reaches the chain walk
    // rather than stopping at the signature check.
    let ca_key = KeyPair::generate_for(&rcgen::PKCS_ED25519).expect("CA keygen must succeed");
    let mut ca_params = CertificateParams::new(Vec::<String>::new()).expect("CA params must build");
    ca_params
        .distinguished_name
        .push(DnType::CommonName, "Self-parented CA");
    ca_params.is_ca = IsCa::Ca(rcgen::BasicConstraints::Unconstrained);
    let ca_cert = ca_params
        .self_signed(&ca_key)
        .expect("self-sign must succeed");
    let ca_pem = ca_cert.pem();
    let ca_issuer = rcgen::Issuer::from_params(&ca_params, ca_key);

    let leaf_key = KeyPair::generate_for(&rcgen::PKCS_ED25519).expect("leaf keygen must succeed");
    let mut leaf_params =
        CertificateParams::new(Vec::<String>::new()).expect("leaf params must build");
    leaf_params
        .distinguished_name
        .push(DnType::CommonName, "cycle-device");
    leaf_params.is_ca = IsCa::NoCa;
    let leaf_cert = leaf_params
        .signed_by(&leaf_key, &ca_issuer)
        .expect("signing the leaf must succeed");
    let leaf_pem = leaf_cert.pem();
    let fingerprint = hex::encode(Sha256::digest(leaf_cert.der()));

    // The corruption: the CA names itself as its own parent.
    let ca_id = uuid::Uuid::new_v4();
    let ca_repo = SurrealCaCertificateRepository::new(db.clone());
    ca_repo
        .create(axiam_core::models::certificate::StoreCaCertificate {
            id: ca_id,
            organization_id: org_id,
            tenant_id: Some(tenant_id),
            parent_ca_id: Some(ca_id),
            subject: "CN=Self-parented CA".into(),
            public_cert_pem: ca_pem,
            chain_pem: None,
            fingerprint: "ca-fingerprint".into(),
            key_algorithm: KeyAlgorithm::Ed25519,
            not_before: now - Duration::days(1),
            not_after: now + Duration::days(365),
            encrypted_private_key: None,
            key_custody: axiam_core::ca_keys::CaKeyCustody::External,
            key_locator: None,
        })
        .await
        .expect("writing the malformed CA row must succeed — the point is that it can");

    let cert_repo = SurrealCertificateRepository::new(db.clone());
    let leaf = cert_repo
        .create(StoreCertificate {
            tenant_id,
            issuer_ca_id: ca_id,
            subject: "CN=cycle-device".into(),
            public_cert_pem: leaf_pem.clone(),
            fingerprint,
            cert_type: CertificateType::Device,
            key_algorithm: KeyAlgorithm::Ed25519,
            not_before: now,
            not_after: now + Duration::days(30),
            metadata: serde_json::json!({}),
        })
        .await
        .expect("storing the leaf must succeed");

    let sa_repo = SurrealServiceAccountRepository::new(db.clone());
    let (sa, _secret) = sa_repo
        .create(CreateServiceAccount {
            tenant_id,
            name: "Cycle SA".into(),
            description: None,
        })
        .await
        .expect("service account creation must succeed");
    cert_repo
        .bind_to_service_account(tenant_id, leaf.id, sa.id)
        .await
        .expect("cert bind must succeed");

    let err = DeviceAuthService::new(cert_repo, ca_repo)
        .authenticate(&leaf_pem)
        .await
        .expect_err("a cyclic parent chain must be refused, and must terminate");

    assert!(
        err.to_string().contains("longer than the supported depth"),
        "the refusal must name the depth bound, so the row is recognisable as \
         corrupt rather than merely unanchored; got: {err}"
    );
}
