//! REQ-14 AC-5 — PKI fail-fast tests (SEC-012).
//!
//! Verifies that CA generation refuses to operate when no encryption key is
//! configured, instead of silently encrypting CA private keys with an all-zero
//! key (the previous insecure fallback).

use axiam_core::error::AxiamError;
use axiam_core::models::certificate::{CreateCaCertificate, KeyAlgorithm};
use axiam_db::repository::SurrealCaCertificateRepository;
use axiam_pki::{CaService, PkiConfig};
use surrealdb::Surreal;
use surrealdb::engine::local::Mem;

/// The CA key custodians these tests run against.
///
/// The same all-zero key `test_pki_config` uses, so a CA generated by one
/// service and signed with by another opens. Built through
/// `custodians_from_env` rather than by hand: it is the function the
/// composition root calls, and a test that assembled custody differently would
/// agree with itself and not with production.
#[allow(dead_code)]
fn test_ca_custodians() -> std::sync::Arc<axiam_pki::CaKeyCustodians> {
    std::sync::Arc::new(
        axiam_pki::custodians_from_env(Some([0u8; 32])) // gitleaks:allow
            .expect("test CA key custodians"),
    )
}

type TestDb = surrealdb::engine::local::Db;

async fn setup_db() -> Surreal<TestDb> {
    let db = Surreal::new::<Mem>(()).await.unwrap();
    db.use_ns("test").use_db("test").await.unwrap();
    axiam_db::run_migrations(&db).await.unwrap();
    db
}

/// SEC-012: a deployment with no key for CA private keys must not start.
///
/// The guarantee moved earlier and got stronger. It used to be enforced at
/// generate time — a running server that would accept a CA generation request
/// and fail it — and is now enforced when the custodian set is assembled, which
/// the composition root does before it serves anything. A deployment that can
/// take custody of no CA key at all does not boot.
///
/// The error still names the environment variable, which is the part an
/// operator needs: `custodians_from_env` returning "not configured" without
/// saying what configures it is the failure mode this asserts against.
#[tokio::test]
async fn ca_custody_without_any_key_source_refuses_to_build() {
    let err = axiam_pki::custodians_from_env(None)
        .expect_err("a custodian set with no custodian at all must not build");
    match err {
        AxiamError::Internal(msg) => {
            assert!(
                msg.contains("AXIAM__PKI__ENCRYPTION_KEY"),
                "error must name the missing env var, got: {msg}"
            );
            assert!(
                msg.contains("AXIAM__PKI__VAULT_ADDR"),
                "and the alternative, so an operator learns both ways out: {msg}"
            );
        }
        other => panic!("expected AxiamError::Internal, got {other:?}"),
    }
}

/// The complement: a key source *is* enough, and the default is the database.
///
/// This is what every deployment that has never heard of Vault gets, and it
/// must keep working unchanged.
#[tokio::test]
async fn an_encryption_key_alone_yields_database_custody() {
    let custodians = axiam_pki::custodians_from_env(Some([0u8; 32])) // gitleaks:allow
        .expect("an encryption key is enough on its own");
    assert_eq!(
        custodians.default_custody(),
        axiam_core::ca_keys::CaKeyCustody::Database
    );
}

/// SEC-012: generate with a real key must succeed (regression guard).
#[tokio::test]
async fn ca_generate_with_key_ok() {
    let db = setup_db().await;
    let repo = SurrealCaCertificateRepository::new(db);
    let config = PkiConfig {
        encryption_key: Some([0u8; 32]), // gitleaks:allow
        ..Default::default()
    };
    let svc = CaService::new(
        repo,
        config,
        std::sync::Arc::new(tokio::sync::Semaphore::new(4)),
        test_ca_custodians(),
    );

    let result = svc
        .generate(CreateCaCertificate {
            organization_id: uuid::Uuid::new_v4(),
            subject: "Test CA with-key".into(),
            key_algorithm: KeyAlgorithm::Ed25519,
            validity_days: 365,
        })
        .await;

    assert!(result.is_ok(), "generate with a real key must succeed");
}
