//! REQ-14 AC-5 — PKI fail-fast tests (SEC-012).
//!
//! Verifies that taking custody of a CA private key refuses to operate when no
//! key source is configured, instead of silently encrypting CA private keys
//! with an all-zero key (the previous insecure fallback).

use axiam_core::error::AxiamError;
use axiam_core::models::certificate::{CreateCaCertificate, KeyAlgorithm};
use axiam_db::repository::SurrealCaCertificateRepository;
use axiam_pki::{CaService, PkiConfig};
use surrealdb::Surreal;
use surrealdb::engine::local::Mem;

/// The CA key custodians these tests run against.
///
/// The same all-zero key `test_pki_config` uses, so a CA generated by one
/// service and signed with by another opens. Built through
/// `custodians_from_env` rather than by hand: it is the function the
/// composition root calls, and a test that assembled custody differently would
/// agree with itself and not with production.
#[allow(dead_code)]
fn test_ca_custodians() -> std::sync::Arc<axiam_pki::CaKeyCustodians> {
    std::sync::Arc::new(
        axiam_pki::custodians_from_env(Some([0u8; 32])) // gitleaks:allow
            .expect("test CA key custodians"),
    )
}

type TestDb = surrealdb::engine::local::Db;

async fn setup_db() -> Surreal<TestDb> {
    let db = Surreal::new::<Mem>(()).await.unwrap();
    db.use_ns("test").use_db("test").await.unwrap();
    axiam_db::run_migrations(&db).await.unwrap();
    db
}

/// SEC-012: a deployment with no key source refuses to *store* a CA key.
///
/// The guarantee moved earlier than it used to be — it is no longer generate
/// time, but the moment custody is asked for — while deliberately stopping
/// short of startup. Refusing to boot would take down every deployment that
/// issues no certificates at all, for a subsystem it never touches; the e2e
/// stack is one of those, and made that concrete. So assembling the custodian
/// set with nothing configured succeeds, and the refusal lands on the first
/// request that needs somewhere to put a private key.
///
/// The error still names the environment variables, which is the part an
/// operator needs: "not configured" without saying what configures it is the
/// failure mode this asserts against.
#[tokio::test]
async fn ca_custody_without_any_key_source_defers_its_refusal_to_first_use() {
    let custodians = axiam_pki::custodians_from_env(None)
        .expect("a deployment that issues no certificates must still boot");
    assert_eq!(
        custodians.default_custody(),
        None,
        "nothing configured must not be silently substituted with a custodian"
    );

    // `.expect_err` is unavailable here: the Ok side is `&dyn CaKeyStore`,
    // which is not `Debug`.
    let err = match custodians.default_store() {
        Ok(_) => panic!("storing a CA key with no custodian must be refused"),
        Err(e) => e,
    };
    match err {
        AxiamError::Internal(msg) => {
            assert!(
                msg.contains("AXIAM__PKI__ENCRYPTION_KEY"),
                "error must name the missing env var, got: {msg}"
            );
            assert!(
                msg.contains("AXIAM__PKI__VAULT_ADDR"),
                "and the alternative, so an operator learns both ways out: {msg}"
            );
        }
        other => panic!("expected AxiamError::Internal, got {other:?}"),
    }
}

/// The complement: a key source *is* enough, and the default is the database.
///
/// This is what every deployment that has never heard of Vault gets, and it
/// must keep working unchanged.
#[tokio::test]
async fn an_encryption_key_alone_yields_database_custody() {
    let custodians = axiam_pki::custodians_from_env(Some([0u8; 32])) // gitleaks:allow
        .expect("an encryption key is enough on its own");
    assert_eq!(
        custodians.default_custody(),
        Some(axiam_core::ca_keys::CaKeyCustody::Database)
    );
}

/// SEC-012: generate with a real key must succeed (regression guard).
#[tokio::test]
async fn ca_generate_with_key_ok() {
    let db = setup_db().await;
    let repo = SurrealCaCertificateRepository::new(db);
    let config = PkiConfig {
        encryption_key: Some([0u8; 32]), // gitleaks:allow
        ..Default::default()
    };
    let svc = CaService::new(
        repo,
        config,
        std::sync::Arc::new(tokio::sync::Semaphore::new(4)),
        test_ca_custodians(),
    );

    let result = svc
        .generate(CreateCaCertificate {
            organization_id: uuid::Uuid::new_v4(),
            subject: "Test CA with-key".into(),
            key_algorithm: KeyAlgorithm::Ed25519,
            validity_days: 365,
            intermediate_subject: None,
            intermediate_validity_days: None,
            issue_from_root: false,
        })
        .await;

    assert!(result.is_ok(), "generate with a real key must succeed");
}
