//! The SAML IdP signing credential — issuance, sealing, lookup, retirement
//! (T23.2.1, G-2, D-21).
//!
//! What these assert is not that a credential came back but that the right one
//! did: an RSA-4096 leaf with `digitalSignature` and `documentSigning` and
//! nothing else, chaining to the tenant's CA, whose private key is in the
//! datastore as ciphertext and decrypts back to the key that matches the
//! certificate. And that everything that must refuse it, does.
//!
//! No literal key or password appears here: the PKI encryption key is built from
//! random bytes at runtime, every certificate is generated, and no assertion
//! message formats a key, a certificate or a PEM.

use std::sync::{Arc, OnceLock};

use axiam_core::ca_keys::CaKeyCustody;
use axiam_core::error::AxiamError;
use axiam_core::models::certificate::{
    CaCertificate, CertificateType, CreateCaCertificate, CreateCertificate, CreateIntermediateCa,
    KeyAlgorithm, SignCertificateCsr, SignIntermediateCsr, StoreCaCertificate, StoreCertificate,
};
use axiam_core::models::saml_idp_credential::SamlIdpCredentialStatus;
use axiam_core::repository::{
    CaCertificateRepository, CertificateRepository, SamlIdpCredentialRepository,
};
use axiam_db::repository::{
    SurrealCaCertificateRepository, SurrealCertificateRepository,
    SurrealSamlIdpCredentialRepository,
};
use axiam_pki::ca::{CaService, PkiConfig};
use axiam_pki::cert::CertService;
use axiam_pki::{
    DeviceAuthService, IssuingScope, MAX_SAML_IDP_CREDENTIAL_VALIDITY_DAYS,
    SamlIdpCredentialService,
};
use chrono::{Duration, Utc};
use sha2::{Digest, Sha256};
use surrealdb::Surreal;
use surrealdb::engine::local::{Db, Mem};
use uuid::Uuid;
use x509_parser::certificate::X509Certificate;
use x509_parser::prelude::FromDer;
use x509_parser::public_key::PublicKey;

/// The PKI encryption key, built once per process from random bytes so no key
/// literal is in the source and a CA generated by one service opens in another.
fn pki_encryption_key() -> [u8; 32] {
    static KEY: OnceLock<[u8; 32]> = OnceLock::new();
    *KEY.get_or_init(|| {
        let mut bytes = [0u8; 32];
        bytes[..16].copy_from_slice(Uuid::new_v4().as_bytes());
        bytes[16..].copy_from_slice(Uuid::new_v4().as_bytes());
        bytes
    })
}

fn custodians() -> Arc<axiam_pki::CaKeyCustodians> {
    Arc::new(
        axiam_pki::custodians_from_env(Some(pki_encryption_key())).expect("test CA custodians"),
    )
}

fn pki_config() -> PkiConfig {
    PkiConfig {
        encryption_key: Some(pki_encryption_key()),
        ..Default::default()
    }
}

type Creds = SurrealSamlIdpCredentialRepository<Db>;
type CredService = SamlIdpCredentialService<
    SurrealCaCertificateRepository<Db>,
    SurrealCertificateRepository<Db>,
    Creds,
>;

struct Rig {
    cas: CaService<SurrealCaCertificateRepository<Db>>,
    ca_repo: SurrealCaCertificateRepository<Db>,
    certs: CertService<SurrealCaCertificateRepository<Db>, SurrealCertificateRepository<Db>>,
    cert_repo: SurrealCertificateRepository<Db>,
    creds: Creds,
    svc: CredService,
}

async fn rig() -> Rig {
    let db = Surreal::new::<Mem>(()).await.unwrap();
    db.use_ns("test").use_db("test").await.unwrap();
    axiam_db::run_migrations(&db).await.unwrap();
    let ca_repo = SurrealCaCertificateRepository::new(db.clone());
    let cert_repo = SurrealCertificateRepository::new(db.clone());
    let creds = SurrealSamlIdpCredentialRepository::new(db.clone());
    let sem = Arc::new(tokio::sync::Semaphore::new(4));
    let certs = CertService::new(
        ca_repo.clone(),
        cert_repo.clone(),
        pki_config(),
        sem.clone(),
        custodians(),
    );
    Rig {
        cas: CaService::new(ca_repo.clone(), pki_config(), sem, custodians()),
        svc: SamlIdpCredentialService::new(certs.clone(), custodians(), creds.clone()),
        certs,
        ca_repo,
        cert_repo,
        creds,
    }
}

impl Rig {
    /// An organization root CA and, beneath it, a signing CA for `tenant_id`.
    /// Returns `(root, tenant signing CA)`.
    async fn tenant_ca(
        &self,
        org_id: Uuid,
        tenant_id: Uuid,
        validity_days: u32,
    ) -> (CaCertificate, CaCertificate) {
        let root = self
            .cas
            .generate(CreateCaCertificate {
                organization_id: org_id,
                subject: "Test Org Root CA".into(),
                key_algorithm: KeyAlgorithm::Ed25519,
                validity_days: 3650,
                intermediate_subject: None,
                intermediate_validity_days: None,
                issue_from_root: false,
            })
            .await
            .expect("root CA")
            .certificate;
        let signing = self
            .cas
            .generate_intermediate(CreateIntermediateCa {
                organization_id: org_id,
                tenant_id,
                parent_ca_id: root.id,
                subject: "Tenant Signing CA".into(),
                key_algorithm: KeyAlgorithm::Ed25519,
                validity_days,
            })
            .await
            .expect("tenant signing CA")
            .certificate;
        (root, signing)
    }
}

fn with_cert<T>(pem: &str, f: impl FnOnce(&X509Certificate<'_>) -> T) -> T {
    let (_, block) = x509_parser::pem::parse_x509_pem(pem.as_bytes()).expect("PEM");
    let (_, cert) = X509Certificate::from_der(&block.contents).expect("DER");
    f(&cert)
}

fn der_of(pem: &str) -> Vec<u8> {
    x509_parser::pem::parse_x509_pem(pem.as_bytes())
        .expect("PEM")
        .1
        .contents
}

fn contains_subslice(haystack: &[u8], needle: &[u8]) -> bool {
    !needle.is_empty() && haystack.windows(needle.len()).any(|w| w == needle)
}

// ---------------------------------------------------------------------------
// The credential itself
// ---------------------------------------------------------------------------

/// Acceptance 1, 4 and 5 in one issuance (RSA-4096 generation is the expensive
/// step, so one credential carries every assertion about a good one).
#[tokio::test]
async fn an_issued_credential_has_the_saml_profile_chains_to_its_ca_and_seals_its_key() {
    let rig = rig().await;
    let (org, tenant) = (Uuid::new_v4(), Uuid::new_v4());
    let (_root, ca) = rig.tenant_ca(org, tenant, 1825).await;

    let credential = rig
        .svc
        .issue(
            org,
            tenant,
            IssuingScope::Tenant,
            ca.id,
            MAX_SAML_IDP_CREDENTIAL_VALIDITY_DAYS,
            SamlIdpCredentialStatus::Active,
        )
        .await
        .expect("issuance");

    assert_eq!(credential.tenant_id, tenant);
    assert_eq!(credential.issuer_ca_id, ca.id);
    assert_eq!(credential.status, SamlIdpCredentialStatus::Active);
    assert_eq!(credential.key_custody, CaKeyCustody::Database);

    // --- the certificate, parsed back ---
    with_cert(&credential.certificate_pem, |cert| {
        // digitalSignature only: no keyEncipherment even though the key is RSA.
        let ku = cert.key_usage().expect("readable").expect("present").value;
        assert!(ku.digital_signature());
        assert!(!ku.key_encipherment());
        assert_eq!(ku.flags, 1, "digitalSignature and nothing else");

        // documentSigning only — no serverAuth, no clientAuth.
        let eku = cert
            .extended_key_usage()
            .expect("readable")
            .expect("present")
            .value;
        assert!(!eku.any && !eku.server_auth && !eku.client_auth);
        assert!(!eku.code_signing && !eku.email_protection);
        assert!(!eku.time_stamping && !eku.ocsp_signing);
        let other: Vec<String> = eku.other.iter().map(|o| o.to_id_string()).collect();
        assert_eq!(other, vec!["1.3.6.1.5.5.7.3.36".to_string()]);

        // No SANs, and not a CA.
        assert!(cert.subject_alternative_name().expect("readable").is_none());
        assert!(
            cert.basic_constraints()
                .expect("readable")
                .is_none_or(|bc| !bc.value.ca)
        );

        // RSA-4096.
        match cert.public_key().parsed().expect("public key") {
            PublicKey::RSA(rsa) => assert_eq!(rsa.key_size(), 4096),
            _ => panic!("the SAML signing key must be RSA"),
        }

        // Chains to the tenant CA: issuer DN and a verifying signature.
        with_cert(&ca.public_cert_pem, |ca_cert| {
            assert_eq!(cert.issuer(), ca_cert.subject());
            cert.verify_signature(Some(ca_cert.public_key()))
                .expect("signed by the tenant signing CA");
        });

        // Validity: at most 730 days, never past the CA.
        let nb = cert.validity().not_before.timestamp();
        let na = cert.validity().not_after.timestamp();
        assert!(na - nb <= 730 * 86_400 + 60);
        assert!(na <= ca.not_after.timestamp());
        assert_eq!(na, credential.not_after.timestamp());

        // The row describes the certificate, not the request.
        assert_eq!(credential.serial, hex::encode(cert.raw_serial()));
    });
    assert_eq!(
        credential.fingerprint,
        hex::encode(Sha256::digest(der_of(&credential.certificate_pem)))
    );

    // --- it is not a `certificate` row, anywhere ---
    assert!(
        rig.certs
            .list(
                tenant,
                axiam_core::repository::Pagination {
                    limit: 100,
                    ..Default::default()
                }
            )
            .await
            .unwrap()
            .items
            .is_empty()
    );
    assert!(matches!(
        rig.certs
            .get_by_fingerprint(tenant, &credential.fingerprint)
            .await,
        Err(AxiamError::NotFound { .. })
    ));
    assert!(matches!(
        rig.cert_repo
            .get_by_fingerprint_global(&credential.fingerprint)
            .await,
        Err(AxiamError::NotFound { .. })
    ));

    // --- it authenticates nobody: device login / mTLS cannot find it ---
    let device_auth = DeviceAuthService::new(rig.cert_repo.clone(), rig.ca_repo.clone());
    assert!(
        device_auth
            .authenticate(&credential.certificate_pem)
            .await
            .is_err()
    );

    // --- the key at rest is ciphertext ---
    let stored = rig
        .creds
        .get_active_sealed(tenant)
        .await
        .unwrap()
        .expect("an active credential")
        .key
        .ciphertext
        .expect("sealed key");

    // --- ...and decrypts back to the key that goes with the certificate ---
    let opened = rig
        .svc
        .get_active_signing_key(org, tenant)
        .await
        .unwrap()
        .expect("an active credential");
    assert_eq!(opened.credential, credential);
    let pem_text: &str = &opened.private_key_pem;
    assert!(pem_text.contains("PRIVATE KEY"));
    assert!(
        !contains_subslice(&stored, pem_text.as_bytes()),
        "the stored bytes must not contain the PEM"
    );
    assert!(
        !contains_subslice(&stored, b"PRIVATE KEY"),
        "the stored bytes must not contain a PEM header"
    );
    let pair = rcgen::KeyPair::from_pem(pem_text).expect("the decrypted key is usable");
    with_cert(&credential.certificate_pem, |cert| {
        assert_eq!(
            rcgen::PublicKeyData::subject_public_key_info(&pair),
            cert.public_key().raw
        );
    });

    // Debug redacts the key.
    let shown = format!("{opened:?}");
    assert!(shown.contains("[REDACTED]"));
    assert!(!shown.contains("PRIVATE KEY"));

    // --- the slot is taken, refused before any key is generated ---
    assert!(matches!(
        rig.svc
            .issue(
                org,
                tenant,
                IssuingScope::Tenant,
                ca.id,
                30,
                SamlIdpCredentialStatus::Active
            )
            .await,
        Err(AxiamError::AlreadyExists { .. })
    ));

    // --- list and get_active return no key material, only facts ---
    assert_eq!(
        rig.svc.list(tenant).await.unwrap(),
        vec![credential.clone()]
    );
    assert_eq!(
        rig.svc.get_active(tenant).await.unwrap(),
        Some(credential.clone())
    );

    // --- another tenant sees and retires nothing ---
    let stranger = Uuid::new_v4();
    assert!(rig.svc.list(stranger).await.unwrap().is_empty());
    assert!(
        rig.svc
            .get_active_signing_key(org, stranger)
            .await
            .unwrap()
            .is_none()
    );
    assert!(matches!(
        rig.svc.retire(stranger, credential.id).await,
        Err(AxiamError::NotFound { .. })
    ));

    // --- retire destroys the key ---
    let retired = rig.svc.retire(tenant, credential.id).await.unwrap();
    assert_eq!(retired.status, SamlIdpCredentialStatus::Retired);
    assert!(
        rig.svc
            .get_active_signing_key(org, tenant)
            .await
            .unwrap()
            .is_none()
    );
    let sealed_left = rig.creds.get_active_sealed(tenant).await.unwrap().is_some();
    assert!(!sealed_left);
}

/// A credential can be issued into the `next` slot beside an active one, and the
/// signer's lookup finds only the active one.
#[tokio::test]
async fn a_next_credential_is_issued_beside_the_active_one() {
    let rig = rig().await;
    let (org, tenant) = (Uuid::new_v4(), Uuid::new_v4());
    let (_root, ca) = rig.tenant_ca(org, tenant, 365).await;

    let active = rig
        .svc
        .issue(
            org,
            tenant,
            IssuingScope::Tenant,
            ca.id,
            90,
            SamlIdpCredentialStatus::Active,
        )
        .await
        .unwrap();
    let next = rig
        .svc
        .issue(
            org,
            tenant,
            IssuingScope::Tenant,
            ca.id,
            90,
            SamlIdpCredentialStatus::Next,
        )
        .await
        .unwrap();

    assert_ne!(active.fingerprint, next.fingerprint);
    assert_eq!(rig.svc.list(tenant).await.unwrap().len(), 2);
    assert_eq!(
        rig.svc.get_active(tenant).await.unwrap().unwrap().id,
        active.id
    );
    assert_eq!(
        rig.svc
            .get_active_signing_key(org, tenant)
            .await
            .unwrap()
            .unwrap()
            .credential
            .id,
        active.id
    );
    // A third in either slot is refused.
    for status in [
        SamlIdpCredentialStatus::Active,
        SamlIdpCredentialStatus::Next,
    ] {
        assert!(matches!(
            rig.svc
                .issue(org, tenant, IssuingScope::Tenant, ca.id, 90, status)
                .await,
            Err(AxiamError::AlreadyExists { .. })
        ));
    }
}

/// The validity is bounded by the CA: a credential asking for what the CA has
/// left is granted and never outlives it.
#[tokio::test]
async fn the_validity_is_bounded_by_the_issuing_ca() {
    let rig = rig().await;
    let (org, tenant) = (Uuid::new_v4(), Uuid::new_v4());
    let (_root, ca) = rig.tenant_ca(org, tenant, 100).await;

    // One day more than the CA has left is refused, naming the number.
    let too_long = rig
        .svc
        .issue(
            org,
            tenant,
            IssuingScope::Tenant,
            ca.id,
            101,
            SamlIdpCredentialStatus::Active,
        )
        .await
        .expect_err("outlives its issuer");
    assert!(matches!(too_long, AxiamError::Validation { .. }));

    let granted = rig
        .svc
        .issue(
            org,
            tenant,
            IssuingScope::Tenant,
            ca.id,
            99,
            SamlIdpCredentialStatus::Active,
        )
        .await
        .expect("what the CA can grant");
    assert!(granted.not_after <= ca.not_after);
}

// ---------------------------------------------------------------------------
// Refusals (all before any RSA key is generated)
// ---------------------------------------------------------------------------

#[tokio::test]
async fn issuance_refuses_a_ca_it_may_not_use() {
    let rig = rig().await;
    let (org, tenant) = (Uuid::new_v4(), Uuid::new_v4());
    let (root, ca) = rig.tenant_ca(org, tenant, 365).await;
    let issue = |org: Uuid, tenant: Uuid, scope: IssuingScope, ca_id: Uuid, days: u32| {
        let svc = rig.svc.clone();
        async move {
            svc.issue(
                org,
                tenant,
                scope,
                ca_id,
                days,
                SamlIdpCredentialStatus::Active,
            )
            .await
        }
    };

    // Another organization's CA: not found, not usable.
    let other_org = Uuid::new_v4();
    let (_other_root, other_ca) = rig.tenant_ca(other_org, tenant, 365).await;
    assert!(matches!(
        issue(org, tenant, IssuingScope::Tenant, other_ca.id, 30).await,
        Err(AxiamError::NotFound { .. })
    ));
    // Another tenant's signing CA in the same organization.
    let other_tenant = Uuid::new_v4();
    let other_tenant_ca = rig
        .cas
        .generate_intermediate(CreateIntermediateCa {
            organization_id: org,
            tenant_id: other_tenant,
            parent_ca_id: root.id,
            subject: "Other Tenant CA".into(),
            key_algorithm: KeyAlgorithm::Ed25519,
            validity_days: 365,
        })
        .await
        .unwrap()
        .certificate;
    assert!(matches!(
        issue(org, tenant, IssuingScope::Tenant, other_tenant_ca.id, 30).await,
        Err(AxiamError::NotFound { .. })
    ));
    // The organization anchor, for a tenant-scope caller.
    assert!(matches!(
        issue(org, tenant, IssuingScope::Tenant, root.id, 30).await,
        Err(AxiamError::NotFound { .. })
    ));

    // A non-signing CA: an imported one whose key AXIAM never held.
    let csr = {
        let pair = rcgen::KeyPair::generate_for(&rcgen::PKCS_ED25519).unwrap();
        let mut params = rcgen::CertificateParams::new(Vec::<String>::new()).unwrap();
        params
            .distinguished_name
            .push(rcgen::DnType::CommonName, "Offline Tenant CA");
        params.serialize_request(&pair).unwrap().pem().unwrap()
    };
    let offline_tenant = Uuid::new_v4();
    let offline = rig
        .cas
        .sign_intermediate_csr(SignIntermediateCsr {
            organization_id: org,
            tenant_id: offline_tenant,
            parent_ca_id: root.id,
            csr_pem: csr,
            validity_days: 365,
        })
        .await
        .unwrap();
    assert_eq!(offline.key_custody, CaKeyCustody::External);
    let refused = issue(org, offline_tenant, IssuingScope::Tenant, offline.id, 30)
        .await
        .expect_err("a CA with no key cannot sign");
    assert!(
        refused.to_string().contains("private key"),
        "the refusal should say the CA holds no key"
    );

    // An expired CA (a row whose window has closed).
    let now = Utc::now();
    let expired_tenant = Uuid::new_v4();
    let expired = rig
        .ca_repo
        .create(StoreCaCertificate {
            id: Uuid::new_v4(),
            organization_id: org,
            tenant_id: Some(expired_tenant),
            parent_ca_id: Some(root.id),
            subject: "Expired Tenant CA".into(),
            public_cert_pem: ca.public_cert_pem.clone(),
            chain_pem: None,
            fingerprint: format!("expired-{}", Uuid::new_v4().simple()),
            key_algorithm: KeyAlgorithm::Ed25519,
            not_before: now - Duration::days(10),
            not_after: now - Duration::days(1),
            encrypted_private_key: ca.encrypted_private_key.clone(),
            key_custody: CaKeyCustody::Database,
            key_locator: None,
        })
        .await
        .unwrap();
    let refused = issue(org, expired_tenant, IssuingScope::Tenant, expired.id, 30)
        .await
        .expect_err("expired");
    assert!(refused.to_string().contains("expired"));

    // A revoked CA.
    rig.cas.revoke(org, ca.id).await.unwrap();
    assert!(
        issue(org, tenant, IssuingScope::Tenant, ca.id, 30)
            .await
            .is_err()
    );

    // Nothing was stored by any refusal.
    assert!(rig.creds.list(tenant).await.unwrap().is_empty());
}

#[tokio::test]
async fn issuance_refuses_a_validity_outside_one_to_730_days_and_a_retired_status() {
    let rig = rig().await;
    let (org, tenant) = (Uuid::new_v4(), Uuid::new_v4());
    let (_root, ca) = rig.tenant_ca(org, tenant, 1825).await;
    assert_eq!(MAX_SAML_IDP_CREDENTIAL_VALIDITY_DAYS, 730);

    for days in [0u32, 731, 825, 3650] {
        assert!(
            matches!(
                rig.svc
                    .issue(
                        org,
                        tenant,
                        IssuingScope::Tenant,
                        ca.id,
                        days,
                        SamlIdpCredentialStatus::Active
                    )
                    .await,
                Err(AxiamError::Validation { .. })
            ),
            "{days} days must be refused"
        );
    }
    assert!(matches!(
        rig.svc
            .issue(
                org,
                tenant,
                IssuingScope::Tenant,
                ca.id,
                30,
                SamlIdpCredentialStatus::Retired
            )
            .await,
        Err(AxiamError::Validation { .. })
    ));
    assert!(rig.creds.list(tenant).await.unwrap().is_empty());
}

// ---------------------------------------------------------------------------
// Internal-only: the generic paths refuse the type
// ---------------------------------------------------------------------------

#[tokio::test]
async fn the_generic_issuance_paths_and_the_certificate_store_refuse_saml_signing() {
    let rig = rig().await;
    let (org, tenant) = (Uuid::new_v4(), Uuid::new_v4());
    let (_root, ca) = rig.tenant_ca(org, tenant, 365).await;

    let generated = rig
        .certs
        .generate(
            org,
            IssuingScope::Tenant,
            CreateCertificate {
                tenant_id: tenant,
                issuer_ca_id: ca.id,
                subject: "saml".into(),
                cert_type: CertificateType::SamlSigning,
                key_algorithm: KeyAlgorithm::Ed25519,
                validity_days: 30,
                metadata: None,
                subject_alt_names: vec![],
            },
            None,
            &[],
        )
        .await;
    assert!(matches!(generated, Err(AxiamError::Validation { .. })));

    let csr = {
        let pair = rcgen::KeyPair::generate_for(&rcgen::PKCS_ED25519).unwrap();
        let mut params = rcgen::CertificateParams::new(Vec::<String>::new()).unwrap();
        params
            .distinguished_name
            .push(rcgen::DnType::CommonName, "saml");
        params.serialize_request(&pair).unwrap().pem().unwrap()
    };
    let signed = rig
        .certs
        .sign_csr(
            org,
            IssuingScope::Tenant,
            SignCertificateCsr {
                tenant_id: tenant,
                issuer_ca_id: ca.id,
                csr_pem: csr,
                cert_type: CertificateType::SamlSigning,
                validity_days: 30,
                metadata: None,
                subject_alt_names: vec![],
            },
            None,
            &[],
        )
        .await;
    assert!(matches!(signed, Err(AxiamError::Validation { .. })));

    // And the store itself will not hold one: the schema's assertion refuses it.
    let now = Utc::now();
    let stored = rig
        .cert_repo
        .create(StoreCertificate {
            tenant_id: tenant,
            issuer_ca_id: ca.id,
            subject: "saml".into(),
            public_cert_pem: ca.public_cert_pem.clone(),
            fingerprint: Uuid::new_v4().simple().to_string(),
            cert_type: CertificateType::SamlSigning,
            key_algorithm: KeyAlgorithm::Ed25519,
            not_before: now,
            not_after: now + Duration::days(1),
            metadata: serde_json::json!({}),
        })
        .await;
    // Refused by the datastore's `cert_type` assertion (D-21: v72 does not widen it).
    assert!(stored.is_err(), "the certificate table must not hold one");
    assert!(
        rig.certs
            .list(
                tenant,
                axiam_core::repository::Pagination {
                    limit: 10,
                    ..Default::default()
                }
            )
            .await
            .unwrap()
            .items
            .is_empty()
    );
}
