//! SurrealDB repository implementations.

mod account_deletion;
mod audit;
mod ca_certificate;
mod certificate;
mod consent;
mod email_config;
mod email_template;
mod email_verification_token;
mod erasure_proof;
mod export_job;
mod federation_config;
mod federation_link;
mod federation_login_state;
mod group;
mod notification_rule;
mod oauth2_auth_code;
mod oauth2_client;
mod oauth2_refresh_token;
mod organization;
mod password_history;
mod password_reset_token;
mod permission;
mod pgp_key;
mod rate_limit;
mod resource;
mod role;
mod saml_replay;
mod scope;
mod service_account;
mod session;
mod settings;
mod tenant;
mod user;
mod webauthn_credential;
mod webhook;

pub use account_deletion::SurrealAccountDeletionRepository;
pub use audit::SurrealAuditLogRepository;
pub use ca_certificate::SurrealCaCertificateRepository;
pub use certificate::SurrealCertificateRepository;
pub use consent::SurrealConsentRepository;
pub use email_config::SurrealEmailConfigRepository;
pub use email_template::SurrealEmailTemplateRepository;
pub use email_verification_token::SurrealEmailVerificationTokenRepository;
pub use erasure_proof::SurrealErasureProofRepository;
pub use export_job::SurrealExportJobRepository;
pub use federation_config::SurrealFederationConfigRepository;
pub use federation_link::SurrealFederationLinkRepository;
pub use federation_login_state::SurrealFederationLoginStateRepository;
pub use group::SurrealGroupRepository;
pub use notification_rule::SurrealNotificationRuleRepository;
pub use oauth2_auth_code::SurrealAuthorizationCodeRepository;
pub use oauth2_client::SurrealOAuth2ClientRepository;
pub use oauth2_refresh_token::SurrealRefreshTokenRepository;
pub use organization::SurrealOrganizationRepository;
pub use password_history::SurrealPasswordHistoryRepository;
pub use password_reset_token::SurrealPasswordResetTokenRepository;
pub use permission::SurrealPermissionRepository;
pub use pgp_key::SurrealPgpKeyRepository;
pub use rate_limit::SurrealRateLimitBucketRepository;
pub use resource::SurrealResourceRepository;
pub use role::SurrealRoleRepository;
pub use saml_replay::SurrealAssertionReplayRepository;
pub use scope::SurrealScopeRepository;
pub use service_account::{SurrealServiceAccountRepository, hash_client_secret};
pub use session::SurrealSessionRepository;
pub use settings::SurrealSettingsRepository;
pub use tenant::SurrealTenantRepository;
pub use user::SurrealUserRepository;
pub use webauthn_credential::SurrealWebauthnCredentialRepository;
pub use webhook::SurrealWebhookRepository;
