//! SurrealDB repository implementations.

mod account_deletion;
mod amqp_nonce_replay;
mod audit;
mod ca_certificate;
mod certificate;
mod ciba_request;
mod consent;
mod device_grant;
mod directory_config;
mod directory_sync_state;
mod email_config;
mod email_template;
mod email_verification_token;
mod erasure_proof;
mod export_job;
mod federation_config;
mod federation_link;
mod federation_login_state;
mod group;
mod mds;
mod minimal_profile_lease;
mod notification_rule;
mod notification_window;
mod oauth2_auth_code;
mod oauth2_client;
mod oauth2_proof_replay;
mod oauth2_refresh_token;
mod oauth2_registration_token;
mod opaque_credential;
mod opaque_server_setup;
mod organization;
mod password_history;
mod password_reset_token;
mod permission;
mod permission_ticket;
mod pgp_key;
mod pushed_auth_request;
mod rate_limit;
mod reactor;
mod resource;
mod revoked_session;
mod role;
mod saml_authn_request;
mod saml_idp_credential;
mod saml_logout_run;
mod saml_replay;
mod saml_service_provider;
mod saml_sp_session;
mod scim_target;
mod scim_token;
mod scope;
mod service_account;
mod session;
mod session_client;
mod settings;
mod ssf_event_buffer;
mod ssf_step_up;
mod ssf_stream;
mod sso_handoff_code;
mod tenant;
pub mod tenant_purge;
mod user;
mod webauthn_attestation_policy;
mod webauthn_credential;
mod webhook;

pub use account_deletion::SurrealAccountDeletionRepository;
pub use amqp_nonce_replay::SurrealAmqpNonceRepository;
pub use audit::SurrealAuditLogRepository;
pub use ca_certificate::SurrealCaCertificateRepository;
pub use certificate::SurrealCertificateRepository;
pub use ciba_request::SurrealCibaRequestRepository;
pub use consent::SurrealConsentRepository;
pub use device_grant::SurrealDeviceGrantRepository;
pub use directory_config::SurrealDirectoryConfigRepository;
pub use directory_sync_state::SurrealDirectorySyncStateRepository;
pub use email_config::SurrealEmailConfigRepository;
pub use email_template::SurrealEmailTemplateRepository;
pub use email_verification_token::SurrealEmailVerificationTokenRepository;
pub use erasure_proof::SurrealErasureProofRepository;
pub use export_job::SurrealExportJobRepository;
pub use federation_config::SurrealFederationConfigRepository;
pub use federation_link::SurrealFederationLinkRepository;
pub use federation_login_state::SurrealFederationLoginStateRepository;
pub use group::SurrealGroupRepository;
pub use mds::SurrealMdsRepository;
pub use minimal_profile_lease::{LeaseClaim, LeaseRecord, SurrealMinimalProfileLeaseRepository};
pub use notification_rule::SurrealNotificationRuleRepository;
pub use notification_window::SurrealNotificationWindowRepository;
pub use oauth2_auth_code::SurrealAuthorizationCodeRepository;
pub use oauth2_client::SurrealOAuth2ClientRepository;
pub use oauth2_proof_replay::SurrealProofReplayRepository;
pub use oauth2_refresh_token::SurrealRefreshTokenRepository;
pub use oauth2_registration_token::SurrealOAuth2RegistrationTokenRepository;
pub use opaque_credential::SurrealOpaqueCredentialRepository;
pub use opaque_server_setup::SurrealOpaqueServerSetupRepository;
pub use organization::SurrealOrganizationRepository;
pub use password_history::SurrealPasswordHistoryRepository;
pub use password_reset_token::SurrealPasswordResetTokenRepository;
pub use permission::SurrealPermissionRepository;
pub use permission_ticket::SurrealPermissionTicketRepository;
pub use pgp_key::SurrealPgpKeyRepository;
pub use pushed_auth_request::SurrealPushedAuthRequestRepository;
pub use rate_limit::SurrealRateLimitBucketRepository;
pub use reactor::SurrealReactorRepository;
pub use resource::SurrealResourceRepository;
pub use revoked_session::SurrealRevokedSessionRepository;
pub use role::SurrealRoleRepository;
pub use saml_authn_request::SurrealPendingSamlRequestRepository;
pub use saml_idp_credential::SurrealSamlIdpCredentialRepository;
pub use saml_logout_run::SurrealSamlLogoutRunRepository;
pub use saml_replay::SurrealAssertionReplayRepository;
pub use saml_service_provider::SurrealSamlServiceProviderRepository;
pub use saml_sp_session::SurrealSamlSpSessionRepository;
pub use scim_target::{
    SurrealScimTargetLinkRepository, SurrealScimTargetRepository, SurrealScimTargetStateRepository,
};
pub use scim_token::SurrealScimTokenRepository;
pub use scope::SurrealScopeRepository;
pub use service_account::SurrealServiceAccountRepository;
pub use session::SurrealSessionRepository;
pub use session_client::SurrealSessionClientRepository;
pub use settings::SurrealSettingsRepository;
pub use ssf_event_buffer::SurrealSsfEventBufferRepository;
pub use ssf_step_up::SurrealSsfStepUpRepository;
pub use ssf_stream::SurrealSsfStreamRepository;
pub use sso_handoff_code::SurrealSsoHandoffCodeRepository;
pub use tenant::SurrealTenantRepository;
pub use user::SurrealUserRepository;
pub use webauthn_attestation_policy::SurrealWebauthnAttestationPolicyRepository;
pub use webauthn_credential::SurrealWebauthnCredentialRepository;
pub use webhook::SurrealWebhookRepository;
