//! SurrealDB repository implementations.

mod audit;
mod ca_certificate;
mod certificate;
mod email_template;
mod federation_config;
mod federation_link;
mod group;
mod oauth2_auth_code;
mod oauth2_client;
mod oauth2_refresh_token;
mod organization;
mod password_history;
mod permission;
mod pgp_key;
mod resource;
mod role;
mod scope;
mod service_account;
mod session;
mod settings;
mod tenant;
mod user;
mod webhook;

pub use audit::SurrealAuditLogRepository;
pub use ca_certificate::SurrealCaCertificateRepository;
pub use certificate::SurrealCertificateRepository;
pub use email_template::SurrealEmailTemplateRepository;
pub use federation_config::SurrealFederationConfigRepository;
pub use federation_link::SurrealFederationLinkRepository;
pub use group::SurrealGroupRepository;
pub use oauth2_auth_code::SurrealAuthorizationCodeRepository;
pub use oauth2_client::SurrealOAuth2ClientRepository;
pub use oauth2_refresh_token::SurrealRefreshTokenRepository;
pub use organization::SurrealOrganizationRepository;
pub use password_history::SurrealPasswordHistoryRepository;
pub use permission::SurrealPermissionRepository;
pub use pgp_key::SurrealPgpKeyRepository;
pub use resource::SurrealResourceRepository;
pub use role::SurrealRoleRepository;
pub use scope::SurrealScopeRepository;
pub use service_account::{SurrealServiceAccountRepository, hash_client_secret};
pub use session::SurrealSessionRepository;
pub use settings::SurrealSettingsRepository;
pub use tenant::SurrealTenantRepository;
pub use user::{SurrealUserRepository, verify_password};
pub use webhook::SurrealWebhookRepository;
